### ISSUE TITLE
qq的以图片形式打开闪照没有了，是为什么？

### ISSUE THREAD

**Issue by lf2533688** [ferredoxin/QNotified#1000]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**模块版本/Module Version**

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
就一个问题描述我咋知道什么问题

**Comment by singleNeuron** [comment]
@lf2533688 我们没删，为啥没有了我们也不知道
