### ISSUE TITLE
[8.8] 仅清除模块缓存会闪退

### ISSUE THREAD

**Issue by kurisucat** [ferredoxin/QNotified#1003]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.17(1938)

**模块版本/Module Version**

* 0.8.20.3eaaf3d

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Taichi 太极 （湛泸·6.1.2-6560）

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

QN 设置界面→底部故障排查→清除缓存

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

对不起我不清楚日志在哪个目录

</code></pre></details>

**Comment by NextAlone** [comment]
清楚缓存会重启qq
