### ISSUE TITLE
[8.8.20.5865] 无法自定义+1图标

### ISSUE THREAD

**Issue by JayChou2021** [ferredoxin/QNotified#1007]
**8.8.20.5865**

* 

**0.8.20.cc4c212 (1629105441)**

* 

**太极：含光·8.0.3.44444**

* 

**QN无法自定义+1图标**

*  连续多个QN版本以及QQ版本出现这种问题，OPPO Reno十倍和红米Note9Pro均存在
* 

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@JayChou2021 国内时间大晚上的不睡觉？
