### ISSUE TITLE
[QQ8.8.20] 侧滑栏按钮间距问题

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#1015]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.20
* 

**模块版本/Module Version**
目前Latest
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
LSPosed 1.5.1
* 

**问题的具体描述/Detailed Description of the Bug**
隐藏侧栏按钮后，侧滑栏拉开，按钮虽然消失但是空隙还在
*  具体描述(如复现BUG所需要的前提和必要操作等)
![Screenshot_20210821-010231_QQ](https://user-images.githubusercontent.com/24774842/130269056-b73f7333-6bb8-4db1-8045-4f2ababc9d6b.png)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

无

</code></pre></details>

**Comment by keta1** [comment]
@Neubulae 没有一个优雅的修复方式，暂且这样吧

**Comment by Neubulae** [comment]
> @Neubulae 没有一个优雅的修复方式，暂且这样吧

oof，那先留在这儿吧
一个有趣的现象就是如果QQ更新了（8.8.12到8.8.17，8.8.17到8.8.20的时候），这里会变正常。重启QQ失效

**Comment by Neubulae** [comment]
最新PR编译了一下，似乎修了

**Comment by NextAlone** [comment]
@Neubulae 刚修了的
