### ISSUE TITLE
[QQ8.8.20] 部分功能未适配

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#1023]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.20

**模块版本/Module Version**

* 0.8.20.0906d3f (1629551370)

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 应用转生

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

 1. 好友页自动续火开关不见了（已经开启的仍可自动续火）
 2. 侧滑栏聊天字数统计不见了
 3. 联系人页精简失效了
 4. 修改@界面排序失效了

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by lightoo1122** [comment]
——建议开设8.8.12+bug反馈专栏

**Comment by NextAlone** [comment]
3. #1022

**Comment by NextAlone** [comment]
4. #1030

**Comment by NextAlone** [comment]
1. #1035

**Comment by NextAlone** [comment]
#1061
