### ISSUE TITLE
[QQ 8.8.20] Bug收集

### ISSUE THREAD

**Issue by NextAlone** [ferredoxin/QNotified#1024]
# 请简述无法使用的功能

---

## 修复进度

**Comment by 575625035** [comment]
群聊屏蔽一起嗨功能失效

**Comment by NextAlone** [comment]
> 群聊屏蔽一起嗨功能失效

#1027

**Comment by Ludwig-OG** [comment]
8.8.20打开qn闪退
[modules_2019-11-11T14_22_29.633.txt](https://github.com/ferredoxin/QNotified/files/7043316/modules_2019-11-11T14_22_29.633.txt)

**Comment by NextAlone** [comment]
> 8.8.20打开qn闪退，已尝试过卸载重装QQ和Qn
> [modules_2019-11-11T14_22_29.633.txt](https://github.com/ferredoxin/QNotified/files/7043316/modules_2019-11-11T14_22_29.633.txt)

qn最新版吗

**Comment by zjzjjz** [comment]
语音转发没有办法正常使用 @NextAlone

**Comment by Ludwig-OG** [comment]
> > 8.8.20打开qn闪退，已尝试过卸载重装QQ和Qn
> > [modules_2019-11-11T14_22_29.633.txt](https://github.com/ferredoxin/QNotified/files/7043316/modules_2019-11-11T14_22_29.633.txt)
> 
> qn最新版吗

QNotified-release 0.8.20.8f93c47，最新的CI版

**Comment by yutuchuyue** [comment]
最新版qq使用这么多板块都不闪退，但是一旦在应用转生里面亦勾选QN模块就闪退，仅有一次成功兼容所有模块不闪退，完整使用（但没有好好珍惜，多加了一个模块，就有闪退了，哭）
或者一同勾选其他模块后，打开勾选QN模块并同意协议后，产生闪退，重进就一直卡页面进不去，如下：
![Uploading Screenshot_2021-08-28-14-19-52-311_com.tencent.mobileqq.jpg…]()

**Comment by cinit** [comment]
@yutuchuyue 请提供闪退时的调用栈回溯

**Comment by yutuchuyue** [comment]
> @yutuchuyue 请提供闪退时的调用栈回溯

是日志吗

**Comment by yutuchuyue** [comment]
> @yutuchuyue 请提供闪退时的调用栈回溯

可能我描述还不够清楚，我再说一遍。

我用不了这个QN模块,分为有三种情况。

1：
![Screenshot_2021-08-28-14-14-16-106_com tencent mobileqq](https://user-images.githubusercontent.com/80840253/131208816-27ec3f33-5a9e-478a-b718-336d31057a23.jpg)
首先我在应用转生里勾选并使用其他任何qq的任何模块都是可以进去的，但一旦勾选了QN模块就会这样子，卡住。
![Screenshot_2021-08-28-14-19-52-311_com tencent mobileqq](https://user-images.githubusercontent.com/80840253/131208859-994c8436-ea7d-4db8-a460-fc060756b4d2.jpg)
2，如果我不勾选其他qq模块，我只用qn模块，我也是可以进去的，而且可以完好的使用，但不能勾选其他qq模块一起使用。

3，以上都还可以接受，但QN模块的那个同意协议有时候点得，能进得去设置，这个没事。可大部分都是点了同意，然后卡住，紧接着黑屏或者无响应。

以上便是我使用最新版qq和最新版qn模块产生的问题，所以那个调用什么的获取不到

**Comment by zjzjjz** [comment]
@NextAlone 
![Screenshot_20210828_184852_com tencent mobileqq](https://user-images.githubusercontent.com/89512963/131215938-f8530638-ac1d-4e7d-9c24-6e082ca3fb60.jpg)

**Comment by zjzjjz** [comment]
@NextAlone 语音转发无效

**Comment by LamGC** [comment]
防撤回功能失效
QQ：8.8.20.5865
太极：Magisk版 129 (60)
Magisk：23.0

**Comment by NextAlone** [comment]
> 防撤回功能失效（话说这是默认开启的吗？没找到开关）
> QN：0.8.21
> QQ：8.8.20.5865
> 太极：Magisk版 129 (60)
> Magisk：23.0

qq净化里

**Comment by LamGC** [comment]
> > 防撤回功能失效（话说这是默认开启的吗？没找到开关）
> > QN：0.8.21
> > QQ：8.8.20.5865
> > 太极：Magisk版 129 (60)
> > Magisk：23.0
> 
> qq净化里

找到了，感谢（另外如果是临时会话的话，防撤回是没有显示对方试图撤回提示的）。

**Comment by LamGC** [comment]
> > > 防撤回功能失效（话说这是默认开启的吗？没找到开关）
> > > QN：0.8.21
> > > QQ：8.8.20.5865
> > > 太极：Magisk版 129 (60)
> > > Magisk：23.0
> > 
> > 
> > qq净化里
> 
> 找到了，感谢（另外如果是私聊的话，防撤回是没有显示对方试图撤回提示的）。

**Comment by NextAlone** [comment]
> @NextAlone 语音转发无效

#1061

**Comment by lightoo1122** [comment]
联系人最下方历史好友入口消失

**Comment by cinit** [comment]
@lightoo1122 那个入口用的人应该不多吧，另外因为BUG消失了的话，仍然可以从设置->qn中进入

**Comment by 1772189738** [comment]
iQOO7应用转生QQ8.7.0无法导出历史好友

**Comment by EWBOOOO** [comment]
花Q 一键20赞功能失效

**Comment by EWBOOOO** [comment]
> # 请简述无法使用的功能
> ## 修复进度

8.8.20 花Q 一键20赞功能失效
