### ISSUE TITLE
[QQ 8.8.20.5865] 聊天框提示文字被自动开启

### ISSUE THREAD

**Issue by lidoworld** [ferredoxin/QNotified#1025]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.20.5865

**模块版本/Module Version**

* 0.8.20.5236021

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSP v1.5.1

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

![Screenshot_2021-08-23-22-27-45-224_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/24887103/130465223-75beb84d-6641-47c1-b3ea-3b8af2cb996c.jpg)

聊天框提示文字被自动开启，本人从未开启和想要开启该功能，但被自动启动。
手动关闭后输入框经常还是有文字，即便成功关闭，过一段时间也会启动该功能。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
好的, 马上修
