### ISSUE TITLE
发送键显示不全

### ISSUE THREAD

**Issue by dailaifu** [ferredoxin/QNotified#1026]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.20(1976)

**模块版本/Module Version**

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

lspxposed v1.5.1(5898)

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

发送键显示不全

**此处贴你获取到的日志信息/Log here**

<details><summary>展
![Uploading Screenshot_20210824-185621.jpg…]()
开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by dailaifu** [comment]
![Uploading Screenshot_20210824-185621.jpg…]()

**Comment by keta1** [comment]
Same #1071
