### ISSUE TITLE
[功能需求]增加去除聊天界面铭牌与红名

### ISSUE THREAD

**Issue by ClokMuch** [ferredoxin/QNotified#103]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ.8.5.5.

**为什么你认为需要此功能**

* QQ原版聊天界面底色为蓝色，使用白色字体会比较和谐，而红色字体就显得突兀；
* 使用上帝模式去除聊天界面中的名牌时，会导致昵称不居中.

**联系到哪些已经存在的bug或者功能**

* 功能：原QQ净化：隐藏会员铭牌.

**具体功能需要/Specific features required**

* 最近消息面板中，VIP昵称为红色，会显得很突兀，希望能将昵称恢复为正常的黑色；
* 聊天面板中，红色昵称配浅蓝色底栏很不协调，希望能将昵称恢复为正常的白色；
* 聊天面板中，希望去除铭牌后，昵称能居中显示（使用上帝模式去除铭牌后，昵称会靠右显示）.

近期才注意到有更新 Issue 模板，故此 Issue 按照模板进行更新 qwq

**Comment by ClokMuch** [comment]
之前想要自己试着适配一下新版的QQ，于是下载了最后一个版本的源码尝试写代码，但是失败了（/_ \）

QQPurify作者好像把源码删掉了，但是我这边有下载一份源码，如果您需要的话我可以发给您 qwq

**Comment by ketal178** [comment]
已添加

**Comment by ClokMuch** [comment]
> 部分已实现

经测试，可去除聊天界面中的铭牌 ✪ ω ✪

**Comment by ClokMuch** [comment]
需求完美解决，感谢各位的努力 ✪ ω ✪
