### ISSUE TITLE
[QQ8.8.20] 净化设置错误

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#1032]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.20

**模块版本/Module Version**

* 0.8.20.8f93c47 (1629829093)

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 应用转生

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

QQ净化设置→侧滑
隐藏夜间模式，登录达人，城市天气开启状态无法保存且点击后弹出隐藏侧滑栏列表的菜单

https://user-images.githubusercontent.com/72146600/130705023-c73a1aa0-0ecd-4d0b-bdbb-d77fa7403c00.mp4

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@lightoo1122 我干的哈哈哈哈哈哈哈哈哈哈哈哈哈哈笑死我了

**Comment by NextAlone** [comment]
是否还有此问题

**Comment by lightoo1122** [comment]
没有了
