### ISSUE TITLE
[功能需求] 屏蔽QQ的弹射表情

### ISSUE THREAD

**Issue by jiasswee** [ferredoxin/QNotified#1033]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.7.0

**为什么你认为需要此功能**

* 弹射表情会满屏弹射，影响聊天心情

**联系到哪些已经存在的bug或者功能**

* ~~ 鹅鹅?这条没有 ~~

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
聊天的时候对方发来一长串弹射表情，看着烦233333

**Comment by NextAlone** [comment]
建议直接让对面别发
