### ISSUE TITLE
[功能需求] 管理员收到群聊申请，自动通过/或者收到指定内容才通过

### ISSUE THREAD

**Issue by javaeryang** [ferredoxin/QNotified#1046]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ

**为什么你认为需要此功能**

* 便捷管理群里申请

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

便捷管理群里申请，适用于大群管理

**Comment by singleNeuron** [comment]
@javaeryang QQ自己不就有自动通过入群申请的功能吗，指定内容的话可以用回答问题

**Comment by javaeryang** [comment]
@singleNeuron 自带的不好用，真的

**Comment by singleNeuron** [comment]
@cinit mirai

**Comment by javaeryang** [comment]
@cinit @singleNeuron 感谢指路
