### ISSUE TITLE
[QQ8.8.17] 跳转错误

### ISSUE THREAD

**Issue by zhuixingzhe-baisheng** [ferredoxin/QNotified#1051]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.17(1938)

**模块版本/Module Version**

* 最新

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

太极
* 

**问题的具体描述/Detailed Description of the Bu

*打开"去你大爷的QQ浏览器"功能，点打卡会跳转到浏览器。

*  具体描述(如复现BUG所需要的前提和必要操作等)

*1.打开"去你大爷的QQ浏览器功能"
2.点击打卡(侧滑的那个打卡)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@zhuixingzhe-baisheng 更新到最新的ci版本了吗

**Comment by zhuixingzhe-baisheng** [comment]
现版本 0.8.21.4f1835a



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ferredoxin/QNotified] [QQ8.8.17] 跳转错误 (#1051)




 
@zhuixingzhe-baisheng 更新到最新的ci版本了吗
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by singleNeuron** [comment]
@zhuixingzhe-baisheng 去 https://t.me/Qnotified_CI 更新到最新版本
