### ISSUE TITLE
O[此处填写QQ或TIM版本号] 简要概况问题

### ISSUE THREAD

**Issue by zazala** [ferredoxin/QNotified#1052]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by zazala** [comment]
![Uploading bubble_left.9.png…]()

**Comment by NextAlone** [comment]
无效issue提交
