### ISSUE TITLE
[功能需求] 群文件“转存永久”按钮

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#1060]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.12+
* 

**为什么你认为需要此功能**
似乎在某个版本开始移除了长按出现转存永久这回事了，能加回来吗
* 

**联系到哪些已经存在的bug或者功能**
如上
* 

**具体功能需要/Specific features required**
如上
*  具体描述(如使用的场景，面临的问题)
如上

**Comment by kongxia535** [comment]
确实，平时想转存永久文件只能在电脑上操作
