### ISSUE TITLE
[功能需求] 加一个可以导入Theme主题包的功能

### ISSUE THREAD

**Issue by QNYXJ** [ferredoxin/QNotified#1067]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.23    Tim暂时不需要
* 

**为什么你认为需要此功能**
QQ给的主题太拉胯了，就算充了会员也难看的要死
所以我建议可以加一个，可以加入实验功能先测试
* 

**联系到哪些已经存在的bug或者功能**
暂时不知道
* 

**具体功能需要/Specific features required**
QQ主题，增加一个可以导入Theme主题包   或者zip主题包的功能
*  具体描述(如使用的场景，面临的问题)
![IMG_20210907_074532](https://user-images.githubusercontent.com/89141407/132266125-08b93c2c-77ce-4c00-bb53-b052d5140c77.jpg)

QQ主题，问题是加入此项功能的可能性不大

**Comment by QNYXJ** [comment]
感觉不太可能啊🙀

**Comment by singleNeuron** [comment]
@QNYXJ 出门左转去用ColorQQ

**Comment by QNYXJ** [comment]
> @QNYXJ 出门左转去用ColorQQ

因为colorQQ2不支持最新版QQ我才提建议的

**Comment by singleNeuron** [comment]
@QNYXJ 那你去找ColorQQ2的作者啊
