### ISSUE TITLE
[8.8.23] 回复不@失效

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#1075]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.23
* 

**模块版本/Module Version**
Latest
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
LSPosed 1.5.3
* 

**问题的具体描述/Detailed Description of the Bug**
应该是最近一次热更新以后失效了？

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by keta1** [comment]
@Neubulae 测试没问题

**Comment by Neubulae** [comment]
在设置里开关功能后重启QQ没问题了，干
