### ISSUE TITLE
[8.8.33] 更新了QNotified 0.8.22.0e4a742，账号被冻结

### ISSUE THREAD

**Issue by youling257** [ferredoxin/QNotified#1085]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.33
* 

**模块版本/Module Version**
0.8.22.0e4a742
* 

*  具体描述(如复现BUG所需要的前提和必要操作等)
自4月20号每天都被冻结持续了半个月，到9月30都没再冻结过
10月1号早上1点更新0.8.22.0e4a742，4点就被冻结
10月2号早上0点注册新号，没20分钟又被冻结

*

**Comment by youling257** [comment]
半年前解冻时不需要绑定手机号接收验证码，直接填真实姓名和身份证，然后面部识别就能解冻
半年解冻流程还要验证码，我特么绑定手机号是10年前的，早不用了，
添写资料验证又不足以证明是主人，解冻两条路都堵死了
就在这儿抱怨下十年的qq号报废了

**Comment by singleNeuron** [comment]
@youling257 论及时更新手机号的重要性，不然你可能因为各种原因报废掉你的号。
