### ISSUE TITLE
[QQ 8.8.33] 部分群消息无法刷新

### ISSUE THREAD

**Issue by yeahjack** [ferredoxin/QNotified#1088]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.33

**模块版本/Module Version**

* 0.8.22.ef219e7

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.6.0

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

部分群仅能在主界面看到最新消息，打开后消息滞后，很多消息无法刷新

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

目前不知道如何导出日志...如果告诉我我非常乐意配合导出

**Comment by yeahjack** [comment]
你好，复现确实很困难，因为我只有一个群有这样的问题。
关于是否为QN模块造成，我停止启用该模块后，该问题得到解决，因此应该是模块导致的问题。

**Comment by aliyuchang33** [comment]
我也有这个问题，我是用了冰箱所以有很多在冻结期间没有被收到的消息，上滑时会显示无法获取。同样关闭qn后解决。请问有没有获取日志的方法？没有找到导出日志的选项。
