### ISSUE TITLE
[功能需求] 替换QQ语音功能

### ISSUE THREAD

**Issue by kongxia535** [ferredoxin/QNotified#1089]
**QQ(TIM)版本/QQ(TIM) Version**
8.6.0+
* 

**为什么你认为需要此功能**
通过此功能快捷替换语音，能和群友互动（装b）
发音乐（和前辈的呐喊）
* 

**联系到哪些已经存在的bug或者功能**
语音功能
* 

**具体功能需要/Specific features required**
自定义语音

*  具体描述(如使用的场景，面临的问题)
在和群友聊天的场景，只能发送1 MB以下的文件

**Comment by singleNeuron** [comment]
@kongxia535 你把麦克风凑另一个手机扬声器上不就行了

**Comment by kongxia535** [comment]
@singleNeuron 这样有杂音，我指的方式是选择文件然后直接替换语音文件发送

**Comment by cmxc123** [comment]
可以用MT管理器替换

**Comment by SchumKuangyu** [comment]
这样都和变声器功能一样了哈哈哈
