### ISSUE TITLE
[QQ V8.8.23.610]显示发信者QQ号功能异常显示为80000000

### ISSUE THREAD

**Issue by salt-ish** [ferredoxin/QNotified#1093]
**QQ(TIM)版本/QQ(TIM) Version**
QQV8.8.23.6010
* 

**模块版本/Module Version**
0.8.22.e02e0e2
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极 含光·8.0.3.06211300-6647
* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

我注意到在几个月前的QQ版本中，还可以通过QN的显示发信者QQ号功能显示匿名消息的QQ号，但是最近不知道是否为QQ版本更新导致，所有匿名消息QQ号显示为80000000。复现起来不需要特殊操作，另外我的操作环境是鸿蒙2.0.0.168(C00E 160R5P5)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@salt-ish 我就没见过任何方法可以显示匿名消息的发送者的，不管是任何Xposed还是抓包还是什么其他玩意。如果发送者是自己那你当我没说。
