### ISSUE TITLE
[QQ 8.8.35] Bug收集

### ISSUE THREAD

**Issue by NextAlone** [ferredoxin/QNotified#1103]
# 修复进度

- [x] 清理最近消息 #1104 
- [x] 回赞界面一键20赞 #1105

**Comment by marvin4work** [comment]
每次打开QQ时都会初始化一次，显示com.tencent.mobileqq.utils.VipUtils
QQ版本8.8.38
QN 版本是最新的

**Comment by keta1** [comment]
@marvin4work 坏，等会我看看

**Comment by NextAlone** [comment]
> @marvin4work 坏，等会我看看

#1116

**Comment by singleNeuron** [comment]
@github-actions[bot] 关你妈呢
