### ISSUE TITLE
[功能需求] 对列出的精简项设置文本溢出显示(Text-Overflow)

### ISSUE THREAD

**Issue by Xnor-bear** [ferredoxin/QNotified#1117]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.38(QNotified 0.8.23.95f8b00)

**为什么你认为需要此功能**

* 美观，符合正常使用逻辑。

**联系到哪些已经存在的bug或者功能**

* 
![image](https://user-images.githubusercontent.com/54651817/139725034-374a4356-2177-406d-8837-bcee58651dd8.png)

**具体功能需要/Specific features required**

*  右端已精简项目设置文本溢出显示，效果参考下图。

![image](https://user-images.githubusercontent.com/54651817/139725841-37e6b105-540c-4062-beeb-86f1fc7045c4.png)

**Comment by NextAlone** [comment]
@Xnor-bear 了解

**Comment by NextAlone** [comment]
直接改成启用数量了
