### ISSUE TITLE
[功能需求] 隐藏群助手

### ISSUE THREAD

**Issue by hechou** [ferredoxin/QNotified#1129]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ

**为什么你认为需要此功能**

* 界面简洁

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by taycke** [comment]
@hechou 他不就是个消息框？
