### ISSUE TITLE
[8.8.38] 设置屏蔽消息类型后无法使用

### ISSUE THREAD

**Issue by lang51** [ferredoxin/QNotified#1130]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.38

**模块版本/Module Version**

* 0.8.23.24e9e6b

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极阴8.0.6

**问题的具体描述/Detailed Description of the Bug**

*  屏蔽指定消息类型，勾选有红包，重启QQ，无法进入qnotified设置界面，并显示
![Screenshot_20211109_204944_com tencent mobileqq](https://user-images.githubusercontent.com/93988941/140929135-0bbe671c-be91-4b8a-a13a-896f834aad9e.png)

**此处贴你获取到的日志信息/Log here**

不知道在哪儿看，qn的数据目录好像要root才能看

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@NextAlone 看起来像是你的屎山炸了

**Comment by NextAlone** [comment]
我看下

**Comment by NextAlone** [comment]
装最新版试试

**Comment by lang51** [comment]
> 装最新版试试

是把QQ搞坏了需要重装QQ吗？我之前试过重装最新qnotified、升级QQ都不行，但是因为想保留聊天记录不想重装QQ。。

**Comment by NextAlone** [comment]
@lang51 最新qn

**Comment by lang51** [comment]
> @lang51 最新qn

就是最新的d0ddfa8

**Comment by NextAlone** [comment]
@lang51 从qn里进故障排查，清除一下模块数据，重新设置吧

**Comment by lang51** [comment]
> @lang51 从qn里进故障排查，清除一下模块数据，重新设置吧

解决了，感谢
但是无法复现，先关了
