### ISSUE TITLE
[8.8.33(2150)] 闪照无法以图片打开

### ISSUE THREAD

**Issue by blmulang** [ferredoxin/QNotified#1139]
**QQ(TIM)版本/QQ(TIM) Version**

* **QQ8.8.33**(2150)

**模块版本/Module Version**

* **0.8.23.29aa17d**

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* **应用转生**

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
**无法以图片打开闪照，一直在转**

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（不知道日志在哪😂）

</code></pre></details>

**Comment by cyf332211** [comment]
企鹅对图片进行加密了，用文档打开加密的图片文件开头一行就是encrypt，我退回老版本了
