### ISSUE TITLE
小程序转链接分享(接收)自动关闭

### ISSUE THREAD

**Issue by cangming99** [ferredoxin/QNotified#1147]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.50

**模块版本/Module Version**

* 0.8.23.90502a5

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed1.6.3(6228)

**问题的具体描述/Detailed Description of the Bug**

*  重开QQ之后，小程序转链接分享(接收)会被自动关闭

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（不知道日志在哪）

</code></pre></details>

**Comment by singleNeuron** [comment]
分给我干啥...必然是UI或者配置存储出了问题....

**Comment by singleNeuron** [comment]
完蛋了，全坏掉了，签到文本化都会自动关掉惹

**Comment by singleNeuron** [comment]
![image](https://user-images.githubusercontent.com/23723294/142650082-805a1b35-2fe9-49f0-8b99-64d5b9b48dd1.png)
![image](https://user-images.githubusercontent.com/23723294/142650093-054c665d-e17b-407b-aaf0-048737afbb4d.png)
MMKV的问题，原因未知
