### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Hans155922** [ferredoxin/QNotified#1162]
Could not determine the dependencies of task ':app:externalNativeBuildDebug'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :FerredoxinUILib.
     Required by:
         project :app
      > No matching configuration of project :FerredoxinUILib was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by singleNeuron** [comment]
https://git-scm.com/docs/git-submodule

**Comment by singleNeuron** [comment]
什么弱智机器人

**Comment by keta1** [comment]
> Could not determine the dependencies of task ':app:externalNativeBuildDebug'.
> 
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
> > Could not resolve project :FerredoxinUILib.
> > Required by:
> > project :app
> > > No matching configuration of project :FerredoxinUILib was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
> > - None of the consumable configurations have attributes.
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.



> https://git-scm.com/docs/git-submodule
> 
> 请自行了解git submodule，并确保所有submodule初始化完成后再编译

开了又关，骚扰我呢？

**Comment by singleNeuron** [comment]
> > Could not determine the dependencies of task ':app:externalNativeBuildDebug'.
> > > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
> > > Could not resolve project :FerredoxinUILib.
> > > Required by:
> > > project :app
> > > > No matching configuration of project :FerredoxinUILib was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
> > > 
> > > 
> > > 
> > > * None of the consumable configurations have attributes.
> > 
> > 
> > 
> > * Try:
> > 
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> 
> > https://git-scm.com/docs/git-submodule
> > 请自行了解git submodule，并确保所有submodule初始化完成后再编译
> 
> 开了又关，骚扰我呢？

机器人关的又不是我关的，你骂 @qwq233 去

**Comment by Hans155922** [comment]
> https://git-scm.com/docs/git-submodule
> 
> 请自行了解git submodule，并确保所有子模块初始化完成后再编译请自己学习git submodule，并在所有子模块初始化后构建。

谢谢大佬指教，第一次玩安卓

**Comment by qwq233** [comment]
> 什么弱智机器人

没走模板被close不挺正常的吗 本来就是设计成这样的

**Comment by qwq233** [comment]
> 什么弱智机器人

没走模板被close不挺正常的吗 本来就是设计成这样的

**Comment by keta1** [comment]
> > 什么弱智机器人
> 
> 没走模板被close不挺正常的吗 本来就是设计成这样的

我在意的地方是close了也能发炎
为啥要reopen

**Comment by singleNeuron** [comment]
@qwq233 人把问题描述清楚了，好好解释一下就行了，为啥要close

**Comment by Hans155922** [comment]
> 

编译报错和模块版本 QQ版本没关系，模板没法填啊

**Comment by Hans155922** [comment]
> @qwq233 人把问题描述清楚了，好好解释一下就行了，为啥要close

编译报错和模块版本 QQ版本没关系，模板没法填啊

**Comment by qwq233** [comment]
> @qwq233 人把问题描述清楚了，好好解释一下就行了，为啥要close

机器人能理解到这种程度早智械危机了
