### ISSUE TITLE
[功能需求] 写个自动往Xposed-Modules-Repo/nil.nadph.qnotified push的CI，并且用Azure Pipeline接管那边的发布

### ISSUE THREAD

**Issue by singleNeuron** [ferredoxin/QNotified#1164]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

@qwq233

**Comment by keta1** [comment]
还要清空下lsp那边的release

**Comment by singleNeuron** [comment]
> “阿卡斯拉，我已被净化了。”
“玛布拉，布拉霍林，玛布拉……”
“夏夫，达夫，麻籽，麻夫。
菲斯塔，维斯塔，米斯塔－卡夫。”
“利玛查德，雷蒙，利玛查德”
左侧，“恐虐！”，下方，“色孽！”，上方，“纳垢！”，然后，右边，“奸奇！”
“黑暗尽处的黑暗，比最深的漆黑还黑。
埋葬在时间的洪流之下……
从黑暗到黑暗，你的声音在虚空中回荡，
未曾一次败退，未曾被人理解。”
“你知道那道门，身为那道门，是那道门的守卫和钥匙：
我命你为他打开通道，让他的力量呈现在我面前！”
@qwq233 @qwq233 @qwq233 
___

**Comment by singleNeuron** [comment]
@singleNeuron

**Comment by singleNeuron** [comment]
![image](https://user-images.githubusercontent.com/23723294/143411346-08525ea7-02da-4582-a156-62ddf3a72f78.png)

**Comment by qwq233** [comment]
干脆让github接管所有玩意得了 我看了下github也能传channel或者appcenter这些玩意 webhook也可以
你们觉得可以的话我回家处理

**Comment by NextAlone** [comment]
@qwq233 好耶

**Comment by qwq233** [comment]
> 还要清空下lsp那边的release

这个否决 lsp那边是看release确定版本这些乱七八糟的玩意的 而且堆积太多了好麻烦orz

**Comment by keta1** [comment]
> > 还要清空下lsp那边的release
> 
> 这个否决 lsp那边是看release确定版本这些乱七八糟的玩意的 而且堆积太多了好麻烦orz

lsp最多只会显示20个release

**Comment by keta1** [comment]
> 干脆让github接管所有玩意得了 我看了下github也能传channel或者appcenter这些玩意 webhook也可以 你们觉得可以的话我回家处理

你不会是请假吧

**Comment by singleNeuron** [comment]
@qwq233 我们当时没用github用了azure的原因是azure每月上限更高

**Comment by qwq233** [comment]
> > 干脆让github接管所有玩意得了 我看了下github也能传channel或者appcenter这些玩意 webhook也可以 你们觉得可以的话我回家处理
> 
> 你不会是请假吧

没 等周六放学

>>> 还要清空下lsp那边的release

>> 这个否决 lsp那边是看release确定版本这些乱七八糟的玩意的 而且堆积太多了好麻烦orz

> lsp最多只会显示20个release

这就不关我事了 主要是麻烦 现在大概100+release 人工太麻烦

**Comment by qwq233** [comment]
> @qwq233 我们当时没用github用了azure的原因是azure每月上限更高

够用即可啦 5k min对我们是够用的反正
