### ISSUE TITLE
[8.8.50] 打开资料卡功能打开不了任何群的资料卡

### ISSUE THREAD

**Issue by Gipn0za** [ferredoxin/QNotified#1168]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.50

**模块版本/Module Version**

* 0.8.24.1d52d54

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsposed 1.6.3

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

输入群号点打开群

**Comment by singleNeuron** [comment]
@Gipn0za 已知问题，低版本可以，高版本失效

**Comment by bearcloney** [comment]
> @Gipn0za 已知问题，低版本可以，高版本失效
本人设备安卓11，QQ  8.2.11，无法使用
低版本是什么版本（qq好像7.x都禁止登陆提示跟新新版本了）
跟安装版本应该也没什么问题（未求证

**Comment by singleNeuron** [comment]
@bearcloney 835是没问题的

**Comment by bearcloney** [comment]
> @bearcloney 835是没问题的

跟安卓版本有关系吗
，你的是安卓几

**Comment by singleNeuron** [comment]
@bearcloney 确定和安卓版本无关

**Comment by bearcloney** [comment]
> @bearcloney确定和安卓版本视频

经过重装以及更新框架，现以解决问题，谢谢大佬热心回复

**Comment by singleNeuron** [comment]
@bearcloney ？你咋解决的，教教我
