### ISSUE TITLE
[功能需求] 希望增加保存图片重定向的功能

### ISSUE THREAD

**Issue by sunbohuashishabi** [ferredoxin/QNotified#1169]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.50
* 

**为什么你认为需要此功能**
qq保存的图片在相册里面看不到（类原生系统）
* 

**联系到哪些已经存在的bug或者功能**
无
* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
将保存的图片重定向到/0/Pictures/QQ

**Comment by singleNeuron** [comment]
@sunbohuashishabi 请合理使用存储重定向的硬链接功能
