### ISSUE TITLE
[QQ 8.8.50] 万象屏蔽卡片消息功能无法保存

### ISSUE THREAD

**Issue by Decwar** [ferredoxin/QNotified#1173]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.50(2324)

**模块版本/Module Version**

* 0.8.24.1d52d54

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.6.2(6152)

**问题的具体描述/Detailed Description of the Bug**

*  在万象屏蔽卡片消息输入并按确定后，重新进入该设置显示空白，外面菜单也没有显示输入的信息，不清楚是否保存成功。并且想询问下该设置是否能对普通消息生效，若不能是否能添加普通消息正则屏蔽功能

**Comment by singleNeuron** [comment]
@Decwar 普通消息不生效

**Comment by Decwar** [comment]
> @Decwar 普通消息不生效

我发现是输入太长的话菜单里就不会显示，但输入短的虽然是显示了，重启QQ后就会变成null。还有这个正则编写两端是否要加上/

**Comment by singleNeuron** [comment]
@github-actions[bot] 现在还能保存吗
