### ISSUE TITLE
[Bug]QQ8.4.1 复读功能不正常

### ISSUE THREAD

**Issue by yblpoi** [ferredoxin/QNotified#118]
在最新版本的QQ中，复读功能无法在句子后出现+1，但是在图片后的+1没有影响。
系统版本：MIUI12国际版
手机：红米note8p
QQ版本：8.4.1.4680
![Screenshot_2020-07-27-10-25-46-067_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/66136793/88497686-ad512400-cff3-11ea-9bcd-80c0d9b3da8d.jpg)

**Comment by NextAlone** [comment]
现在还有问题吗
