### ISSUE TITLE
[长期]Play版QQ BUG收集

### ISSUE THREAD

**Issue by qwq233** [ferredoxin/QNotified#1184]
此处长期性收集Play版QQ的BUG 如发现BUG请Comment
修复了会把commnet hide/delete

**Comment by YSHcc01** [comment]
MIUI 12.5 开发版21.11.3最新版QN与最新版QQ打架，QQ会闪退

**Comment by 358624893588935** [comment]
安卓11，QQ8.2.11，最新版QN精简更改底栏无变化

**Comment by rinscr3003** [comment]
最新版QQ和最新版qn不兼容，QQ打开后立即闪退

**Comment by JniTaim** [comment]
移除群聊一起嗨
修改@界面排序
小程序转链接分享 接收（例如腾讯文档）

**Comment by mytsrgit** [comment]
![Screenshot_20220326125626](https://user-images.githubusercontent.com/93456238/160225326-ad3baa43-ea0d-42bf-a52c-1977e80719f4.jpg)
打开这个再关闭必闪退

**Comment by mytsrgit** [comment]
@全体成员 通知无法屏蔽

**Comment by reserveword** [comment]
去你大爷的QQ浏览器会导致所有链接无法打开
play版8.2.11，magisk/riru/lsposed，装了去你大爷的内置浏览器，但是没打开QQ的规则
