### ISSUE TITLE
[功能需求] 扩展自动续火范围至群聊天可用

### ISSUE THREAD

**Issue by asoulist** [ferredoxin/QNotified#1187]
**QQ(TIM)版本/QQ(TIM) Version**

* 原Play转国内版QQ 8.8.50.6735

**为什么你认为需要此功能**

* 有若干私密福利群开启了严格的打卡模式，只限给保持活跃（至少7天火苗）的成员私聊发放资源压缩包

**联系到哪些已经存在的bug或者功能**

* [Omega测试]->[特供版]自动续火

**具体功能需要/Specific features required**

*  扩展原有的自动续火功能至群聊可用，可在群资料界面添加一个开关，使用和好友续火类似的设置方式，每日固定时间在群内发送一条消息，或者发送打卡消息，从而保持群内活跃记录

**Comment by NextAlone** [comment]
@asoulist 想看资源还这么懒

**Comment by singleNeuron** [comment]
@asoulist 想看资源还这么懒

另外，请把我们拉入群以方便测试
