### ISSUE TITLE
[8.8.50] 设置中没有防撤回和以图片方式打开闪照

### ISSUE THREAD

**Issue by Fros1er** [ferredoxin/QNotified#1190]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.50(2324)

**模块版本/Module Version**

* 0.8.24.1d52d54

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.6.5(6272)，magisk23.0，riru23.1.3，小米10，miui12.5.10稳定版

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

安装后设置页面中没有和防撤回和闪照有关的设置（仅有“频道功能”中的防撤回，已开启），在确定收到消息的情况下防撤回和以图片方式打开闪照也没有工作。

**此处贴你获取到的日志信息/Log here**

没有找到获取日志的方式。。只能贴个反混淆信息了

<details><summary>展开查看</summary><pre><code>

![Screenshot_2021-12-16-11-22-41-719_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302663-fc4b0307-131a-4a62-bb90-825d3dc0d291.jpg)
![Screenshot_2021-12-16-11-22-46-124_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302671-dd02dcbc-ef3e-4f13-96b0-7dd3b583efd1.jpg)
![Screenshot_2021-12-16-11-22-52-998_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302674-a5e9d391-4e83-4f1b-960e-065956be0cf5.jpg)
![Screenshot_2021-12-16-11-22-57-337_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302676-a30ee53f-e92d-4876-bc5b-abc52e27c678.jpg)
![Screenshot_2021-12-16-11-23-01-914_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302678-96ac42d4-940e-477b-94fc-84ffa25848d7.jpg)
![Screenshot_2021-12-16-11-23-07-474_com tencent mobileqq](https://user-images.githubusercontent.com/34234343/146302682-78c6209c-5ca9-48d9-a679-5ddd0b25e161.jpg)

</code></pre></details>

**Comment by keta1** [comment]
在QQ进化里

**Comment by singleNeuron** [comment]
@keta1 在QQ净化[WIP]里

**Comment by Fros1er** [comment]
> @keta1 在QQ净化[WIP]里



> 在QQ进化里

谢谢。。。刚开始用，还不太熟悉。麻烦了。
