### ISSUE TITLE
[8.8.50] 安卓12 无法使用QN 打开QQ后崩溃

### ISSUE THREAD

**Issue by jiajiaxd** [ferredoxin/QNotified#1201]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.50
* 

**模块版本/Module Version**
0.9.0.b928ab7 (1640438662)
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
LSPosed 1.6.5
* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
系统升级至安卓12后 无法使用QN 打开QQ直接崩溃

**Comment by qwq233** [comment]
重启过？

**Comment by jiajiaxd** [comment]
经检查是其它Xposed模块导致，抱歉打扰了！

**Comment by jiajiaxd** [comment]
我回来了，经过测试，发现
安装QN后如果不重启手机，QQ就不会崩溃。
重启了手机后，打开QQ就崩。关闭QN后仍然崩溃，清除数据没有用，必须要重新安装。
