### ISSUE TITLE
[功能需求] 简洁模式方头像,QQ更新以后简洁模式没有正方形头像

### ISSUE THREAD

**Issue by huangg233** [ferredoxin/QNotified#1211]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.50

**为什么你认为需要此功能**

* 老版本QQ简洁模式以前是方的,希望在有生之年能有个设置回正方形头像的功能

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by singleNeuron** [comment]
@huangg233 写完简洁模式圆头像再写简洁模式方头像是吧…

**Comment by huangg233** [comment]
> @huangg233 写完简洁模式圆头像再写简洁模式方头像是吧…

😂不懂,以前一直用的方头,鬼知道傻逼QQ怎么想的

**Comment by qwq233** [comment]
用老版本 请

**Comment by qwq233** [comment]
#969 Duplicate
