### ISSUE TITLE
[8.8.50] Google Play版本的QNotified无法使用

### ISSUE THREAD

**Issue by xyf2018** [ferredoxin/QNotified#1212]
**QQ(TIM)版本/QQ(TIM) Version**

8.8.50

**模块版本/Module Version**

1.0.0.d4f980f 
Google Play版

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

LSPosed 1.6.5

**问题的具体描述/Detailed Description of the Bug**

1.Google Play商店里最新版的QNotified 1.0.0.d4f980f不能正常使用。具体表现为QQ启动时没有QN的加载过程，QQ的设置里也没有QN，就好像根本没有安装和启用QN一样，但再三确认过是正常启用了的。
2.安装QNotified电报频道中提供的相同版本QN，可以正常使用。

**Comment by qwq233** [comment]
> 安装QNotified电报频道中提供的相同版本QN，可以正常使用。
你没杀应用重启qq的问题
