### ISSUE TITLE
使用qn模块导致账号频繁被封禁

### ISSUE THREAD

**Issue by kusadact** [ferredoxin/QNotified#1213]
**QQ(TIM)版本/QQ(TIM) Version**

* qq 8.8.50.6735和qq8.8.5.5

**模块版本/Module Version**

* 0.8.24.1d52d54

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Xposed 89版

**问题的具体描述/Detailed Description of the Bug**

*  在我的小米MAX（3+32g android7）手机在qq8850和8855版本使用qn时账号频繁被封禁，每次都是半夜被封(三点零几和四点零几居多)。qq给出的理由是使用第三方qq，此封号可以立即解冻。
* 尝试过只打开qn而不加任何修改，也会被封号

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

01-02 13:33:53.700 I/Xposed  (  559): -----------------
01-02 13:33:53.700 I/Xposed  (  559): Starting Xposed version 89, compiled for SDK 24
01-02 13:33:53.700 I/Xposed  (  559): Device: MI MAX (Xiaomi), Android version 7.0 (SDK 24)
01-02 13:33:53.700 I/Xposed  (  559): ROM: NRD90M
01-02 13:33:53.700 I/Xposed  (  559): Build fingerprint: Xiaomi/hydrogen/hydrogen:7.0/NRD90M/V10.3.2.0.NBCCNXM:user/release-keys
01-02 13:33:53.700 I/Xposed  (  559): Platform: arm64-v8a, 64-bit binary, system server: yes
01-02 13:33:53.700 I/Xposed  (  559): SELinux enabled: yes, enforcing: yes
01-02 13:33:54.765 I/Xposed  (  559): -----------------
01-02 13:33:54.765 I/Xposed  (  559): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-02 13:33:57.157 I/Xposed  (  559): Detected ART runtime
01-02 13:33:57.173 I/Xposed  (  559): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-02 13:33:57.503 I/Xposed  (  559): Loading modules from /data/app/com.xposed.miuianesth

</code></pre></details>

**Comment by qwq233** [comment]
https://t.me/QNotified/907
https://t.me/QNotified/910
