### ISSUE TITLE
[功能需求] 破解群禁言

### ISSUE THREAD

**Issue by mayalso** [ferredoxin/QNotified#1214]
**QQ(TIM)版本/QQ(TIM) Version**

* 版本都行

**为什么你认为需要此功能**

* 被恶意禁言恶心

**联系到哪些已经存在的bug或者功能**

* 
**具体功能需要/Specific features required**
能直接正常发言就行
*  具体描述(如使用的场景，面临的问题)

**Comment by singleNeuron** [comment]
不可能的事，别想了
