### ISSUE TITLE
[QQ8.8.50] 更新1.0以后闪退

### ISSUE THREAD

**Issue by Diolance** [ferredoxin/QNotified#1218]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.50

**模块版本/Module Version**

* 1.0.0系列

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.6.5

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

安装1.0版模块后，重启启用模块，只要打开QQ，约6-7秒就会闪退，更新7号新版本后依旧存在问题，因为闪退太快也不知道怎么获取日志

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）
![Screenshot_2022-01-08-12-17-13-725_bin mt plus](https://user-images.githubusercontent.com/97007874/148631118-8d6bf470-e7f0-4692-ab69-ea63c8924061.jpg)
![Screenshot_2022-01-08-12-17-21-850_bin mt plus](https://user-images.githubusercontent.com/97007874/148631129-f98002b0-2b27-45ff-95ac-f9a49f53037a.jpg)
![Screenshot_2022-01-08-12-17-27-222_bin mt plus](https://user-images.githubusercontent.com/97007874/148631137-bd453c89-704e-46d7-b702-c01c98c074f0.jpg)
![Screenshot_2022-01-08-12-17-32-038_bin mt plus](https://user-images.githubusercontent.com/97007874/148631142-cd691f67-65a4-4b39-84a7-da53983ec05b.jpg)
![Screenshot_2022-01-08-12-17-36-015_bin mt plus](https://user-images.githubusercontent.com/97007874/148631149-890cd8e3-982d-49e9-b57b-01a8dfe5e40c.jpg)
![Screenshot_2022-01-08-12-17-39-883_bin mt plus](https://user-images.githubusercontent.com/97007874/148631154-c2e9afe5-ad96-4595-82f3-3a6397d07863.jpg)
复制日志出了些问题，就只能截图了，望见谅
</code></pre></details>

**Comment by keta1** [comment]
@Diolance 去lsposed里看日志

**Comment by Diolance** [comment]
> 

谢谢，已经重新传了日志

**Comment by turthy** [comment]
TIM也有过几秒就强制闪退的情况，大概是不论版本的，tim旧版本也会闪退（）关闭模块就不闪退了

**Comment by turthy** [comment]
嗯，另外qq旧版本不会闪退，用着很好

**Comment by keta1** [comment]
> > 
> 
> 谢谢，已经重新传了日志 @keta1

你不能发文件吗？粘贴也行

**Comment by Diolance** [comment]
> > > 
> > 
> > 
> > 谢谢，已经重新传了日志 @keta1
> 
> 你不能发文件吗？粘贴也行
第一次发帖，不太清楚该怎么上传文件，找了一阵没找到(´╥ω╥`)。从MT里复制粘贴一直有问题，只能几个几个词的复制

**Comment by Diolance** [comment]
> > > 
> > 
> > 
> > 谢谢，已经重新传了日志 @keta1
> 
> 你不能发文件吗？粘贴也行

我试着把文件传到了我主页里

**Comment by haiyan233** [comment]
> > > > 
> > > 
> > > 
> > > 谢谢，已经重新传了的日志@keta1
> > 
> > 
> > 你不能行发文件吗？
> 
> 我把文件传到了我的主页里

有解决办法了吗

**Comment by qwq233** [comment]
play下的qn吗

**Comment by rinscr3003** [comment]
@qwq233 我的是从github release和appcenter都下载试过，没有区别一样闪退

**Comment by rinscr3003** [comment]
@qwq233 更新至MIUI13的最新更新后正常。Mi11@MIUI13.0.5.0

**Comment by qwq233** [comment]
> @qwq233 更新至MIUI13的最新更新后正常。Mi11@MIUI13.0.5.0

@rinscr3003 说明是你的问题

fixed in #1232  (?)
