### ISSUE TITLE
[功能需求] 支持Android11 12的消息泡功能

### ISSUE THREAD

**Issue by NicoOrz** [ferredoxin/QNotified#1220]
**QQ(TIM)版本/QQ(TIM) Version**
8.5.0
* 

**为什么你认为需要此功能**
更贴合原生系统 方便快速回复
* 

**联系到哪些已经存在的bug或者功能**
无
* 

**具体功能需要/Specific features required**
在QQ收到消息时以消息泡的方式呈现
![Screenshot_20220112-182803](https://user-images.githubusercontent.com/36440594/149125305-c76dfe78-cfe9-442a-bfec-5277880a4405.png)

*  具体描述(如使用的场景，面临的问题)

**Comment by keta1** [comment]
已经有了，需要安卓12才行
11没法支持
