### ISSUE TITLE
[QQ8.8.55]进入qq就闪退问题

### ISSUE THREAD

**Issue by haiyan233** [ferredoxin/QNotified#1221]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.55

**模块版本/Module Version**

* 最新版

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed最新版

**问题的具体描述/Detailed Description of the Bug**

*  打开模块2-10秒之内就闪退，关上模块就没事，绝对是模块的bug，更新了8.8.55就这样了，上个版本还没事

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

日志没获取到，不过也有个用户反馈了，这两个bug应该是一样的，希望大大能赶快修复

</code></pre></details>

**Comment by qwq233** [comment]
#1218
