### ISSUE TITLE
私聊窗口发送出去的消息显示对方已读或未读

### ISSUE THREAD

**Issue by Bcake123** [ferredoxin/QNotified#1229]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**
很多时候都在等对方回复，但又不知道对方是读了不想回复还是没读 所以我认为需要这项功能
* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by NextAlone** [comment]
@Bcake123 服务器无此项数据，无法实现

**Comment by Cryolitia** [comment]
这个功能首先需要腾讯的服务器向客户端发送对方已读这个数据，已读回执这个功能应该去找腾讯要而不是找我们
