### ISSUE TITLE
I want join in your group to develop the plugin together but how I contact you bro

### ISSUE THREAD

**Issue by codmakerxjl** [ferredoxin/QNotified#1231]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by Cryolitia** [comment]
@codmakerxjl Can you speak Chinese?
Koennen Sie Chinese sprechen?
あなたは中国語を話せますか?

**Comment by codmakerxjl** [comment]
嗯，刚刚用的模拟器，没安装中文输入，现在用的电脑。  
我可以加入你们一起开发吗

**Comment by Cryolitia** [comment]
@codmakerxjl 你使用Telegram吗

**Comment by codmakerxjl** [comment]
没有，需要使用telegram吗，我现在就可以去下载

**Comment by Cryolitia** [comment]
@codmakerxjl 是的，请

**Comment by codmakerxjl** [comment]
我已经下载完了

**Comment by codmakerxjl** [comment]
怎么联系你

**Comment by Cryolitia** [comment]
@codmakerxjl 给我你的telegrm账号

**Comment by codmakerxjl** [comment]
codemakerx

**Comment by codmakerxjl** [comment]
你能搜索到吗
