### ISSUE TITLE
[8.8.50] 收到更新提醒

### ISSUE THREAD

**Issue by waveyl** [ferredoxin/QNotified#1242]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.50.6735

**模块版本/Module Version**

* 1.0.0.479023d

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极阴8.0.6

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
![Screenshot_20220124_183045_com tencent mobileqq](https://user-images.githubusercontent.com/22638873/150767541-959c40d3-ff8e-4001-9bbc-3706d5ec0316.png)

![Screenshot_20220124_183052_com tencent mobileqq](https://user-images.githubusercontent.com/22638873/150767554-f5dc8232-4552-4992-ad96-1fe78aa525c6.png)

**Comment by edison0354** [comment]
我也收到了，不过找了半天也没找到哪里有禁止更新的功能，所以这模块真的能禁止检测更新么…

**Comment by keta1** [comment]
> 我也收到了，不过找了半天也没找到哪里有禁止更新的功能，所以这模块真的能禁止检测更新么…

很久没修了 大抵是坏了
