### ISSUE TITLE
[功能需求] 直接在 QQ 打开被拦截的网站

### ISSUE THREAD

**Issue by V-arc** [ferredoxin/QNotified#1243]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.33.6300

**为什么你认为需要此功能**

* 我不需要 QQ 为我拦截某些所谓的“恶意”网站，让我必须回到我的浏览器访问一个简单的页面。

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
今天在 QQ 打开网站 [billie66/TLCL：《快乐的 Linux 命令行》](http://billie66.github.io/TLCL/)  ，提示如下：
当前网页非官方页面
http://billie66.github.io/TLCL/
非官方页面，请勿输入QQ账号和密码，如需访问，请复制后使用浏览器访问
我不希望 QQ 对我所访问的网站进行限制。

**Comment by qwq233** [comment]
去用*去他妈的内置浏览器*
