### ISSUE TITLE
[QQ8.8.68] 打开模块设置闪退

### ISSUE THREAD

**Issue by duobuhui** [ferredoxin/QNotified#1248]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.68

**模块版本/Module Version**

*1.0.0d4f980f 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极 6.3.0-6992

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

打开模块设置时闪退 “太极已阻止qq闪退” 使用故障排查**清除缓存**和**重置模块设置**后依旧出现

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
日志

**Comment by duobuhui** [comment]
我目前只能打开模块的故障排查页面，我并不能找到抓取日志的功能入口
目前只有一张太极的报错信息：![screenshot](https://631266.freep.cn/631266/Screenshot_20220126_182634_com.tencent.mobileqq.jpg)

**Comment by cinit** [comment]
请更新 CI 最新版, 这个问题已经在新版本中修复

**Comment by RSNongyao** [comment]
请问CI怎么更新 我也有同样的问题不知道咋更新

**Comment by NextAlone** [comment]
> 请问CI怎么更新 我也有同样的问题不知道咋更新

https://t.me/QNotified_CI
