### ISSUE TITLE
QQLite深色/夜间模式

### ISSUE THREAD

**Issue by ReAtopos** [ferredoxin/QNotified#1256]
**QQ(TIM)版本/QQ(TIM) Version**

* QQlite

**为什么你认为需要此功能**

* 因为lite版并没有这个功能，但是lite版本十分简介流畅

**联系到哪些已经存在的bug或者功能**

* 夜间/深色模式

**具体功能需要/Specific features required**

*  夜间模式相比纯白更加护眼，很多人包括我也已经习惯了一直使用夜间模式

**Comment by Cryolitia** [comment]
找 @Lagrio 或者ColorQQ要QQLite的主题去，别找我们

**Comment by Lagrio** [comment]
> 
？别找我

**Comment by Lagrio** [comment]
> 找 @Lagrio 或者ColorQQ要QQLite的主题去，别找我们

？别找我

**Comment by ReAtopos** [comment]
对不起，我不太清楚，抱歉
请问去哪里下载colorQQ呢 我gitbug上搜colorQQ搜不到，就搜到了个colorQQ2

**Comment by Cryolitia** [comment]
@ReAtopos ColorQQ是付费软件，而且也不支持QQ Lite(我猜)，建议用大把的钱去砸作者让他给你写

**Comment by Cryolitia** [comment]
@ReAtopos 但是这个是目前离着你需求最近的了，我们根本没研究过主题这块

**Comment by ReAtopos** [comment]
好吧，谢谢你
