### ISSUE TITLE
[QQ8.1.0] qq提示版本过旧导致无法登录无法使用qn设置

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [ferredoxin/QNotified#1263]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.1.0

**模块版本/Module Version**

* 0.8.24

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSP-Zygisk

**问题的具体描述/Detailed Description of the Bug**

*  今天更新了一下模块的版本，然后就发现qq退出了要重新登。但是登录时qq提示版本过旧登不了...我记得qn里面好像有可以直接登录然后自己手动登的功能的，还有伪装版本号的...但是我无法登录qq就导致我无法打开qn的设置，就这样陷入了死循环
 看tg上面投票还是有人在使用较低版本的qq的（虽然不多），8.1.0是我可以找到的能登录的最早的版本了，我不喜欢qq添加的没啥用的新功能让它占的空间越来越大...所以我不想更新，希望问题可以解决，麻烦大佬辣~

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

emm...都打不开设置哪来的日志啊...

</code></pre></details>

**Comment by cinit** [comment]
可以从模块直接跳转到QQ内设置的
