### ISSUE TITLE
[8.8.11] 使用系统发送照片方式发送视频

### ISSUE THREAD

**Issue by LittleChest** [ferredoxin/QNotified#1265]
**QQ(TIM)版本/QQ(TIM) Version**

QQ 8.8.11

**模块版本/Module Version**

1.0.1.40e313e

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

LSPosed 1.7.1 (6358)

**问题的具体描述/Detailed Description of the Bug**

在QN设置中打开 可选使用系统相册
在任意聊天中点按右下角加号
点按 相册
试图发送视频

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

抓不到qwq

</code></pre></details>

**Comment by Cryolitia** [comment]
@LittleChest 用发送文件发视频

**Comment by LittleChest** [comment]
好吧
