### ISSUE TITLE
[QQ 8.8.68] 自定义QQ等级上限数字会导致QQ卡死

### ISSUE THREAD

**Issue by Loyolichoo** [ferredoxin/QNotified#1266]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.68

**模块版本/Module Version**

* 1.0.1.40e313e

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Magisk 24.1 
* Riru v26.1.4.r522.8b379cedb5 
* Riru - LSPosed v1.7.1（6358）

**问题的具体描述/Detailed Description of the Bug**

*  启用自定义QQ等级功能，设置QQ等级为 2147483647
* QQ首页左滑打开菜单页会完全卡死，停用模块、清除QQ/模块的dex和缓存，以及清空模块数据都不好使。预计只能清除QQ数据或手动删除该QQ号的数据。蹲一个不用清除数据的解决方案

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by Loyolichoo** [comment]
> qn有个故障排查 进去删掉模块数据

感谢指导，清除缓存跟重置数据不好使，应该是账号数据出现了损坏。
不过顺着这个思路从QN app页面趁QQ还没卡死的时候直接跳转到QN的设置界面然后修改本地QQ等级为1级解决了问题。

感觉自定义QQ等级的取值范围可以缩小一些，或者测试一下边界问题。

**Comment by lliioollcn** [comment]
已经在 #1268 对此添加了限制
