### ISSUE TITLE
[QQ8.8.50.6735] QQ设置内显示“未激活”

### ISSUE THREAD

**Issue by PRO-2684** [ferredoxin/QNotified#1269]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.50.6735

**模块版本/Module Version**

* 1.0.1.b04a665

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.7.2 (6379) - Zygisk

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

LSPosed内已启用模块，QNotified app里也显示已激活，但是QQ设置内显示的是“QNotified    [未激活]”，点进去标题栏显示“EULA”，界面全空白。从qn app内可正常打开qn设置，但是模块并不生效。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

貌似无错误输出

</code></pre></details>

**Comment by PRO-2684** [comment]
大草，原来是没有适配夜间模式，滚到最下面就可以同意协议了

**Comment by Cryolitia** [comment]
@PRO-2684 QQ自己有问题，夜间模式QQ自己的拒绝入群的消息都显示不出来，我们也没办法
