### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by TravinDreek** [ferredoxin/QNotified#1284]
本软件同时使用两个互不兼容的许可证, 存在根本性的条款冲突, 并且这种冲突无法通过使用一者覆盖另一者的方法解决. 详细分析见下.

从 README 中可以看出, 本软件同时使用 AGPLv3 和一份 EULA 发布, 并且试图通过声明 "本协议 (EULA) 与 AGPL 协议的冲突部分均按照本协议约束" 来使 EULA 覆盖于 AGPLv3 的部分条款之上. 这种覆盖是不能实现的, 因为在 AGPL 的第 7 节有如下规定:

>  If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.
> 如果你接收到的程序或其部分, 声称受本许可证约束, 却补充了进一步的限制条款, 那么你可以去掉它们.

同时, 在 AGPL 的第 10 节还有如下规定:

> If conditions are imposed on you (whether by court order, agreement or otherwise) that contradict the conditions of this License, they do not excuse you from the conditions of this License.
> 即便你面临与本许可证条款相冲突的条款 (无论来自于法庭要求, 协议还是其他地方), 你也不能以此为由违背本许可证的条款.

因此, 在受到这两个互不兼容的许可证的约束下, 此软件对用户的实际授权情况是这样的: 用户可以行使 AGPL 赋予用户的一切权利, 而不受 EULA 的约束, 因为用户可以去除任何限制性条款.

让我们假设, 如果 EULA 的条款真的有效地覆盖在了 AGPLv3 上, 会发生什么.

同样在第 10 节, AGPL 有如下规定:

> If you cannot convey a covered work so as to satisfy simultaneously your obligations under this License and any other pertinent obligations, then as a consequence you may not convey it at all.
> 如果你不能在输送该涵盖作品的同时满足来自本许可证的要求和其他相关的要求, 那么你就不能输送该涵盖作品.

由于 AGPL 和 EULA 有显然的冲突, 用户不能在同时满足它们的情况下输送本程序. 在这种情况下, 要同时遵守 AGPL 和 EULA, 那么用户唯一能做的就是不传播本软件. 也就是说, 只要 EULA 还生效, 那么本软件根本就不能被传播.

综上, 要解决这种许可证冲突, 唯一能做的就是去除 EULA 这种限制性条款, 只以 AGPL 发布本程序. 如果试图通过去除 AGPL 而保留 EULA 来解决此问题, 将导致此软件违背开源的定义, 而不能被称为 "开源软件" (如果你想进一步了解这一点, 请告诉我).

**Comment by qwq233** [comment]
agpl的意思是如果是非原始作者设置了什么附加条款可以无视 但是我们这显然是原始作者拥有著作权 著作权法显然高于协议这些 而著作权拥有者是有权利授予部分人或所有人部分权利并规定限制条款的 因此实际上是没有问题的

**Comment by qwq233** [comment]
@cinit 我没权限 你close吧

**Comment by qwq233** [comment]
关于开源

> 开源软件又称开放源代码软件，是一种源代码可以任意获取的计算机软件，这种软件的**著作权持有人在软件协议的规定之下保留一部分权利**并允许用户学习、修改以及以任何目的向任何人分发该软件。

来源维基百科

你应该指的是free software（即自由软件）这里也没说这是自由软件 将该项目称之为开源软件实际上是没有问题的

**Comment by qwq233** [comment]
综上所述 著作权法高于协议 而著作权所有者可以根据情况对人对协议进行调整且这种权利是高于协议的 有些时候你可以给一篇文稿以CC BY-NC-SA 4.0协议公开但是对于想商用的群体进行收费授权 详细见[中华人民共和国著作权法](http://www.npc.gov.cn/npc/c30834/202011/848e73f58d4e4c5b82f69d25d46048c6.shtml)或[数字千年版权法](https://zh.wikipedia.org/zh-hans/%E6%95%B8%E5%AD%97%E5%8D%83%E5%B9%B4%E7%89%88%E6%AC%8A%E6%B3%95)

**Comment by qwq233** [comment]
> @cinit 我没权限 你close吧

额 @Cryolitia

**Comment by TravinDreek** [comment]
在著作权与协议方面, 我理解你想表达的意思. 不管是在我国著作权法还是在 DMCA 中, 作者对其作品授权方式的选择都是自由的. 我也见过以某个许可证授权的作品的例外许可被合法出售至特定方的情况, 例如你所说的出售以 CC NC 系列许可证发布的作品的有关允许商用的行为.

但是, QNotified 许可情况的问题在于, 尽管其使用了两个许可证, 但它的发布不是一种双授权行为 (即两个许可证并非分别用于两种不同的发布方式); 这两个许可证都实际地作用在了同一种发布方式上. 在这种情况下, 即在具体的一种发布方式下, 对作品的授权条款应该是明确且不自相矛盾的. 然而, 本软件的实际情况是, AGPL 要求给予充足的许可并排斥限制性条款, 而 EULA 又需要增加限制性条款并覆盖 AGPL 的要求. 尽管 EULA 对 AGPL 的覆盖的有效性是更加可能被法律认可的, 但仅通过声明 "EULA 与 AGPL 冲突之处, 以 EULA 为准" 来构造的许可不能被视作是牢固的, 因为在这种跨协议的条款覆盖中, 对具体条款的具体条件的判定是复杂的, 这也正是我在原 issue 中说应该只是用一个许可证的原因.

(A)GPL 是一个成熟的许可证, 其条款与条件是明确且牢固的. QNotified 的 EULA 本身的条款与条件也是相对完整且可行的. 因此, 单独采用这两个许可证中的任意一个都是可行的. 实际上, 单独使用 EULA 授权就可以解决这种冲突.

正如我在原 issue 末尾所述, 我之所以说不应使用 EULA, 是因为它会导致本软件超出 "开源软件" 的定义, 即使它的 EULA 仍是生效的. 在这里, 你引用了 Wikipedia 上的 "开源软件" 定义, 但 "开源" 一词实际上是由 [OSI](https://opensource.org/) 定义的. OSI 是最先提出和定义 "开源" 这一概念的组织, 其对 "开源" 的定义也是目前人们判断某一软件是否为 "开源软件" 所参考的事实的标准.

阅读了 QNotified 的 EULA 之后, 我发现其中最值得注意的条款是关于禁止商业使用的条款. 就这一点, 如果我们再参看 OSI 对 "开源软件" 的[定义](https://opensource.org/osd), 就会发现这已经不符合它的第一点了. 另外, 在 OSI 的 FAQ 中, 关于 "开源软件" 商业使用的问题也被给出了明确的[回答](https://opensource.org/faq#commercial). 因此, 如果只参看 Wikipedia 模糊的定义, 将本软件称为 "开源软件" 看似没什么问题, 但它实际上已经超出了 "开源软件" 的确切定义.

最后, 你对自由软件 (free software) 也许还存在一些误解. 在你的回复中, 你提到了自由软件, 并认为自由软件和 "开源软件" 存在着较大的区别. 实际上, 这两个家族的分歧与分裂只是政治观点上的. 尽管自由软件和 "开源软件" 的定义, 在表述上有很大的区别, 但他们其实指的基本就是同一类事物, 这是 [FSF](https://www.gnu.org/philosophy/open-source-misses-the-point.html) 和 [OSI](https://opensource.org/faq#free-software) 都认同的. 就本软件而言, 如果它是 "开源软件", 那么它也是自由软件; 如果它不是 "开源软件" 那么它也不是自由软件. 本软件的目前的情况就是后者.

**Comment by TravinDreek** [comment]
@qwq233

**Comment by qwq233** [comment]
我采用双许可证的方式主要是我既想要agpl的特性也要自己附加条款 两个整合太麻烦了
关于开源软件 自由软件并不是开源软件 开源软件的范围显然较大 从广义的角度我认为将开源解释为开放源代码没有问题

你自己也提到
>  EULA 对 AGPL 的覆盖的有效性是更加可能被法律认可的
著作权拥有者大多数为中国公民，协议和著作权法与民法典没有较大冲突（其实AGPL还相对来说和著作权法有些小冲突 没有考虑到大陆法系的国家 主要是针对海洋法系国家也即英美考虑），本着能少事情就少事情的原则，我这边不予解决，

**Comment by TravinDreek** [comment]
看来 "开源" 一词的意思还是被过度延伸了. 既然不能在 EULA 上做出妥协, 我的建议还是, 如果可能的话, 还是尽量把所有条款整合到一个许可证中, 这样许可证才是更加清晰的.

**Comment by qwq233** [comment]
> 看来 "开源" 一词的意思还是被过度延伸了. 既然不能在 EULA 上做出妥协, 我的建议还是, 如果可能的话, 还是尽量把所有条款整合到一个许可证中, 这样许可证才是更加清晰的.

我的建议是 你来

**Comment by TravinDreek** [comment]
尽管我会审阅许可证, 我并不擅长写一份许可证. 不过, 我想对方也不想再费心在这些事上了. 这样的话, 大可忽略我的建议, 继续开发软件便可.
