### ISSUE TITLE
希望能够使用Magisk框架，我的手机不支持Xposed框架

### ISSUE THREAD

**Issue by NULL204** [ferredoxin/QNotified#1287]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by xiesihao** [comment]
lsposed啊。。。
magisk和Xposed的原理都不同，这个怎么可能用magisk模块实现呢。。。

**Comment by lliioollcn** [comment]
你可以使用lsposed的magisk模块来实现xposed
