### ISSUE TITLE
[功能需求] 长按+1修改信息

### ISSUE THREAD

**Issue by jiushu9** [ferredoxin/QNotified#1305]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.85

**为什么你认为需要此功能**

* 很有用

**联系到哪些已经存在的bug或者功能**

* no

**具体功能需要/Specific features required**
111
*  具体描述(如使用的场景，面临的问题)
修改信息，玩乐

**Comment by keta1** [comment]
never to do

**Comment by cinit** [comment]
@jiushu9 会被滥用，不予考虑
