### ISSUE TITLE
[功能需求] 超级表情去除帧数限制

### ISSUE THREAD

**Issue by Nevodev** [ferredoxin/QNotified#1307]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.85

**为什么你认为需要此功能**

* QQ超级表情内测的时候帧数高，现在加了限制，达不到60帧，感觉不流畅，看着难受

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  qq里面的超级表情（聊天界面），去掉帧数限制，达到高刷

**Comment by cinit** [comment]
@Nevodev won't fix
