### ISSUE TITLE
[QQ 8.8.88.7830] 太极已阻止QQ闪退

### ISSUE THREAD

**Issue by b4imetu** [ferredoxin/QNotified#1309]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.88.7830

**模块版本/Module Version**

* QNotified 1.0.0.d4f980f

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极 9.0.1.04182224

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

MIUI 13 22.5.11 Beta，QNotified 可以初始化，
![2B2E8BE7638417722E41E7220A2D24AE](https://user-images.githubusercontent.com/41535001/169299272-40f38eb8-07ec-4aa3-8305-43ef0733d8a6.jpg)
但是设置里点击QNotified，立刻显示`太极已阻止QQ闪退` 然后黑屏，
![8BDC16A19CD77C953CEF8F3DCF5017E4](https://user-images.githubusercontent.com/41535001/169299300-ba23dc58-662b-46ce-8210-ebc23738b090.jpg)
![2E5FBBB7A1742B297CB69BE477EE5654](https://user-images.githubusercontent.com/41535001/169299316-6743e09f-f671-43b4-a18b-cd37f8fb783a.jpg)

QNotified应用内显示未激活Xposed，无法使用，
![9E56EC85106F741531C4376710608AF4](https://user-images.githubusercontent.com/41535001/169299434-ec341c51-3541-4afc-ac86-21f3564d7da8.jpg)
不去设置QNotified的话，QQ本体可以正常使用。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by cinit** [comment]
更新 QNotified 694b73911131e8275ef093cba2099a2e09ba9963

**Comment by b4imetu** [comment]
> 更新 QNotified [694b739](https://github.com/ferredoxin/QNotified/commit/694b73911131e8275ef093cba2099a2e09ba9963)

[QNotified CI版](https://install.appcenter.ms/orgs/qnotifieddev/apps/qnotified/distribution_groups/alpha))
更新QNotified 版本1.0.1.6f5520f 之后已解决
Thx <3
