### ISSUE TITLE
[QQ8.9.5.8845] QQ插件界面无法进入

### ISSUE THREAD

**Issue by hankarry** [ferredoxin/QNotified#1327]
**QQ(TIM)版本/QQ(TIM) Version**
QQ8.9.5.8845
* 

**模块版本/Module Version**
1.0.1.6f5520f
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极10.0.0.08101220-8341
* 

**问题的具体描述/Detailed Description of the Bug**
 
*  具体描述(如复现BUG所需要的前提和必要操作等)
使用太极重装QQ后，装入QNotifid重启QQ，几乎是在华为平板鸿蒙系统的平行视界功能下完成，第一次运行出现了条款允许界面，点击允许后界面异常，对应的那半屏黑屏
后尝试重装QQ与取消优化无效
![Screenshot_20220824_145601_com tencent mobileqq](https://user-images.githubusercontent.com/63282735/186352026-a1547694-1cba-48a3-bbc7-d4ffe01fa802.jpg)
![Screenshot_20220824_145606_com tencent mobileqq](https://user-images.githubusercontent.com/63282735/186352065-ff4eac7d-a33d-4eed-b75a-77821c9e952c.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

</code></pre></details>

**Comment by teble** [comment]
@hankarry 换 qa, qn 跑路了

**Comment by A1Panda** [comment]
> 

你好请问 qa的下载链接有么

**Comment by teble** [comment]
https://github.com/cinit/QAuxiliary
