### ISSUE TITLE
[QQ8.8.33] 安卓13无法使用

### ISSUE THREAD

**Issue by 100pangci** [ferredoxin/QNotified#1334]
**QQ8.8.33**

* 

**模块版本1.0.1**

* 

**使用lsposed做框架**

* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述
* 只要点到qn的二级界面，然后点同意，QQ就崩溃了。
之前MIUI13，安卓12同版本是可以打开的
升到13就不行了。
现在系统是crdioid

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
https://paste.crdroid.net/76rNWq（崩溃好像抓不到）
</code></pre></details>

**Comment by cinit** [comment]
@100pangci 换qa
