### ISSUE TITLE
[功能需求] 不更新了吗


### ISSUE THREAD

**Issue by baiqilingnai** [ferredoxin/QNotified#1335]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by qimlisky** [comment]
qn不会了，qa也没了，前一天qa还说有人在QQ官方体验群发有关qa的后一天就停止维护

**Comment by cinit** [comment]
@zxluxi 是的

**Comment by qimlisky** [comment]
挺伤心的

**Comment by qimlisky** [comment]
> @zxluxi 是的

作者以后会自己写了用吗？

**Comment by cinit** [comment]
@zxluxi 自然是不用 qn 了

**Comment by 114514ns** [comment]
> qn不会了，qa也没了，前一天qa还说有人在QQ官方体验群发有关qa的后一天就停止维护

qa还在

**Comment by Penguin0321** [comment]
新版本QQ已经更换框架并且强制旧版本账号退出了
