### ISSUE TITLE
[此处填写QQ或TIM版本号] 简要概况问题

### ISSUE THREAD

**Issue by kagg886** [ferredoxin/QNotified#1338]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.9.63.11330

**模块版本/Module Version**

* 1.4.1.r1455

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
LSPosed
* 

**问题的具体描述/Detailed Description of the Bug**
NT架构下的防撤回失效

*  具体描述(如复现BUG所需要的前提和必要操作等)

无

**此处贴你获取到的日志信息/Log here**

无

**Comment by cinit** [comment]
@kagg886 已经跑路了，感谢您的支持。

**Comment by kagg886** [comment]
> @kagg886 已经跑路了，感谢您的支持。
发错仓库了 不好意思 -_-
