### ISSUE TITLE
[Bug]QQ8.4.1 以图片方式打开闪照产生卡顿

### ISSUE THREAD

**Issue by bling-yshs** [ferredoxin/QNotified#154]
打开“以图片方式打开闪照”后，在QQ群一滑动到有图片的消息时，就能感受到明显的卡顿。关闭这个功能后，卡顿感消失。

QQV8.4.1.4680
QNotified0.8.3
EDXP安卓10
![IMG_20200810_221204](https://user-images.githubusercontent.com/41812674/89793659-b516d980-db58-11ea-85ea-a03d7931a88f.jpg)
![IMG_20200810_222950](https://user-images.githubusercontent.com/41812674/89794007-1048cc00-db59-11ea-87a9-56763cf3dd38.jpg)

**Comment by singleNeuron** [comment]
@bling-yshs 好耶

**Comment by lliioollcn** [comment]
现在还有这个问题吗

**Comment by bling-yshs** [comment]
> 现在还有这个问题吗

现在... 现在我甚至找不到这个功能跑哪去了..

**Comment by lliioollcn** [comment]
> > 现在还有这个问题吗
> 
> 现在... 现在我甚至找不到这个功能跑哪去了..

qq净化里的扩展

**Comment by bling-yshs** [comment]
> > > 现在还有这个问题吗
> > 
> > 
> > 现在... 现在我甚至找不到这个功能跑哪去了..
> 
> qq净化里的扩展

哦 现在确实没问题了 话题我给关了吧
