### ISSUE TITLE
[QQ/TIM] 复读+1不支持长消息(MessageForLongText)

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#20]
rt

**Comment by cinit** [comment]
文本消息还是图片?

**Comment by cinit** [comment]
有截图吗？

**Comment by sjackser** [comment]
> 有截图吗？

文字消息，截图待会

**Comment by sjackser** [comment]
> 有截图吗？

https://sm.ms/image/6C51ZDxm8p2K4Fu
https://sm.ms/image/SbnBoaJguqPGLv3

**Comment by sjackser** [comment]
初步推测和Emoji有关系？

**Comment by cinit** [comment]
看到消失了...有没有缩小版本的?

**Comment by cinit** [comment]
应该不是emoji

**Comment by sjackser** [comment]
> 看到消失了...有没有缩小版本的?

缩小目前没找到…感觉要有很特定的长度，附一个无emoji的
![Screenshot_20200203-094739_QQ](https://user-images.githubusercontent.com/24774842/73619923-7d3f4e80-466a-11ea-91ee-a688ecc8582a.png)

**Comment by cinit** [comment]
可能是消息类型不同吧(如果找不到缩小的+1图标的话)，我待会翻翻代码

**Comment by NextAlone** [comment]
#686

**Comment by NextAlone** [comment]
现在测试一下是否可用
