### ISSUE TITLE
[功能需求]防撤回消息定位

### ISSUE THREAD

**Issue by whycantiusemyname** [ferredoxin/QNotified#216]
就是在尝试撤回的提示上可以定位到那条消息（主要还是撤回了图片也不显示啊）

**Comment by IJustWantANamePlease** [comment]
> 好麻烦的啊...

可以把撤回提示放到对应消息下面吗，错位的完全不知道撤回的是哪条😂

**Comment by whycantiusemyname** [comment]
> > 好麻烦的啊...
> 
> 可以把撤回提示放到对应消息下面吗，错位的完全不知道撤回的是哪条😂

这个感觉也可以，可能也方便做一点

**Comment by jiasswee** [comment]
同样需要，如果太难实现可以把撤回消息放到对应消息下面也行

**Comment by 2938137849** [comment]
同样需要，我觉得直接让原消息不撤回，然后把撤回提示放到对应消息下面就行了

**Comment by Hakuin123** [comment]
考古，这个需求似乎已经实现了hhh 看样子这个issue还没有被close（

**Comment by cinit** [comment]
QAuxiliary 在 NT QQ 8.9.63+ 的撤回提示已添加防撤回消息定位，此题关闭。
