### ISSUE TITLE
[Bug]QQ8.4.5 屏蔽@全体成员不生效

### ISSUE THREAD

**Issue by Howard20181** [ferredoxin/QNotified#245]
Ver. 0.8.9.115.64b1a36 
QQ ver. 8.4.5(1468) 
EdXposed v0.4.6.4(4556)(YAHFA) 

选中群聊点击完成后返回还是选中0个群

**Comment by 122cygf** [comment]
@Howard20181 现在应该可以保存了，尝试一下新版本

**Comment by Howard20181** [comment]
> @Howard20181 现在应该可以保存了，尝试一下新版本

新版本确认可以保存配置，实际效果等待下一次被@全体～

**Comment by Howard20181** [comment]
0.8.9.120.9b071e9 可以保存设置，但是通知照发 
QQ 8.4.5(1468)

**Comment by cinit** [comment]
@Howard20181 下次一定
