### ISSUE TITLE
[QQ8.5.0]简洁模式 发送按钮显示残缺

### ISSUE THREAD

**Issue by 814004737** [ferredoxin/QNotified#250]
![S00827-17521777(1)(1)](https://user-images.githubusercontent.com/42638734/91432448-5362a900-e894-11ea-8666-787157a2cfa6.png)
这个发送按钮显示不全
0.8.9.124版本

**Comment by qwq233** [comment]
现在还有没有该情况

**Comment by 814004737** [comment]
有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gao_cai_sheng"<notifications@github.com&gt;; 
发送时间: 2021年1月9日(星期六) 中午1:17
收件人: "ferredoxin/QNotified"<QNotified@noreply.github.com&gt;; 
抄送: "左效飞"<814004737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ferredoxin/QNotified] [Bug]QQ简洁模式 发送按钮显示残缺 (#250)





 
现在还有没有该情况

**Comment by lliioollcn** [comment]
请提供下qq版本

**Comment by qwq233** [comment]
模块版本 qq版本 另关闭模块是否出现此情况

**Comment by 814004737** [comment]
模块0.8.10.246.d1b3030
QQ8.5.0(1596)
关闭模块后无此情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gao_cai_sheng"<notifications@github.com&gt;; 
发送时间: 2021年1月9日(星期六) 中午1:49
收件人: "ferredoxin/QNotified"<QNotified@noreply.github.com&gt;; 
抄送: "左效飞"<814004737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ferredoxin/QNotified] [Bug]QQ简洁模式 发送按钮显示残缺 (#250)





 
模块版本 qq版本 另关闭模块是否出现此情况

**Comment by NextAlone** [comment]
关闭Omega的发送卡片大概率可以解决。

**Comment by 814004737** [comment]
没有开启该功能😭



---原始邮件---
发件人: "NextAlone"<notifications@github.com&gt;
发送时间: 2021年2月18日(周四) 下午3:47
收件人: "ferredoxin/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "夏沫"<814004737@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] [Bug]QQ简洁模式 发送按钮显示残缺 (#250)




 
关闭Omega的发送卡片大概率可以解决。

**Comment by huajijam** [comment]
@814004737 请尝试关闭所有类似于美化/主题的更改，在关闭了发送xml卡片功能后我们并不会对发送按钮及其附属组件做出更改

**Comment by huajijam** [comment]
@814004737 另外，请尝试更新到最新的CI版本qn

**Comment by 814004737** [comment]
在qn模块内重置模块设置后，当显示为未激活时无问题，当激活模块后就会出现问题
百思不得其解，辛苦开发者了



---原始邮件---
发件人: "huajijam"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 中午11:47
收件人: "ferredoxin/QNotified"<QNotified@noreply.github.com&gt;;
抄送: "夏沫"<814004737@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] [QQ8.5.0]简洁模式 发送按钮显示残缺 (#250)




 
@814004737 请尝试关闭所有类似于美化/主题的更改，在关闭了发送xml卡片功能后我们并不会对发送按钮及其附属组件做出更改

**Comment by lliioollcn** [comment]
请问现在还有无此问题？

**Comment by PRO-2684** [comment]
![Screenshot_2022-06-09-18-10-47-947_com tencent mobileqq](https://user-images.githubusercontent.com/54608551/172823609-e8dde64a-2493-47de-80a0-00d591707382.png)
