### ISSUE TITLE
[Bug]QQ？开启小尾巴时小尾巴内容与图片分离

### ISSUE THREAD

**Issue by whycantiusemyname** [ferredoxin/QNotified#260]
设置了小尾巴后，有几率会出现发送图片时先发送空消息加上小尾巴 然后再发图片的情况（触发条件未知，目前只遇上两次）
![-351e8dedf6545d46](https://user-images.githubusercontent.com/60563852/91636930-23b5bd00-e9ca-11ea-8558-223871cca78a.jpg)

**Comment by whycantiusemyname** [comment]
脑抽了 刚刚又试了下 其实就是选中图片后 用上面的发送按钮（就是输入框旁边的 就会出现这个bug

**Comment by lliioollcn** [comment]
#210
