### ISSUE TITLE
复读机可以自定义复读次数吗

### ISSUE THREAD

**Issue by CXY23** [ferredoxin/QNotified#3]
如果复读多次得一直点好累的 @cinit

**Comment by cinit** [comment]
Emm...类似长按(+1)圆圈选择复读次数?

**Comment by CXY23** [comment]
对 +1可以自定义或者其他方式实现

**Comment by Vstory** [comment]
所有聊天气泡都显示+1，很影响美观。是否支持隐藏+1，直接点击+1位置就可以复读？
@cinit

**Comment by cinit** [comment]
@Vstory 那加个修改(+1)透明度
