### ISSUE TITLE
[Bug]QQ848 bug收集

### ISSUE THREAD

**Issue by 122cygf** [ferredoxin/QNotified#306]
因为848有嗷嗷多的适配问题，所以关于848的问题可以都在这里说

**Comment by 122cygf** [comment]
长按消息没有复制卡片，屏蔽一起嗨无效，群聊回复禁止艾特失效，强制使用系统文件还没适配

**Comment by 122cygf** [comment]
检查消息，私聊无法撤回

**Comment by whalechoi** [comment]
语音转发也没了

**Comment by tianqiqaq** [comment]
小尾巴，聊天小尾巴也没有，望尽快适配

**Comment by singleNeuron** [comment]
@tianqiqaq 望打钱，望提交pr

**Comment by 122cygf** [comment]
> 语音转发也没了

应该是所有在长按菜单中加按钮的功能都不好使了 @whalechoi

**Comment by tianqiqaq** [comment]
> > 语音转发也没了
> 
> 应该是所有在长按菜单中加按钮的功能都不好使了 @whalechoi

对，可能是因为QQ菜单改版成微信那种样子的原因吧

**Comment by 122cygf** [comment]
万象撤回修了

**Comment by singleNeuron** [comment]
@122cygf 好耶

**Comment by 122cygf** [comment]
群聊回复禁止艾特修了

**Comment by sudami** [comment]
我昨天已完美适配QQ 8.4.8 ，提供几个适配点吧：

1. **语音转发（创建菜单）**

CustomMenu.createItem 调用构造函数在QQ>=8.4.8时，需要传递2个参数，类似如下代码

> Object item = null;
            try
            {
                item = clazz.newInstance();
            }
            catch (Throwable e)
            {
                e.printStackTrace();
                item = XposedHelpers.newInstance(clazz, id, title);
            }

2. **语音转发（创建头像）**
FaceImpl.java 构造函数中 QQ>=8.4.8的函数变成了 setDecodeTaskCompletionListener，类似如下代码

> //public void setDecodeTaskCompletionListener(FaceDecoder.DecodeTaskCompletionListener arg2)
            Utils.invoke_virtual(mFaceDecoder, "setDecodeTaskCompletionListener", createListener(), clz_DecodeTaskCompletionListener);
    

3. **getTroopMemberNick** 函数内部需要微调，改为 “Throwable”

![111](https://user-images.githubusercontent.com/6194926/92834413-954f2b80-f40c-11ea-8cfd-f8ddae124bf3.png)
![222](https://user-images.githubusercontent.com/6194926/92834423-97b18580-f40c-11ea-86f4-a9b9edddfa9f.png)

**Comment by 122cygf** [comment]
> 我昨天已完美适配QQ 8.4.8 ，提供几个适配点吧：
> 
> 1. **语音转发（创建菜单）**
> 
> CustomMenu.createItem 调用构造函数在QQ>=8.4.8时，需要传递2个参数，类似如下代码
> 
> > Object item = null;
> > try
> > {
> > item = clazz.newInstance();
> > }
> > catch (Throwable e)
> > {
> > e.printStackTrace();
> > item = XposedHelpers.newInstance(clazz, id, title);
> > }
> 
> 1. **语音转发（创建头像）**
>    FaceImpl.java 构造函数中 QQ>=8.4.8的函数变成了 setDecodeTaskCompletionListener，类似如下代码
> 
> > //public void setDecodeTaskCompletionListener(FaceDecoder.DecodeTaskCompletionListener arg2)
> > Utils.invoke_virtual(mFaceDecoder, "setDecodeTaskCompletionListener", createListener(), clz_DecodeTaskCompletionListener);
> 
> 1. **getTroopMemberNick** 函数内部需要微调，改为 “Throwable”
> 
> ![111](https://user-images.githubusercontent.com/6194926/92834413-954f2b80-f40c-11ea-8cfd-f8ddae124bf3.png)
> ![222](https://user-images.githubusercontent.com/6194926/92834423-97b18580-f40c-11ea-86f4-a9b9edddfa9f.png)

感谢

**Comment by youling257** [comment]
一直不知道别人发的“正在加载应用组件”是什么内容，开启“强制使用默认气泡”，终于看到了内容。
更新8.4.8，“强制使用默认气泡”无效，看不到“正在加载应用组件”的内容。

**Comment by 122cygf** [comment]
@youling257 关了这个功能就能看到应用组件了是吗

**Comment by youling257** [comment]
8.4.5，开启“强制使用默认气泡”，能看到应用组件内容

**Comment by youling257** [comment]
跟“强制启用默认气泡”无关，瞎鼓捣了一番，在8.4.8看到了应用组件的内容。

**Comment by 122cygf** [comment]
848长按消息弹出菜单注入修了

**Comment by Larusxu** [comment]
随机骰子还能修复嘛🤔

**Comment by 122cygf** [comment]
@Larusxu 能，已经修了，下午推代码

**Comment by 122cygf** [comment]
改骰子点数修了

**Comment by tianqiqaq** [comment]
内个，卡片发送为啥用不了，是没适配🐴

**Comment by huajijam** [comment]
@tianqiqaq 卡片发送功能暂未完全开放 请等待后续更新

**Comment by tianqiqaq** [comment]
> @tianqiqaq 卡片发送功能暂未完全开放 请等待后续更新

@huajijam 好的，谢谢

**Comment by taycke** [comment]
防撤回gkdgkdgkd

**Comment by msj1423** [comment]
可以复制卡片代码，但无法发送卡片（长按发送无反应）
version: 0.8.10.191.5788496
太极框架下测试运行的结果

**Comment by taycke** [comment]
@msj1423 这个是已知

**Comment by msj1423** [comment]
> @msj1423 这个是已知

好的，因为我看上次问是9天前，我看插件更新是17号，我以为是修复后还有问题，原来是一直就没好...

**Comment by singleNeuron** [comment]
@msj1423 QQ是848?

**Comment by msj1423** [comment]
> @msj1423 QQ是848?

是，群聊发不出去，给单个好友发会显示错误Failed: java.net.ConnectException: Failed...

**Comment by singleNeuron** [comment]
@msj1423 需要魔法上网

**Comment by msj1423** [comment]
> @msj1423 需要魔法上网

挂了一下，群发还是不行，私发变成了“禁止自动回复类卡片”，可能卡片代码不行了

**Comment by taycke** [comment]
@msj1423 这是我们对发送卡片消息的限制

**Comment by singleNeuron** [comment]
@msj1423 别玩这种sb消息了，发点正常代码吧

**Comment by shadowwe** [comment]
1. 打开之后不能切换到简洁模式了，点了之后会显示切换中然后没反应
2. qq角标显示的选项被去掉了，会导致没有新消息的时候显示一个角标或者有新消息没角标

**Comment by singleNeuron** [comment]
> 因为848有嗷嗷多的适配问题，所以关于848的问题可以都在这里说

请合理使用看板功能并分配issues

**Comment by Littlegolden** [comment]
所以848现在该升吗

**Comment by singleNeuron** [comment]
@Littlegolden 不知道

**Comment by Marukon** [comment]
“屏蔽指定群@全体成员通知”和“屏蔽指定群的红包通知”不能用。

**Comment by JinXiaoguang** [comment]
开启QN一段时间之后, QQ桌面图标会有消息红点, 但QQ并没有未读消息.目前实测有效的消除办法是在太极中取消qn的勾选然后重启QQ

**Comment by Lagrio** [comment]
@JinXiaoguang 无法复现
系统版本 使用太极阴？

**Comment by JinXiaoguang** [comment]
> @JinXiaoguang 无法复现
> 系统版本 使用太极阴？

荣耀v20, magic3.1.0 10.1.0.170.
太极阴.
我也不知道触发条件, 所以需要其他更详细信息的话, 只能在下次遇到时再提供

**Comment by username-long111** [comment]
可能是历史好友

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;金小光&quot;<notifications@github.com&gt;
发送时间: 2020年11月22日(周日) 下午4:21
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] [Bug]QQ848 bug收集 (#306)




 
开启QN一段时间之后, QQ桌面图标会有消息红点, 但QQ并没有未读消息.目前实测有效的消除办法是在太极中取消qn的勾选然后重启QQ
 
&mdash;
