### ISSUE TITLE
希望增添自动撤回群成员消息的功能

### ISSUE THREAD

**Issue by 1340388476** [ferredoxin/QNotified#309]
方便管理群

**Comment by singleNeuron** [comment]
@1340388476 发一条自动撤回一条那你还要群干啥，全员禁言多好

**Comment by 1340388476** [comment]
> @ 1340388476发一条自动撤回一条那你还要群干啥，全员禁言多好

不是啊，我的意思是自动撤回群员某种特定的消息，推广引流类的那种

**Comment by singleNeuron** [comment]
@1340388476 好耶

**Comment by 1340388476** [comment]
> @1340388476 好耶

抱歉啊，没说清楚

**Comment by 1340388476** [comment]
> > @1340388476 好耶
> 
> 抱歉啊，没说清楚

还有大佬，再提出个问题，之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情

**Comment by singleNeuron** [comment]
@1340388476 好耶

**Comment by huajijam** [comment]
@1340388476 然后呢

**Comment by 1340388476** [comment]
> @1340388476 然后呢

没然后了呀

**Comment by huajijam** [comment]
> > @1340388476 然后呢
> 
> 没然后了呀

那现在呢？

**Comment by 1340388476** [comment]
> > > @1340388476 然后呢
> > 
> > 没然后了呀
> 
> 那现在呢？

？？？

**Comment by huajijam** [comment]
> > > > @1340388476 然后呢
> > > 
> > > 
> > > 没然后了呀
> > 
> > 
> > 那现在呢？
> 
> ？？？

之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
然后呢？？？？？

**Comment by 1340388476** [comment]
> > > > > @1340388476 然后呢
> > > > 
> > > > 
> > > > 没然后了呀
> > > 
> > > 
> > > 那现在呢？
> > 
> > ？？？
> 
> 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> 然后呢？？？？？

奥你是说这个啊，就是那个开关被移除了

**Comment by huajijam** [comment]
> > > > > > @1340388476 然后呢
> > > > > 
> > > > > 
> > > > > 没然后了呀
> > > > 
> > > > 
> > > > 那现在呢？
> > > 
> > > 
> > > ？？？
> > 
> > 
> > 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> > 然后呢？？？？？
> 
> 奥你是说这个啊，就是那个开关被移除了

该功能暂不支持>=8.2.0的QQ 在“实验性功能”里，请检查你的QQ版本

**Comment by 1340388476** [comment]
> > > > > > > @1340388476 然后呢
> > > > > > 
> > > > > > 
> > > > > > 没然后了呀
> > > > > 
> > > > > 
> > > > > 那现在呢？
> > > > 
> > > > 
> > > > ？？？
> > > 
> > > 
> > > 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> > > 然后呢？？？？？
> > 
> > 奥你是说这个啊，就是那个开关被移除了
> 
> 该功能暂不支持>=8.2.0的QQ 在“实验性功能”里，请![Screenshot_20200910-214157_QQ.jpg](https://user-images.githubusercontent.com/71079887/92738611-ac5f3080-f3ae-11ea-9f10-e35eda6014dc.jpg)

**Comment by huajijam** [comment]
> > > > > > > > @1340388476 然后呢
> > > > > > > 
> > > > > > > 
> > > > > > > 没然后了呀
> > > > > > 
> > > > > > 
> > > > > > 那现在呢？
> > > > > 
> > > > > 
> > > > > ？？？
> > > > 
> > > > 
> > > > 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> > > > 然后呢？？？？？
> > > 
> > > 
> > > 奥你是说这个啊，就是那个开关被移除了
> > 
> > 
> > 该功能暂不支持>=8.2.0的QQ 在“实验性功能”里，请![Screenshot_20200910-214157_QQ.jpg](https://user-images.githubusercontent.com/71079887/92738611-ac5f3080-f3ae-11ea-9f10-e35eda6014dc.jpg)

![image](https://user-images.githubusercontent.com/29218242/92738972-0102ab80-f3af-11ea-8f0e-771ee495f61e.png)

**Comment by huajijam** [comment]
> > > > > > > > > > @1340388476 然后呢
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 没然后了呀
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 那现在呢？
> > > > > > > 
> > > > > > > 
> > > > > > > ？？？
> > > > > > 
> > > > > > 
> > > > > > 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> > > > > > 然后呢？？？？？
> > > > > 
> > > > > 
> > > > > 奥你是说这个啊，就是那个开关被移除了
> > > > 
> > > > 
> > > > 该功能暂不支持>=8.2.0的QQ 在“实验性功能”里，请![Screenshot_20200910-214157_QQ.jpg](https://user-images.githubusercontent.com/71079887/92738611-ac5f3080-f3ae-11ea-9f10-e35eda6014dc.jpg)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29218242/92738972-0102ab80-f3af-11ea-8f0e-771ee495f61e.png)
> 
> 额，我的意思是，在＞8.2.0会以“即使没有svip，也会加载svip所同步的所有历史表情”这种形式生效，但是没有入口

无法完整支持的功能为什么需要入口

**Comment by 1340388476** [comment]
> > > > > > > > > > > @1340388476 然后呢
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 没然后了呀
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 那现在呢？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ？？？
> > > > > > > 
> > > > > > > 
> > > > > > > 之前的功能“保存更多表情”是有用的，打开这个功能，即使没有svip，也会加载svip所同步的所有历史表情
> > > > > > > 然后呢？？？？？
> > > > > > 
> > > > > > 
> > > > > > 奥你是说这个啊，就是那个开关被移除了
> > > > > 
> > > > > 
> > > > > 该功能暂不支持>=8.2.0的QQ 在“实验性功能”里，请![Screenshot_20200910-214157_QQ.jpg](https://user-images.githubusercontent.com/71079887/92738611-ac5f3080-f3ae-11ea-9f10-e35eda6014dc.jpg)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/29218242/92738972-0102ab80-f3af-11ea-8f0e-771ee495f61e.png)
> > 
> > 额，我的意思是，在＞8.2.0会以“即使没有svip，也会加载svip所同步的所有历史表情”这种形式生效，但是没有入口
> 
> 无法完整支持的功能为什么需要入口

😂😂😂好吧麻烦了大佬，跟我尬聊许久添麻烦了，期待你们的更新，抱歉抱歉，感谢感谢
