### ISSUE TITLE
[功能需求]希望能添加去除群荣誉标志的功能

### ISSUE THREAD

**Issue by nlh002** [ferredoxin/QNotified#33]
这东西看着挺烦的...而且只有管理员和群主能关掉

**Comment by cinit** [comment]
龙王什么的?

**Comment by cinit** [comment]
龙王什么的?

**Comment by nlh002** [comment]
是的，跟之前那个什么群聊等级一样

**Comment by Vstory** [comment]
还有这个
 [戳我](https://i.loli.net/2020/02/21/Xb1ehOf9cpL2jFA.jpg) 

🌚

**Comment by wqk317** [comment]
@nlh002 @cinit 
龙王在8.2.8里边已经去掉了，精简模式下

**Comment by ketal178** [comment]
可在设置->隐私->群互动标识及幸运字符设置
内关闭
![J61 _BT@ST 8 BUR}7(9`3X](https://user-images.githubusercontent.com/41381927/106344995-ff973880-62e7-11eb-8ada-8fdcdb05ead5.jpg)
