### ISSUE TITLE
[BUG]QQ8.4.1 QQ净化隐藏侧滑栏每日打卡 未生效

### ISSUE THREAD

**Issue by T9041** [ferredoxin/QNotified#334]
**QQ(TIM)版本/QQ(TIM) Version**8.4.1

**模块版本/Module Version**0.8.10.191.5788496

**使用框架与框架版本呢/Xposed Framework and Framework Version**EdXposed SandHook 4529

**什么情况/What happened?** QQ净化-侧滑栏-隐藏侧滑栏列表-每日打卡    开启了之后未生效

**Comment by taycke** [comment]
你是不是使用了第三方主题

**Comment by JasonKhew96** [comment]
@T9041 换YAHFA试试？

**Comment by T9041** [comment]
> 你是不是使用了第三方主题

默认主题鸭

**Comment by T9041** [comment]
> @T9041 换YAHFA试试？

试了一下YAHFA也不能隐藏

**Comment by KyuubiRan** [comment]
每日打卡不是左上角那个打卡

**Comment by lliioollcn** [comment]
现在还有这个问题吗

**Comment by qwq233** [comment]
Lost connection
