### ISSUE TITLE
[BUG] 8.4.10 简洁模式圆头像失效

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#341]
**QQ(TIM)版本/QQ(TIM) Version**
8.4.10(1506)
* 

**模块版本/Module Version**
0.8.10.200.7960735
* 

**使用框架与框架版本呢/Xposed Framework and Framework Version**
EdXp 0.4.6.2(4529)(YAHFA)
* 

**什么情况/What happened?**
如题
*

**Comment by singleNeuron** [comment]
@Neubulae 显而易见的没适配

**Comment by Neubulae** [comment]
> @Neubulae 显而易见的没适配

显而易见地提了issue（

8.4.10似乎根本没几个人收到推送吧？尤其是测试版

**Comment by 122cygf** [comment]
> > @Neubulae 显而易见的没适配
> 
> 显而易见地提了issue（
> 
> 8.4.10似乎根本没几个人收到推送吧？尤其是测试版

所以显而易见的没适配
