### ISSUE TITLE
代码许可证与最终用户许可协议冲突

### ISSUE THREAD

**Issue by qwq233** [ferredoxin/QNotified#347]
RT
GPL协议允许在开源情况商业使用，但许可协议中规定不得售卖发行。
一般情况下接受许可协议才可以继续使用，从而限制用户售卖QN。
但只有使用才需要接受许可协议，若不使用貌似可以不需要接受该协议。
目前GPL作为源码的许可证，貌似是大于用户许可协议的。
额，语言可能比较混乱，各位懂就行，反正我觉得最好做出调整

**Comment by singleNeuron** [comment]
@qwq233 猜测是开发组自己本身就很混乱，我们需要一个法律顾问，建议更改许可协议后提交pr。

**Comment by qwq233** [comment]
> @qwq233 猜测是开发组自己本身就很混乱，我们需要一个法律顾问，建议更改许可协议后提交pr。

@singleNeuron 唔 目前我这边没什么头绪 如果要改的话所有代码头部都要改，问了下更改现有许可证还要经过所有贡献者同意，反正就是工程量较大，你们这边又关掉了讨论群组，讨论起来着实有点麻烦

**Comment by singleNeuron** [comment]
@qwq233 给我你的telegram id

**Comment by qwq233** [comment]
@singleNeuron 通过qwq233@qwq2333.top这个邮箱发到Cryolitia@gmail.com里了

**Comment by qwq233** [comment]
solved
