### ISSUE TITLE
捐助打赏渠道？

### ISSUE THREAD

**Issue by iAvoe** [ferredoxin/QNotified#354]
不是bug，目前正在用QQ8.4.5，所以无法使用QN。同时在github和telegram上都找不到捐助打赏渠道，所以过来问问😚

**Comment by singleNeuron** [comment]
没有也不会提供打赏渠道，QNotified是一个开源免费非商业不盈利的项目

**Comment by singleNeuron** [comment]
另外大部分常用功能应该都已经支持845了
