### ISSUE TITLE
Tim中显示了不支持的功能

### ISSUE THREAD

**Issue by ghost** [ferredoxin/QNotified#357]
**QQ(TIM)版本/QQ(TIM) Version**

* 应该是所有版本

**模块版本/Module Version**

* QN模块v0.8.10.209.7ff924c

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* 太极阴6.4.0

**什么情况/What happened?**

*  在TIM有些不通用的功能也会显示在QN模块设置里面

**Comment by Boring24** [comment]
希望尽早修复

**Comment by singleNeuron** [comment]
@Boring24 请具体举例

**Comment by Boring24** [comment]
> @Boring24 请具体举例
> 
> @ Boring24

比如里面的QQ净化很多功能明明不适用但是没把它弄走

**Comment by huajijam** [comment]
@Boring24 pr please,No issues

**Comment by singleNeuron** [comment]
> > @Boring24 请具体举例
> > 
> > @ Boring24
> 
> 比如里面的QQ净化很多功能明明不适用但是没把它弄走

比如是哪些？请一个个列出来

**Comment by NextAlone** [comment]
> > @Boring24 请具体举例
> > @ Boring24
> 
> 比如里面的QQ净化很多功能明明不适用但是没把它弄走

因为他叫qq净化，啊这
