### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GokusaiShiki** [ferredoxin/QNotified#359]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.8(1492)

**模块版本/Module Version**

* 0.8.10.200.7960735

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* EdXposed sandhook

**什么情况/What happened?**

*  QQ净化隐藏的侧滑栏列表隐藏不了开播啦鹅
![Screenshot_2020-10-19-14-47-02-23.jpg](https://user-images.githubusercontent.com/56814766/96410754-fa6f1b80-1219-11eb-8213-4a243fab2f65.jpg)![Screenshot_2020-10-19-14-47-05-98.jpg](https://user-images.githubusercontent.com/56814766/96410796-0ce95500-121a-11eb-8d8c-04e025784697.jpg)

**Comment by username-long111** [comment]
手动上帝模式


---Original---

**Comment by GokusaiShiki** [comment]
好bua




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ferredoxin/QNotified"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 下午3:04
收件人:&nbsp;"ferredoxin/QNotified"<QNotified@noreply.github.com&gt;;
抄送:&nbsp;"丸山彩"<2100115425@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ferredoxin/QNotified] [BUG]  (#359)





 手动上帝模式 
 
 
 ---Original---
