### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SummerOfIce** [ferredoxin/QNotified#361]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.8

**模块版本/Module Version**

* 0.8.10.209.7ff924c

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* edxposed

**什么情况/What happened?**

*  屏蔽名片点赞通知失效了

**Comment by huajijam** [comment]
see issues #306
