### ISSUE TITLE
[BUG]QQ8.3.5 在运行一定时间后会开始出现卡顿，需要重启应用才能解决，但依旧在一定时间后再次出现

### ISSUE THREAD

**Issue by sonyjams** [ferredoxin/QNotified#363]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.3.5

**模块版本/Module Version**

* 0.8.10

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* yahfa 0.4.6.3

**什么情况/What happened?**

*  在运行一定时间后会开始出现卡顿，需要重启应用才能解决，但依旧在一定时间后再次出现

**Comment by qwq233** [comment]
还有这个问题吗

**Comment by sonyjams** [comment]
由于不再使用magisk无法确认是否还有此问题，但目前在太极阴环境下的8.6.0同样会出现相同的问题

**Comment by ketal178** [comment]
@sonyjams 这一看就是内存泄露，qn内存泄露的地方太多了，修不了

**Comment by sonyjams** [comment]
我又在tim上试了下，tim上倒是没有遇到这种情况
