### ISSUE TITLE
希望能加入斗图

### ISSUE THREAD

**Issue by BaiBuCYBGT** [ferredoxin/QNotified#364]
希望可以在聊天窗长按表情，触发斗图，搜索图片并发出

**Comment by singleNeuron** [comment]
@BaiBuCYBGT 这个倒是能写，但是我上哪搜索图片去

**Comment by username-long111** [comment]
qx模块有个网络表情，用那个不就行了

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;singleNeuron&quot;<notifications@github.com&gt;
发送时间: 2020年10月25日(周日) 上午8:27
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 希望能加入斗图 (#364)




 
@BaiBuCYBGT 这个倒是能写，但是我上哪搜索图片去
 
&mdash;

**Comment by singleNeuron** [comment]
@username-long111 那你用QX不就行了

**Comment by BaiBuCYBGT** [comment]
挺多搜索图片的网站的，应该可以实现吧。而且qx功能也没这个模块的多，qx还有时候会抽风用不了的，现在还是这个模块好用啊

**Comment by username-long111** [comment]
又不是我要这个功能

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;singleNeuron&quot;<notifications@github.com&gt;
发送时间: 2020年10月25日(周日) 晚上8:58
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;username-long111&quot;<2855669787@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 希望能加入斗图 (#364)




 
@username-long111 那你用QX不就行了
 
&mdash;

**Comment by Lagrio** [comment]
@username-long111 非本人需求请勿建议

**Comment by huajijam** [comment]
建议自写

**Comment by username-long111** [comment]
建议卸载

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;huajijam&quot;<notifications@github.com&gt;
发送时间: 2020年10月26日(周一) 下午5:29
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;username-long111&quot;<2855669787@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 希望能加入斗图 (#364)




 
建议自写
 
&mdash;
