### ISSUE TITLE
[功能需求]屏蔽建议屏蔽程序内推送

### ISSUE THREAD

**Issue by DDXDB** [ferredoxin/QNotified#365]
希望能添加屏蔽聊天界面上方程序内新新信息通知
![Screenshot_20201026-094157](https://user-images.githubusercontent.com/38449595/97125649-87acf580-176f-11eb-9270-1ccb8e8df605.jpg)

**Comment by huajijam** [comment]
免打扰，请

**Comment by DDXDB** [comment]
> 免打扰,请

开了免打扰还是有==

**Comment by username-long111** [comment]
是那个群开免打扰

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;DDXDB&quot;<notifications@github.com&gt;
发送时间: 2020年10月26日(周一) 下午5:43
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 屏蔽建议屏蔽程序内推送 (#365)




  
免打扰,请
  
开了免打扰还是有==
 
&mdash;

**Comment by huajijam** [comment]
> > 免打扰,请
> 
> 开了免打扰还是有==

建议删掉qq

**Comment by Boring24** [comment]
这个确实烦人

**Comment by Boring24** [comment]
> 这个确实烦人

可以用 上帝模式 删除

**Comment by Boring24** [comment]
> 这个确实烦人

可以用 上帝模式 删除

**Comment by DDXDB** [comment]
> > 这个确实烦人
> 
> 可以用 上帝模式 删除

请问上帝模式在哪里

**Comment by username-long111** [comment]
百度自己搜

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;DDXDB&quot;<notifications@github.com&gt;
发送时间: 2020年10月31日(周六) 中午11:06
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;username-long111&quot;<2855669787@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 屏蔽建议屏蔽程序内推送 (#365)




   
这个确实烦人
  
可以用 上帝模式 删除
  
请问上帝模式在哪里
 
&mdash;

**Comment by 122cygf** [comment]
@username-long111 这是个xp模块

**Comment by qwq233** [comment]
?qq可以关 看看消息提醒pls
