### ISSUE TITLE
希望加一个每日自动打卡功能

### ISSUE THREAD

**Issue by 986244073** [ferredoxin/QNotified#366]
每日自动打卡  不用自己每天去点一下了

**Comment by Lagrio** [comment]
@986244073 建议使用XAutoDaily

**Comment by taycke** [comment]
@986244073 请使用隔壁XAutoDaily

**Comment by 986244073** [comment]
插件开多了 卡

**Comment by Lagrio** [comment]
@986244073 功能开多了 也卡

**Comment by 986244073** [comment]
XAutoDaily 集成进去 麻烦吗

**Comment by username-long111** [comment]
你来搞🤔

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;Yancy&quot;<notifications@github.com&gt;
发送时间: 2020年11月7日(周六) 晚上7:09
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ferredoxin/QNotified] 希望加一个每日自动打卡功能 (#366)




 
XAutoDaily 集成进去 麻烦吗
 
&mdash;

**Comment by 986244073** [comment]
XAutoDaily好像不开源

**Comment by taycke** [comment]
你可以联系作者

**Comment by longhuan1999** [comment]
我先用的XAutoDaily，然后装了QNotified，现在有些自动打卡任务好像不执行了，不知道是QQ更新的问题还是模块冲突的问题

**Comment by taycke** [comment]
@longhuan1999 这两模块没冲突，请自查原因

**Comment by longhuan1999** [comment]
我能知道没有冲突就已经很满足了，至于“自查原因”，😂我的水平还做不到。虽然我知道是我想多了，但还是有一种被抱怨瞎说的错觉，也可能是感觉后半句话太官方用语了吧。抱歉，纯属描述个人感受（日常多想），非陈述事实，如有冒犯，联系删除
