### ISSUE TITLE
[BUG] Google Play版QQ，闪照功能无法使用

### ISSUE THREAD

**Issue by taoxian000** [ferredoxin/QNotified#369]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 7.7.6 Google Play版/8.2.10 Google Play版（Google Play只更新到8.2.10）

**模块版本/Module Version**

* 0.8.10.209

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* 太极（阳） 128

**什么情况/What happened?**

* 菜单中未出现闪照相关功能，闪照仍以原版方式打开
![微信图片_20201110114100](https://user-images.githubusercontent.com/22560916/98624913-ae5f5480-2349-11eb-9220-d0b5397be91b.png)

**Comment by JasonKhew96** [comment]
@taoxian000 闪照功能 移进 QQ净化(扩展) 菜单里了
