### ISSUE TITLE
[BUG] TIM 3.3.0未作适配

### ISSUE THREAD

**Issue by Neubulae** [ferredoxin/QNotified#374]
**QQ(TIM)版本/QQ(TIM) Version**
3.3.0
* 

**模块版本/Module Version**
latest CI
* 

**使用框架与框架版本呢/Xposed Framework and Framework Version**
edxp magisk latest Sandhook
* 

**什么情况/What happened?**
如：复读机失灵（错误复读）回复去除艾特失效（根本没有）没有圆头像选项等
*

**Comment by ketal178** [comment]
如何复现复读机失灵（错误复读） @Neubulae 
我深度测试未出现此情况

**Comment by Neubulae** [comment]
> 如何复现复读机失灵（错误复读） @Neubulae
> 我深度测试未出现此情况

当时的版本 复读机根本无法使用，随便摁都是错的
我反馈完半个多月以后似乎就修复了这个问题了

**Comment by ketal178** [comment]
> > 如何复现复读机失灵（错误复读） @Neubulae
> > 我深度测试未出现此情况
> 
> 当时的版本 复读机根本无法使用，随便摁都是错的
> 我反馈完半个多月以后似乎就修复了这个问题了

你是更新了TIM吗
