### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jssmme** [ferredoxin/QNotified#375]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.10

**模块版本/Module Version**

* 0.8.10.210---0.8.10.217

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* edxp 0.4.6.4 yahfa

**什么情况/What happened?**

*  模块升级时，无法直接重启生效，必须取消勾选再勾选重启才能生效

**Comment by taycke** [comment]
@Jssmme 建议打开即时模块设置

**Comment by JasonKhew96** [comment]
@Jssmme 升级模块前确保 EdXposed Manager 在后台，安装更新后 EdXposed Manager 会发一条通知，如果没有，重启后可能会失效
