### ISSUE TITLE
[BUG] QNotified设置入口消失问题

### ISSUE THREAD

**Issue by 1552980358** [ferredoxin/QNotified#376]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.4.5以上

**模块版本/Module Version**

* 0.8.10

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* 太极6.3

**什么情况/What happened?**

*  在内置QQ净化里开启某些功能会导致QQNotified以及QX模块在设置里的入口消失，目测与QNotiied内某个/些功能冲突或本身定位时出现问题，但QNotified与QX模块设置入口消失后部分功能能正常工作，如防撤回等，但屏蔽艾特全体则失效
解决方案为在系统设置里清理QQ全部资料，登入后入口会重新显示，所有配置都会被清空设置

**Comment by 1552980358** [comment]
8.4.8也有同样问题

**Comment by iAvoe** [comment]
已知最高适配于8.4.1

**Comment by qwq233** [comment]
现在有没有这个问题？

**Comment by lliioollcn** [comment]
#397
