### ISSUE TITLE
希望能修复自定义机型[BUG] 

### ISSUE THREAD

**Issue by dw0401** [ferredoxin/QNotified#378]
**QQ(TIM)版本/QQ(TIM) Version**
QQ版本  8.4.10
*

**模块版本/Module Version**
0.8.10.217.52b6dfc (41)
* 

**使用框架与框架版本呢/Xposed Framework and Framework Version**
太极
* 

**什么情况/What happened?**
自定义机型设置好后 在QQ聊天界面能正常使用 但是空间动态下面无法正常显示 显示了机型名字 以及型号无法区分大小写 比如iPhone 只能显示成iphone 希望看到后修复一下 感谢！
![Screenshot_20201121_003434_com tencent mobileqq](https://user-images.githubusercontent.com/54498197/99825563-cdfe3600-2b1c-11eb-989f-8db30b67e68a.jpg)
![Screenshot_20201121_003423_com tencent mobileqq](https://user-images.githubusercontent.com/54498197/99825569-d0f92680-2b1c-11eb-99e0-39e717cfb884.jpg)

*

**Comment by dw0401** [comment]
@cinit

**Comment by shiertx** [comment]
这个貌似是QQ方面的问题

*实在想显示成果子就去买个果子吧（x）*

**Comment by username-long111** [comment]
Р&nbsp;&nbsp;把P换成这个就行了

________________
2855669787@qq.com




---原始邮件---
发件人: &quot;dw0401&quot;<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 凌晨0:41
收件人: &quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [ferredoxin/QNotified] 希望能修复自定义机型[BUG]  (#378)




 
QQ(TIM)版本/QQ(TIM) Version
 QQ版本  8.4.10
 *
 
模块版本/Module Version
 0.8.10.217.52b6dfc (41)
 *
 
使用框架与框架版本呢/Xposed Framework and Framework Version
 太极
 *
 
什么情况/What happened?
 自定义机型设置好后 在QQ聊天界面能正常使用 但是空间动态下面无法正常显示 显示了机型名字 以及型号无法区分大小写 比如iPhone 只能显示成iphone 希望看到后修复一下 感谢！
 
 
  
  
&mdash;
