### ISSUE TITLE
想请问一下现在的模块支持到哪个版本了呢·

### ISSUE THREAD

**Issue by zeyejiang** [ferredoxin/QNotified#384]
因为我找遍了整个页面也没看到模块支持哪个版本，就是想问一下，还请作者加一个支持的版本的介绍

**Comment by taycke** [comment]
@zeyejiang 整个模块现在属于玄学适配状态，每个人每个框架情况都可能不同，所以没办法给你版本支持介绍

**Comment by zeyejiang** [comment]
> @zeyejiang整个模块现在属于玄学适应状态，每个人每个框架情况都可能不同，所以没办法给你版本支持介绍

原来是这样，我用的xp现在应该是适配了最新版QQ了

**Comment by iAvoe** [comment]
我试了8.4.10, 8.4.5和8.4.1，8.34.9，8.4.1以上都不适配

**Comment by taycke** [comment]
@iAvoe 建议具体到哪一个功能

**Comment by cinit** [comment]
模块内每一个子功能对各版本QQ/TIM支持都不一样, 有高有低, 完全不统一, 没什么人用的功能可能还停留在几个月前, 主要的功能可能测试版QQ都能用, 每一个功能的各版本兼容情况都不一样, 我也不清楚
