### ISSUE TITLE
[BUG]TIM3.3.0 上传apk重命名失效

### ISSUE THREAD

**Issue by 18263212936** [ferredoxin/QNotified#385]
**QQ(TIM)版本/QQ(TIM) Version**

TIM3.3.0

**模块版本/Module Version**

0.8.10.221.c902517

**使用框架与框架版本呢/Xposed Framework and Framework Version**

edxp magisk vDEVTESTONLY.4612(SandHook)

**什么情况/What happened?**

上传apk重命名失效

**Comment by ketal178** [comment]
#516
