### ISSUE TITLE
[BUG]QQ8.4.10 使用系统相机初始化失败

### ISSUE THREAD

**Issue by 12123ads** [ferredoxin/QNotified#387]
**QQ(TIM)版本/QQ(TIM) Version**
8.4.10
* 

**模块版本/Module Version**
0.8.10.221
* 

**使用框架与框架版本呢/Xposed Framework and Framework Version**
太极，湛泸·6.4.0.09021214
* 

**什么情况/What happened?**
打开强制使用系统相机和强制使用系统文件显示初始化失败
![Screenshot_2020-12-02-21-51-16-02](https://user-images.githubusercontent.com/69107029/100881189-98782600-34e8-11eb-96d0-b5adeb1e076a.jpg)

*

**Comment by 12123ads** [comment]
这个怎么办

**Comment by NextAlone** [comment]
现在应该没问题了吧

**Comment by qwq233** [comment]
Lost connection
