### ISSUE TITLE
[BUG] 转发消息点头像查看详细信息功能群信息不准确

### ISSUE THREAD

**Issue by inkhog** [ferredoxin/QNotified#389]
**QQ(TIM)版本/QQ(TIM) Version**

8.4.18及之前多个版本

**模块版本/Module Version**

0.8.10.221.c902517

**使用框架与框架版本呢/Xposed Framework and Framework Version**

**什么情况/What happened?**

他人转发的合并消息中，显示的群号信息实际为此人转发合并消息时所在的群信息，而非信息内容所在群信息

**Comment by cinit** [comment]
本来就应该显示 原始消息所在的原始群

**Comment by inkhog** [comment]
曾经有一个合并消息传的很火，朋友转发给我后，这个消息内的人的QQ号都是正确的， 但这个群号成了我朋友呆在的那个群的群号（我不在那群），而原始群的信息却是一点没有，这种情况是怎么回事？

**Comment by cinit** [comment]
附带的QQ群号很大程度上取决于进行转发操作的那个客户端，目前能确认的是安卓QQ客户端会附上原始群号，至于PC端，我没确认过------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;inkhog&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月29日(星期二) 下午4:35
收件人:&nbsp;&quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;;
抄送:&nbsp;&quot;Acetylcholine&quot;<1041703712@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ferredoxin/QNotified] [BUG] 转发消息点头像查看详细信息功能群信息不准确 (#389)

**Comment by NextAlone** [comment]
@inkhog 是**将合并消息转发**还是**合并了转发过去的合并消息转发给你**

**Comment by inkhog** [comment]
> 附带的QQ群号很大程度上取决于进行转发操作的那个客户端，目前能确认的是安卓QQ客户端会附上原始群号，至于PC端，我没确认过------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;inkhog&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年12月29日(星期二) 下午4:35 收件人:&nbsp;&quot;ferredoxin/QNotified&quot;<QNotified@noreply.github.com&gt;; 抄送:&nbsp;&quot;Acetylcholine&quot;<1041703712@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [ferredoxin/QNotified] [BUG] 转发消息点头像查看详细信息功能群信息不准确 (#389)

那个朋友用的是电脑QQ，刚刚我自己用电脑TIM测试了一下，的确是。如果电脑转发的话，手机查看的合并消息的群号就变成了电脑转发的来源群而不是信息的原始群
