### ISSUE TITLE
[BUG] 闪照无法查看原图

### ISSUE THREAD

**Issue by Creedowl** [ferredoxin/QNotified#390]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.18

**模块版本/Module Version**

* 0.8.10.221.c902517

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* edxposed v4.5.7

**什么情况/What happened?**

*  闪照无法查看大图，只能显示预览的小图，点开不会加载原图

**Comment by lzkgbld** [comment]
问一下佬您那插件哪里看到闪照查看方式为原图的，我在太极那边打的框架没看到闪照选项了...

**Comment by Creedowl** [comment]
@lzkgbld 在qq净化里面

**Comment by lzkgbld** [comment]
> @lzkgbld在qq净化里面

感谢

**Comment by lliioollcn** [comment]
现在还有这个问题吗

**Comment by Creedowl** [comment]
@lliioollcn 目前看起来是可以正常加载闪照原图的
