### ISSUE TITLE
[BUG] qq闪退

### ISSUE THREAD

**Issue by heallly** [ferredoxin/QNotified#394]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.8

**模块版本/Module Version**

* 0.8.10.230.a074655

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* 93-v0.5.1.2 (YAHFA)

**什么情况/What happened?**

*  QQ无法打开，闪退。尝试了兼容模式，也不能正常使用
![IMG_20201220_235540_185.jpg](https://user-images.githubusercontent.com/45277152/102717760-512ec980-431f-11eb-9fee-7136d0473c2f.jpg)

**Comment by cinit** [comment]
换SandHook试试?
另: 你应该抓取QQ的log, 而不是qn的log

**Comment by qwq233** [comment]
是否还会出现此类情况？
