### ISSUE TITLE
希望可以去除QQ单次转发9次的次数限制

### ISSUE THREAD

**Issue by Huaxidesu** [ferredoxin/QNotified#395]
群太多想批量转发信息一次却只能转发9个，希望能解除这个限制

**Comment by cinit** [comment]
@Huaxidesu wont add

**Comment by cinit** [comment]
现状就在那里  
![image](https://user-images.githubusercontent.com/40174090/102737529-9e905280-4382-11eb-81ec-c4a6a83d3a4e.png)
