### ISSUE TITLE
[QQ8.5.0]自定义聊天小尾巴点选择生效的好友/群时闪退

### ISSUE THREAD

**Issue by Belikov-qq** [ferredoxin/QNotified#396]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.0

**模块版本/Module Version**

* 0.8.10.230.a074655

**使用框架与框架版本呢/Xposed Framework and Framework Version**

* Edxposed4.5.7

**什么情况/What happened?**

*  beta测试性功能里的自定义聊天小尾巴点选择生效的好友/群时闪退

**Comment by NextAlone** [comment]
已修复，等新版
