### ISSUE TITLE
[BUG] QQ 8.5.0 BUG收集

### ISSUE THREAD

**Issue by NextAlone** [ferredoxin/QNotified#398]
# 收集QQ8.5.0的BUG

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.0

## 残留BUG

* 简洁模式圆头像

**Comment by zym013579** [comment]
QQ净化里面，群聊，“隐藏滑动群应用”失效。8.4.8可用。

**Comment by yefeng1015** [comment]
除了屏蔽滑动群应用之外，还有桌面图标总是有一个角标，进了程序却找不到，已退回8.4.18

**Comment by Elaboration12138** [comment]
> QQ净化里面，群聊，“隐藏滑动群应用”失效。8.4.8可用。

已修

**Comment by lyc13822711** [comment]
语音转发，简洁模式圆头像，QQ净化内重命名文件失效

**Comment by Belikov-qq** [comment]
自定义猜拳骰子显示初始化失败
历史好友闪退

**Comment by NextAlone** [comment]
> 自定义猜拳骰子显示初始化失败
> 历史好友闪退

已修

**Comment by lyc13822711** [comment]
> 语音转发转发出去显示成功但没有，简洁模式圆头像初始化失败 QQ净化内重命名base.apk失效

**Comment by NextAlone** [comment]
@lyc13822711 先用花Q里的BaseApk，简洁模式可
