### ISSUE TITLE
[功能需求]回复带图功能

### ISSUE THREAD

**Issue by Vstory** [ferredoxin/QNotified#40]
以前QQ支持回复别人消息时，附带图片，在某一个版本开始就消失了。
这种功能QN能实现吗？

**Comment by cinit** [comment]
能否告诉我哪个老版本支持,方便我对比研究(我印象里好像没用过)

**Comment by Vstory** [comment]
> 能否告诉我哪个老版本支持,方便我对比研究(我印象里好像没用过)


我测试旧版7.3.2还是支持的
[手机QQ v7.3.2](https://apd.shouji.com.cn/cdn/shouji/xmm/MobileQQ732.apk)

**Comment by cinit** [comment]
好,那我以7.9.9为母版比对一下

**Comment by ketal178** [comment]
> > 能否告诉我哪个老版本支持,方便我对比研究(我印象里好像没用过)
> 
> 我测试旧版7.3.2还是支持的
> [手机QQ v7.3.2](https://send.firefox.com/download/dbacb00839daac9d/#HBh0nScWzbQoFeVXF2Ibmg)
> 
> 已测试v8.0.0以下全部支持 回复他人消息附带图片 功能，v7.3.2 ~ v7.9.9 均支持。
> 我记得8.x.x后的某一个版本又把该功能加回来了，不过又在某一个8.x.x版本把它阉割了。
> 
> 旧版本手机QQ可以在这里获取：[手机QQ](https://soft.shouji.com.cn/down/21530.html###)

阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死，我觉得最好不做

**Comment by Vstory** [comment]
> > > 能否告诉我哪个老版本支持,方便我对比研究(我印象里好像没用过)
> > 
> > 
> > 我测试旧版7.3.2还是支持的
> > [手机QQ v7.3.2](https://send.firefox.com/download/dbacb00839daac9d/#HBh0nScWzbQoFeVXF2Ibmg)
> > 已测试v8.0.0以下全部支持 回复他人消息附带图片 功能，v7.3.2 ~ v7.9.9 均支持。
> > 我记得8.x.x后的某一个版本又把该功能加回来了，不过又在某一个8.x.x版本把它阉割了。
> > 旧版本手机QQ可以在这里获取：[手机QQ](https://soft.shouji.com.cn/down/21530.html###)
> 
> 阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死，我觉得最好不做


醒醒，不做难道就接收不到Pc的回复带图信息？

**Comment by NextAlone** [comment]
az

**Comment by ketal178** [comment]
> > > > 能否告诉我哪个老版本支持,方便我对比研究(我印象里好像没用过)
> > > 
> > > 
> > > 我测试旧版7.3.2还是支持的
> > > [手机QQ v7.3.2](https://send.firefox.com/download/dbacb00839daac9d/#HBh0nScWzbQoFeVXF2Ibmg)
> > > 已测试v8.0.0以下全部支持 回复他人消息附带图片 功能，v7.3.2 ~ v7.9.9 均支持。
> > > 我记得8.x.x后的某一个版本又把该功能加回来了，不过又在某一个8.x.x版本把它阉割了。
> > > 旧版本手机QQ可以在这里获取：[手机QQ](https://soft.shouji.com.cn/down/21530.html###)
> > 
> > 
> > 阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死，我觉得最好不做
> 
> 醒醒，不做难道就接收不到Pc的回复带图信息？

你为啥不更新QQ
做出了你发个消息就把自己卡死

**Comment by Vstory** [comment]
> 你为啥不更新QQ
> 做出了你发个消息就把自己卡死

怎么又扯到了更新QQ上？
提交了这个issue就表示一直在用旧版本？？
不太清楚，你所谓
`阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死`
从哪里看到的。
至于卡死，都没出来功能，就能预测结果？

**Comment by ketal178** [comment]
> > 你为啥不更新QQ
> > 做出了你发个消息就把自己卡死
> 
> 怎么又扯到了更新QQ上？
> 提交了这个issue就表示一直在用旧版本？？
> 不太清楚，你所谓
> `阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死`
> 从哪里看到的。
> 至于卡死，都没出来功能，就能预测结果？

那个版本很久了，当时我用内测版的时候，出现了这个bug，内测群还有人专门发送这种消息，
印象很深

**Comment by Vstory** [comment]
> > > 你为啥不更新QQ
> > > 做出了你发个消息就把自己卡死
> > 
> > 
> > 怎么又扯到了更新QQ上？
> > 提交了这个issue就表示一直在用旧版本？？
> > 不太清楚，你所谓
> > `阉割的原因是当时的一个测试版中，收到回复带图的消息，会导致QQ卡死`
> > 从哪里看到的。
> > 至于卡死，都没出来功能，就能预测结果？
> 
> 那个版本很久了，当时我用内测版的时候，出现了这个bug，内测群还有人专门发送这种消息，
> 印象很深


无所谓了，这个issue你要不发评论，我都快忘了

**Comment by qwq233** [comment]
@Vstory 你提出需求我们要做的话肯定要先了解清楚啊

**Comment by Vstory** [comment]
哈哈
