### ISSUE TITLE
[功能请求]@界面排序由群主管理员至正常人员

### ISSUE THREAD

**Issue by Huaxidesu** [ferredoxin/QNotified#403]
新版本的艾特机制太蛋疼了，老版本艾特管理员和群主打开艾特界面的时候就排在最上面，希望Qn可以实现这个功能

**Comment by NextAlone** [comment]
@Huaxidesu 请简述该问题版本，模块版本等详细信息。

**Comment by cinit** [comment]
群聊界面文本框输入@弹出的群成员列表里，使得群主管理作为第一排序关键词，拼音作为第二关键词，是这个意思吗？

**Comment by Huaxidesu** [comment]
> 群聊界面文本框输入@弹出的群成员列表里,使得群主管理作为第一排序关键词,拼音作为第二关键词,是这个意思吗?

是

**Comment by qwq233** [comment]
这个是什么版本出现的
