### ISSUE TITLE
QQ8.5.2 群文件闪退

### ISSUE THREAD

**Issue by LTHPKBTE** [ferredoxin/QNotified#409]
QQ8.5.2

QNotified 0.8.10.233.11c81e1

Edxposed 91.0 (SandHook)

点击群文件任意一个文件即会闪退。
如果群文件没有文件夹，只有文件，打开群文件即会闪退。

**Comment by LTHPKBTE** [comment]
测试版目前有没有插件都会自行闪退。回到旧版之后打开侧边栏会自行闪退。可能是我软件有点问题

**Comment by NextAlone** [comment]
@LTHPKBTE 内测版的问题吧，

**Comment by LTHPKBTE** [comment]
> @LTHPKBTE 内测版的问题吧，

现在回到正常版本更严重了，资料卡和侧边栏都会崩溃

**Comment by NextAlone** [comment]
@LTHPKBTE 关掉qn也闪退的话，只能清除qq数据

**Comment by LTHPKBTE** [comment]
qn有导出设置的办法吗

**Comment by LTHPKBTE** [comment]
上次清数据重新设置搞老半天搞得我不怎么想清数据

**Comment by NextAlone** [comment]
@LTHPKBTE 没有，除了几个需要路径的，别的就都是开关吧，

**Comment by LTHPKBTE** [comment]
因为我很多功能都开了，自定义图片啥的都搞上了....算了我重新搞吧
