### ISSUE TITLE
[Feature] 桌面图标

### ISSUE THREAD

**Issue by HZY040122** [ferredoxin/QNotified#418]
**QQ(TIM)版本/QQ(TIM) Version**
8.2.11（play版）
* 

**模块版本/Module Version**
0.8.10.243.7063447(41)
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
edxposed 0.5.1.4_4656 YAHFA
* 

**问题的具体描述/Detailed Description of the Bug**
最新版本添加了桌面图标，但隐藏桌面图标的按钮仍然暂未开放，如何隐藏桌面图标？
*  具体描述(如复现BUG所需要的前提和必要操作等)

**Comment by Lagrio** [comment]
@HZY040122 您可以通过启动器隐藏 但我们不建议您隐藏桌面图标，这是特性的一部分而不是bug

**Comment by cinit** [comment]
您可以提交一个PR来实现桌面图标的开关

**Comment by NextAlone** [comment]
@cinit 你来啦
