### ISSUE TITLE
希望添加一个增大QQ语音消息的功能

### ISSUE THREAD

**Issue by k650dg4d2** [ferredoxin/QNotified#423]
同音量下,微信的声音就很大,但是QQ即使开了免提声音也还是特别小,得把耳朵贴上去才能听见

**Comment by cinit** [comment]
请问是所有的QQ语音消息都是如此吗？

**Comment by k650dg4d2** [comment]
> 请问是所有的QQ语音消息都是如此吗？

我的QQ语音都是这样,小米MIUI12.不知道你们的手机QQ是不是这样,你可以试一下

**Comment by qwq233** [comment]
请问是显示免提还是按了免提

**Comment by k650dg4d2** [comment]
> 请问是显示免提还是按了免提

就是按了免提之后声音还是很小,

**Comment by qwq233** [comment]
@k650dg4d2 只有它显示免提二字才是免提播放

**Comment by qwq233** [comment]
问题是否解决？

**Comment by k650dg4d2** [comment]
> 问题是否解决？

也能用,声音虽不是很大,但也能听见,如果精力有限,可以先做别的需求,或者放弃这个需求
已经解决

**Comment by qwq233** [comment]
@k650dg4d2 那挂着吧 没事应该
