### ISSUE TITLE
希望添加一个屏蔽"下载大文件的xml"的功能

### ISSUE THREAD

**Issue by Womsxd** [ferredoxin/QNotified#424]
类似这种xml，收到了就会被迫下载一个Centos的镜像或者其他文件，这取决于icon的url
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="5" templateID="1" action="" brief="[233]" sourceMsgId="0" url="" flag="0" adverSign="0" multiMsgFlag="0"><item layout="0" advertiser_id="0" aid="0"><image uuid="9A31CBB775CC2CFB09D799EA8DE47E74.jpg" md5="9A31CBB775CC2CFB09D799EA8DE47E74" GroupFiledid="0" filesize="18152" local_path="/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatimg/4e0/Cache_-5e8f02098094a4e0" minWidth="700" minHeight="1200" maxWidth="700" maxHeight="1200" /></item><source name="" icon="https://mirrors.cloud.tencent.com/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso?fileid=123456789" action="" appid="-1" /></msg>`

**Comment by Lagrio** [comment]
@Womsxd 亲，这是已有功能

**Comment by Womsxd** [comment]
火星了(
