### ISSUE TITLE
[QQ8.50] 模块在最新版edxp0.5.1.4下无法生效

### ISSUE THREAD

**Issue by Berlinwallq** [ferredoxin/QNotified#431]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**模块版本/Module Version**

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

**Comment by lliioollcn** [comment]
请提供详细报错

**Comment by qwq233** [comment]
在edxposed manager取消激活再勾选重启试试 我自己有时候也会出现这种毛病 取消勾选重启就解决了

**Comment by qwq233** [comment]
长时间未得到反馈
信息未补充
