### ISSUE TITLE
[BUG]安卓11太极框架不显示入口

### ISSUE THREAD

**Issue by margin-bqk** [ferredoxin/QNotified#437]
设置页面没有入口
小米10 miui12.5 开发版 magisk太极
QQ版本8.5和8.4都不行

**Comment by qwq233** [comment]
取消勾选再勾选试试
或者发下日志

**Comment by JasonKhew96** [comment]
> 设置页面没有入口
> 小米10 miui12.5 开发版 magisk太极
> QQ版本8.5和8.4都不行

请按照模板提交 issue

**Comment by margin-bqk** [comment]
取消勾选再勾选没有效果，我不知道你说的调试信息在哪里看，没有入口的话应该看不到吧
![Screenshot_2021-01-16-19-36-53-573_nil nadph qnotified](https://user-images.githubusercontent.com/67771037/104810942-b4e0d100-57bd-11eb-8d35-14d4e2aac53d.jpg)如果你需要调试信息的话

**Comment by qwq233** [comment]
qq号给下 被拉黑可能没入口

**Comment by margin-bqk** [comment]
812835699

**Comment by qwq233** [comment]
@margin-bqk 现在还看不到？
