### ISSUE TITLE
[QQ8.5.5(1630)] 拦截异常zip失效

### ISSUE THREAD

**Issue by ketal178** [ferredoxin/QNotified#439]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5(1630)

**模块版本/Module Version**

* 0.8.10.4fad373

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* EDXP 4.6.0-pre

**问题的具体描述/Detailed Description of the Bug**

拦截异常zip
`` 
 https://paste.ubuntu.com/p/Pb2QyQnn32/
``
*  具体描述(如复现BUG所需要的前提和必要操作等)

**Comment by NextAlone** [comment]
还有这个问题吗

**Comment by ketal178** [comment]
> 还有这个问题吗

有

**Comment by NextAlone** [comment]
请给我一个异常zip和异常图片

**Comment by qwq233** [comment]
玄学问题 关了吧要不

**Comment by taycke** [comment]
@qwq233 这玩意写出来之后就没见能用过
