### ISSUE TITLE
[功能需求]重复消息自动收叠

### ISSUE THREAD

**Issue by inkhog** [ferredoxin/QNotified#443]
**QQ(TIM)版本/QQ(TIM) Version**

8.5.0

**为什么你认为需要此功能**

交流大群复读机过多，严重影响到部分重要信息的获取，而一句复读常常需要超过十条才能显示收叠按钮。如果在历史记录内寻找以前信息则更难，希望能有自动收叠功能以免错过重要信息

**具体功能需要/Specific features required**

聊天界面最好可以像QQ原生收叠功能一样可以重新展开，历史记录如果可以希望也能加入收叠重复信息功能

**Comment by NextAlone** [comment]
@inkhog 复读阈值改为3之类的效果？

**Comment by inkhog** [comment]
如果能自己手动改阈值更好，如果不能，其实只要连续的两条相同的信息就可以收叠了，毕竟除了统计人数，我实在想不出来+1还有什么喜人的功能

**Comment by NextAlone** [comment]
功能已添加
