### ISSUE TITLE
[QQ8.5.5] 查看图片界面长按图片弹出Dialog内头像为方形

### ISSUE THREAD

**Issue by ketal178** [ferredoxin/QNotified#445]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5

**模块版本/Module Version**

* 0.8.10

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* edxp

**问题的具体描述/Detailed Description of the Bug**
![截图](https://wanandroid.com/blogimgs/d0e3b730-d06c-4d8b-9f18-ec926eb7def6.jpg)
*  具体描述(如复现BUG所需要的前提和必要操作等)

**Comment by taycke** [comment]
@ketal178 QQ是不是用的简洁模式？

**Comment by ketal178** [comment]
> @ketal178 QQ是不是用的简洁模式？

对

**Comment by NextAlone** [comment]
@ketal178 您好，简洁模式就是方的呢。？

**Comment by ketal178** [comment]
> @ketal178 您好，简洁模式就是方的呢。？

简洁模式圆头像对这里不起作用吗

**Comment by taycke** [comment]
@ketal178 对的

**Comment by qwq233** [comment]
Non-bug  -  This feature is not added
