### ISSUE TITLE
[QQ8.4.8] 开启拦截异常体积图片加载后还是会自动加载

### ISSUE THREAD

**Issue by Womsxd** [ferredoxin/QNotified#446]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.4.8

**模块版本/Module Version**

* 0.8.10.258

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

*  Xposed

**问题的具体描述/Detailed Description of the Bug**
无法拦截成功流量卡片

*  具体描述(如复现BUG所需要的前提和必要操作等)
收到一条流量卡片
流量卡片：
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="5" templateID="1" action="" brief="[流量鬼见愁]" sourceMsgId="0" url="" flag="0" adverSign="0" multiMsgFlag="0"><item layout="0" advertiser_id="0" aid="0"><image uuid="9A31CBB775CC2CFB09D799EA8DE47E74.jpg" md5="9A31CBB775CC2CFB09D799EA8DE47E74" GroupFiledid="0" filesize="18152" local_path="/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatimg/4e0/Cache_-5e8f02098094a4e0" minWidth="700" minHeight="1200" maxWidth="700" maxHeight="1200" /></item><source name="" icon="https://mirrors.cloud.tencent.com/centos/7/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso?fileid=123456789" action="" appid="-1" /></msg>`

**Comment by taycke** [comment]
@Womsxd 已知bug

**Comment by Womsxd** [comment]
> @Womsxd 已知bug

还有问下有考虑自定义设置拦截异常图片的最小值吗？
以及拦截卡屏消息

**Comment by taycke** [comment]
@Womsxd 会考虑的

**Comment by Womsxd** [comment]
这玩意也太玄学了，今天下午莫名其妙的时候拦截成功一次

**Comment by qwq233** [comment]
#439 -> 重复
