### ISSUE TITLE
[QQ8.5.5] 免广告送免费礼物在通过输入$打开的送礼界面无效

### ISSUE THREAD

**Issue by ketal178** [ferredoxin/QNotified#447]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5

**模块版本/Module Version**

* 0.8.10

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* edxp

**问题的具体描述/Detailed Description of the Bug**
[![syQoi4.jpg](https://s3.ax1x.com/2021/01/18/syQoi4.jpg)](https://imgchr.com/i/syQoi4)
[![syQ7W9.png](https://s3.ax1x.com/2021/01/18/syQ7W9.png)](https://imgchr.com/i/syQ7W9)
*  具体描述(如复现BUG所需要的前提和必要操作等)
群聊界面输入$，选择赠送对象后，选择广告礼物，会跳到广告界面

**Comment by taycke** [comment]
@ketal178 请点击聊天界面右上角进入
