### ISSUE TITLE
脚本功能不能正常被使用

### ISSUE THREAD

**Issue by PluginsKers** [ferredoxin/QNotified#450]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.2.11.4530

**模块版本/Module Version**

* 0.8.10.200

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极6.4.0

**问题的具体描述/Detailed Description of the Bug**

*  在导入(.java)文件显示“请选择正确的文件”，使用示例的代码的新文件进行尝试过，依旧。

**Comment by qwq233** [comment]
@PluginsKers 该功能还未最好

**Comment by PluginsKers** [comment]
加油嗷！✨✨✨
