### ISSUE TITLE
[QQ7.9.8]使用此模块失效，望支持

### ISSUE THREAD

**Issue by tanyi20041109** [ferredoxin/QNotified#461]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ_7.9.8

**模块版本/Module Version**

* 0.8.10.260.badce21

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极_版本 湛泸·6.4.0.09021214

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
不能使用此模块！希望支持，上个版本还好好的。

**Comment by qwq233** [comment]
@tanyi20041109 修改标题pls

**Comment by qwq233** [comment]
@tanyi20041109 顺你该升级你的qq了

**Comment by tanyi20041109** [comment]
> @tanyi20041109 顺你该升级你的qq了

太臃肿了

**Comment by ketal178** [comment]
@tanyi20041109 最起码升级到8.0.0

**Comment by qwq233** [comment]
版本过老 不会继续支持
