### ISSUE TITLE
[功能需求] 空间退回顶部按钮

### ISSUE THREAD

**Issue by tanyi20041109** [ferredoxin/QNotified#462]
**QQ(TIM)版本/QQ(TIM) Version**

* 所有版本

**为什么你认为需要此功能**

* 每次看完空间它不给我弄到最上面，导致看最新空间要划好久才看见。

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
希望添加空间退回顶部按钮

**Comment by ketal178** [comment]
说出来你可能不信，你点一下标题栏的好友动态，就回到顶部了
