### ISSUE TITLE
[QQ&TIM] "以图片的方式打开表情包"这个功能在较高的版本中失效

### ISSUE THREAD

**Issue by tanyi20041109** [ferredoxin/QNotified#463]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ应该只有8.0.0以上存在，TIM不清楚

**模块版本/Module Version**

* 0.8.10.260.badce21
//其它版本也有这个问题，至于哪几个我也不清楚

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极·湛泸·6.4.0.09021214

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
    在打开这个功能后退出"QQ净化[WIP]"页面会自动关闭！
[Screenshot_2021-01-24-14-39-58-088.png](https://user-images.githubusercontent.com/77902908/105623335-e871ca00-5e53-11eb-9491-0bcb26816361.png)

**Comment by ketal178** [comment]
你的目前QQ版本？

**Comment by tanyi20041109** [comment]
> 你的目前QQ版本？
> 

8.5.5，其它八.几的前几个月也用过 也是这样的，7.9.8没事所以推测8.0.0以上失效

**Comment by ketal178** [comment]
QQ855测试无此情况，且未出现【打开这个功能后退出"QQ净化[WIP]"页面会自动关闭】
