### ISSUE TITLE
[功能需求] QQ群提醒词

### ISSUE THREAD

**Issue by Vstory** [ferredoxin/QNotified#477]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.5.5

**为什么你认为需要此功能**
* 对于包含特定词语的信息进行特别提醒，腾讯自带的默认总共2个太少。
 

**联系到哪些已经存在的bug或者功能**
* QQ群提醒词

**具体功能需要/Specific features required**

* QQ群通过群提醒词实现订阅某些动漫番剧的发布通知

**Comment by qwq233** [comment]
#78 重复
