### ISSUE TITLE
[QQ855] QQ订阅号的批量撤回会使删除不可见

### ISSUE THREAD

**Issue by pinksheer** [ferredoxin/QNotified#484]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5

**模块版本/Module Version**

* 0.8.10.260.badce21 (41)

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极•阴内核128

**问题的具体描述/Detailed Description of the Bug**

*  在QQ订阅号中多选消息时删除按钮消失，只显示撤回。
![Screenshot_20210129-192901](https://user-images.githubusercontent.com/78209749/106270018-4ba29880-6268-11eb-88d0-92e2fe29cd7f.jpg)

**Comment by ketal178** [comment]
确认有此问题，会尽快修复
