### ISSUE TITLE
[功能需求] 屏蔽群作业类消息的通知

### ISSUE THREAD

**Issue by Womsxd** [ferredoxin/QNotified#486]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.4.8+

**为什么你认为需要此功能**

* 屏蔽某些人发的什么群友召唤术

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**
 屏蔽群作业类消息的通知
*  具体描述(如使用的场景，面临的问题)
例如屏蔽这种群作业类消息
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="60" templateID="123" action="web" brief="您已被移出本群" sourceMsgId="0" url="" flag="0" adverSign="0" multiMsgFlag="0"><item layout="1" advertiser_id="0" aid="0" /><item layout="1" advertiser_id="0" aid="0"><summary size="×FF0000">群友召唤术？</summary></item><source name="" icon="" action="" appid="-1" /></msg>`

**Comment by qwq233** [comment]
![image](https://user-images.githubusercontent.com/20317838/106294463-2c1c6780-628a-11eb-92e4-c7051c7e1167.png)
？已经屏蔽了

**Comment by Womsxd** [comment]
要开启什么？我开启文本化之后还能收到

**Comment by cinit** [comment]
@Womsxd 这个不是回执消息，这个是群作业...

**Comment by Womsxd** [comment]
能屏蔽吗？有时候莫名其妙的收到一条，挺烦人的

**Comment by Womsxd** [comment]
或者说我需要重新开个issues？(

**Comment by qwq233** [comment]
reopen吧直接 我改个title

**Comment by SekiBetu** [comment]
> ![image](https://user-images.githubusercontent.com/20317838/106294463-2c1c6780-628a-11eb-92e4-c7051c7e1167.png)
> ？已经屏蔽了

屏蔽指的不是发送，是接收

**Comment by qwq233** [comment]
现在还能发此类信息吗？
测试了下貌似发不出去了
就是指别人收不到那种

**Comment by singleNeuron** [comment]
@qwq233 在写了在写了

**Comment by lemonpearneko** [comment]
那我反问一下，有没有什么类似群友召唤术的强通知，急需，不要有病毒的那种，再不把通知弄到位我就要废了。

**Comment by singleNeuron** [comment]
@lemonpearneko 没有有病毒的群友召唤术，而且QN不支持发送此类干扰性卡片

**Comment by Womsxd** [comment]
> 现在还能发此类信息吗？
> 测试了下貌似发不出去了
> 就是指别人收不到那种

还能，只需要改成类似于这样子的就能发
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="60" templateID="123" action="web" brief="群友召唤术" sourceMsgId="0" url="https://qun.qq.com/homework/?channel=1014" flag="3" adverSign="0" multiMsgFlag="0"><item layout="2" advertiser_id="0" aid="0"><picture cover="http://p.qpic.cn/qqconadmin/0/8a0b8bcb4d512461014d527fc2520002/0" w="0" h="0" /><title>群友召唤术</title><summary>群友召唤术</summary></item><source name="班级作业" icon="" url="https://qun.qq.com/homework/?channel=1014" action="web" i_actionData="tencent" appid="101846357" /></msg>`

**Comment by Womsxd** [comment]
> 那我反问一下，有没有什么类似群友召唤术的强通知，急需，不要有病毒的那种，再不把通知弄到位我就要废了。

群作业(官方功能

**Comment by singleNeuron** [comment]
@Womsxd 建议去找QQ复读机，我们不想QN用户破坏普通用户体验

**Comment by Womsxd** [comment]
> @Womsxd 建议去找QQ复读机，我们不想QN用户破坏普通用户体验

我个人也不喜欢收到这种消息，平常也不会拿来发这种烦人的消息(测试是自己开群大小号测试的)

**Comment by taycke** [comment]
@Womsxd qn压根不能发这类型的消息，所以你还是去找复读机吧

**Comment by Womsxd** [comment]
> @Womsxd qn压根不能发这类型的消息，所以你还是去找复读机吧

不是要发，是希望屏蔽掉这类消息。。。

**Comment by Womsxd** [comment]
如果那条带xml的回复有不妥的话我会自己删掉的

**Comment by singleNeuron** [comment]
@Womsxd 那就请你自己删了吧

**Comment by Womsxd** [comment]
> @Womsxd 那就请你自己删了吧

好

**Comment by qwq233** [comment]
现在还能发此类信息吗？别人收的到那种

**Comment by Womsxd** [comment]
> 现在还能发此类信息吗？别人收的到那种

能，不过不是用QN的发送功能，要xml文本我可以提供（也可以直接拿群作业的改）

**Comment by lliioollcn** [comment]
#497
