### ISSUE TITLE
[功能需求] "消息+1"位置更正

### ISSUE THREAD

**Issue by tanyi20041109** [ferredoxin/QNotified#495]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ(play版)8.2.10

**为什么你认为需要此功能**

* 在开启"自己的消息和头像局左显示"后按钮位置会在消息前显示，以至于在聊天界面点击自己头像会复读消息

**联系到哪些已经存在的bug或者功能**

* "自己的消息和头像局左显示"

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
![Screenshot_2021-01-31-14-16-36-651.jpeg](https://user-images.githubusercontent.com/77902908/106376424-2af55280-63d0-11eb-83dc-f09ae622ac98.jpeg)

**Comment by NextAlone** [comment]
娱乐功能或许不会更新

**Comment by taycke** [comment]
@NextAlone

**Comment by qwq233** [comment]
@tanyi20041109 那就关掉"自己的消息和头像局左显示" 没看到功能描述么
