### ISSUE TITLE
插件半死不活

### ISSUE THREAD

**Issue by HatsuneMikuZero** [ferredoxin/QNotified#505]
环境:MIUI12.2.2 安卓11 太极阴QQ8.5.5
在更新完安卓11后qn在QQ设置里不显示，同时会使其他无关QQ插件不显示，取消qn即正常，功能方面:+1 一键撤回 一键20赞还在(我感觉的）/防撤回失效，各种美化失效
目测是qn不兼容MIUI12的安卓11版本，并且会影响到其他插件(如果qn生效)

**Comment by ketal178** [comment]
@HatsuneMikuZero 这边miui12.5+安卓11ok，有log吗

**Comment by qwq233** [comment]
@HatsuneMikuZero 请使用模板

**Comment by singleNeuron** [comment]
@HatsuneMikuZero 建议附带日志
