### ISSUE TITLE
[TIM3.3.5]存储重定向失效

### ISSUE THREAD

**Issue by xinghuan22** [ferredoxin/QNotified#510]
**QQ(TIM)版本/QQ(TIM) Version**
TIM3.3.5
* 

**模块版本/Module Version**
0.8.11.265.d3ba0e0
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
edxposed SandHook v4.5.7
* 

**问题的具体描述/Detailed Description of the Bug**
存储重定向开启后，经测试超过20mb大小的文件无法下载
*  具体描述(如复现BUG所需要的前提和必要操作等)
本人手机miui12.5
**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
@xinghuan22 我们这不是rikka的储存空间隔离
如果你指下载重定向的话由于Android11大改暂不考虑支持

**Comment by xinghuan22** [comment]
> @xinghuan22 我们这不是rikka的储存空间隔离
> 如果你指下载重定向的话由于Android11大改暂不考虑支持

谢谢
