### ISSUE TITLE
     太极阴湛卢6.1.2－5285  QQ8.5.5.5105  qn0.8.11.952af64QQ进去不显示

### ISSUE THREAD

**Issue by huanmoshi** [ferredoxin/QNotified#519]
![Screenshot_2021_0205_230733](https://user-images.githubusercontent.com/78606198/107051064-9bfe8680-6791-11eb-9e30-7716ee91be0f.jpg)
**QQ(TIM)版本/QQ(TIM)版本**n*模块版本/模块版本**n*n n*使用的框架名称与框架版本/X命题框架版本**n*n n**问题的具体描述/详细描述Bug*n*n具体描述(如复现bug所需要的前提和必要操作等)n n**此处贴你获取到的日志信息/日志此处**n<Details><汇总>展开查看</汇总><此处贴日志>n(此处贴日志)n</CODE></PRECT></Details>

**Comment by qwq233** [comment]
@huanmoshi 太极要几个小时才能适配 而且现在太极挂了

**Comment by qwq233** [comment]
@huanmoshi 自己找太极的人
