### ISSUE TITLE
[问题] [手动tag: question] 哪个QQ版本最适合QNotified

### ISSUE THREAD

**Issue by CCRcmcpe** [ferredoxin/QNotified#535]
**QQ(TIM)版本/QQ(TIM) Version**
8.4.5
* 

**模块版本/Module Version**
0.8.11.73159f7
* 

上个issue被光速close了，加错了tag，但是
**你们并没有“问题”的issue模板**

**Comment by CCRcmcpe** [comment]
看标题。

**Comment by qwq233** [comment]
我也不知道
