### ISSUE TITLE
[功能需求] 忽略网址安全警告

### ISSUE THREAD

**Issue by WEYI-Tech** [ferredoxin/QNotified#539]
**QQ(TIM)版本/QQ(TIM) Version**

855

**为什么你认为需要此功能**

直接打开网页，免去复制到浏览器打开步骤

**联系到哪些已经存在的bug或者功能**

无

**具体功能需要/Specific features required**

好友发来网址可以直接打开不管是否安全

**Comment by qwq233** [comment]
@WEYI-Tech 请使用"去你大爷的内置浏览器"
