### ISSUE TITLE
[8.5.5] QQAppInterface潜在问题

### ISSUE THREAD

**Issue by GoldenHuaji** [ferredoxin/QNotified#540]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5

**模块版本/Module Version = **

* 0.8.11.267.e1c4ec7

**使用的框架名称与框架版本/Xposed Framework and Framework Version = **

* Taichi Yin 6.4.0

**问题的具体描述/Detailed Description of the Bug**
我看了你们的 Utils.getQQAppInterface 的源码，这个方法逻辑错误， `AppRuntime` **有时候**不能被转为`QQAppInterface`，获取 QQAppInterface 的正确方法是 hook com.tencent.mobileqq.app.QQAppInterface.onCreate(Bundle)，然后使用一个变量(a)来储存 QQAppInterface 的值（`a = param.thisObject;`）。每次调用 getQQAppInterface  的时候，直接返回 a 的值就可以了。参见 [1](https://github.com/GoldenHuaji/QScript/blob/main/app/src/main/java/me/tsihen/qscript/MainHook.kt) 和 [2](https://github.com/GoldenHuaji/QScript/blob/main/app/src/main/java/me/tsihen/qscript/util/QQFields.kt)
*  具体描述(如复现BUG所需要的前提和必要操作等)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
日志我找不到了，但这是我自己开发模块时遇到的问题，这个 BUG 有概率触发
（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
扯句题外话 如果有直接引用qn的代码请保留qn的代码头xx

**Comment by singleNeuron** [comment]
please see https://github.com/ferredoxin/QNotified/pull/541

**Comment by cinit** [comment]
并不是所有的进程都存在QQAppInterface ，但是每一个进程都存在 AppRuntime 。在主进程里，AppRuntime等于QQAppInterface，在其他进程(如`:mini`) QQAppInterface不存在，但是存在继承AppRuntime的实例(如MiniAppInterface)，因此`getQQAppInterface()`这个函数应当仅在QQ主进程(`SyncUtils.isMainProcess()==true`)能被调用，其他进程(如 `:qzone`) 不应该调用这个函数，因为当前进程可能不具有QQAppInterface

**Comment by singleNeuron** [comment]
@cinit 那你怎么不在调用的时候检查进程，就算给方法加个注解标注只能在主进程调用也行啊。

**Comment by qwq233** [comment]
@cinit 所以说是ignore还是？
