### ISSUE TITLE
[QQ 8.2.7] 精简聊天长按菜单无效

### ISSUE THREAD

**Issue by xushet** [ferredoxin/QNotified#551]
**QQ(TIM)版本/QQ(TIM) Version**

* 版本 8.2.7

**模块版本/Module Version**

* 版本 0.8.11.504e8a9

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed版本 v0.5.4.0

**问题的具体描述/Detailed Description of the Bug**勾选或取消勾选“精简聊天长按菜单”的项目都无法生效

*  具体描述(如复现BUG所需要的前提和必要操作等)
![Screenshot_20210213-094305_QQ.png](https://user-images.githubusercontent.com/34502902/107838208-b662e080-6ddf-11eb-8811-9eef5f4e0beb.png)![Screenshot_20210213-094332_QQ.png](https://user-images.githubusercontent.com/34502902/107838211-b6fb7700-6ddf-11eb-9d08-0fcc64aecd67.png)

**Comment by ketal178** [comment]
@xushet 你好，暂未适配旧版本，马上就在旧版本屏蔽这个功能，让你看到这个功能是我的失误

**Comment by xushet** [comment]
> @xushet 你好，暂未适配旧版本，马上就在旧版本屏蔽这个功能，让你看到这个功能是我的失误

好吧

**Comment by ketal178** [comment]
@xushet 很久很久以后你就能用上这个功能
亦或者你更新QQ到850就能用了

**Comment by ketal178** [comment]
已修复
