### ISSUE TITLE
[QQ 8.2.7] 简洁模式圆头像会导致动态按钮不再直接打开QQ空间

### ISSUE THREAD

**Issue by xushet** [ferredoxin/QNotified#552]
**QQ(TIM)版本/QQ(TIM) Version**

* 版本 8.2.7

**模块版本/Module Version**

* 版本 0.8.11.504e8a9

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed版本 v0.5.4.0

**问题的具体描述/Detailed Description of the Bug**
在开启简洁模式的前提下，勾选“简洁模式圆头像”后，主界面底部的动态按钮不再是直接打开QQ空间而是打开动态页

*  具体描述(如复现BUG所需要的前提和必要操作等)
勾选“简洁模式圆头像”，切换到最近任务界面，划掉QQ，再次从启动器打开QQ，点击底部动态按钮
![Screenshot_20210212-170222_QQ.png](https://user-images.githubusercontent.com/34502902/107838387-a4357200-6de0-11eb-887e-d9d881c6f8dc.png)

**Comment by Neubulae** [comment]
这应该是某一次热更导致的？因为我记得是某一天开始突然就再也不能这样打开QQ空间了。

**Comment by NextAlone** [comment]
是否还有此问题

**Comment by xushet** [comment]
> 是否还有此问题

仍然存在

**Comment by singleNeuron** [comment]
第一，请使用新版简洁模式圆头像
第二，这种情况可能是由于QQ尚未完全启动，请在保持QQ打开的情况下等待一分钟再尝试打开空间
8.5.5测试正常
