### ISSUE TITLE
以图片方式打开闪照 存在掉帧问题

### ISSUE THREAD

**Issue by Wittoy** [ferredoxin/QNotified#56]
开启 以图片方式打开闪照 功能后，在聊天记录会出现掉帧现象，两台手机均复现此现象。

**Comment by cinit** [comment]
我自己也掉帧很严重...可是闪照上能优化的我都优化过了

**Comment by Wittoy** [comment]
或许可以参考QX模块的仅破解闪照时间限制，而不是以图片方式打开闪照（
