### ISSUE TITLE
[功能需求] QQ空间自动点赞功能(类似WX模块的朋友圈点赞)

### ISSUE THREAD

**Issue by PiPiTcc** [ferredoxin/QNotified#569]
**QQ(TIM)版本/QQ(TIM) Version**

*  855
**为什么你认为需要此功能**

* 应付需要点赞的好友(不点不行啊😂)

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by PiPiTcc** [comment]
我需要QQ空间自动点赞功能(类似WX模块的朋友圈点赞)

**Comment by JXSG-UP** [comment]
想要

**Comment by Cryolitia** [comment]
@JXSG-UP 没这好事
