### ISSUE TITLE
[QQ8.5.5] 开启隐藏字体特效后聊天气泡长按菜单中的"设为精华"消失

### ISSUE THREAD

**Issue by 3190** [ferredoxin/QNotified#582]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5.5105

**模块版本/Module Version**

* 0.8.11.08ec234

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Xposed 3.1.5

**问题的具体描述/Detailed Description of the Bug**

*  QQ净化中开启隐藏字体特效，聊天气泡长按菜单中的"设为精华"消失，但图片长按菜单的"设为精华"依然存在
* 关闭隐藏字体特效后恢复正常

**Comment by NextAlone** [comment]
是否还有此问题

**Comment by 3190** [comment]
模块已更新到0.8.14 问题仍然存在

**Comment by 3190** [comment]
> 是否还有此问题

模块已更新到0.8.14问题仍然存在
