### ISSUE TITLE
[QQ 8.2.7] 精简加号菜单无效

### ISSUE THREAD

**Issue by xushet** [ferredoxin/QNotified#593]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ版本 8.2.7

**模块版本/Module Version**

*QNotified 版本 0.8.11.b2be0a4

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 版本 v0.5.4.1（5250）

**问题的具体描述/Detailed Description of the Bug**![Screenshot_20210217-011653_QQ.png](https://user-images.githubusercontent.com/34502902/108098383-434aba00-70be-11eb-9333-87df4a31afad.png)
![Screenshot_20210217-011715_QQ.png](https://user-images.githubusercontent.com/34502902/108098457-59f11100-70be-11eb-9c8e-ff4fe0b12f7f.png)

*  具体描述(如复现BUG所需要的前提和必要操作等)
勾选去掉的菜单选项后，仍然出现在菜单里

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
@xushet 等我看下

**Comment by xushet** [comment]
系统版本 Android11类原生

**Comment by NextAlone** [comment]
> 系统版本 Android11类原生

试下，应该能用了
