### ISSUE TITLE
[功能需求] 功能搜索与更新记录

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#594]
**QQ(TIM)版本/QQ(TIM) Version**

* 855

**为什么你认为需要此功能**

* 每次更新都不知道更新了啥
* 有些功能找不到

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by cinit** [comment]
@XinYi-Media 要不要再来个新功能小红点?
