### ISSUE TITLE
[QQ 8.5.5] 简洁模式圆头像无法使用

### ISSUE THREAD

**Issue by CirnoSalt** [ferredoxin/QNotified#600]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ - 8.5.5

**模块版本/Module Version**

* 0.8.11.265

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极 - 6.1.2
* Android 10 (MIUI 12)

**问题的具体描述/Detailed Description of the Bug**

旧版简洁模式圆头像：初始化失败
新版简洁模式圆头像：在主界面中头像仍然为方形，并且伴随闪烁，聊天界面内头像无法载入。

尝试自行解决：
清除QQ和模块数据：无效
在主界面闪烁时静置等待十分钟：无效

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
02-17 16:05:29.420 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:29.420 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:29.420 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:29.420 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:29.420 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:29.420 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:29.420 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:29.420 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:29.420 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:29.420 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:29.421 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:29.421 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:29.421 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:29.421 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:29.421 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:29.421 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:29.421 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:29.426 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:29.426 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:29.426 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:29.426 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:29.426 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:29.426 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:29.426 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:29.427 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:29.427 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:29.427 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:29.427 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:29.427 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:29.427 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:29.427 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:29.427 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:29.427 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:29.428 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:29.428 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:29.428 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:29.428 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:29.428 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:29.428 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:29.428 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:29.428 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:29.428 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:29.428 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:29.715  4355  5052 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
02-17 16:05:29.719  4355  5052 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
02-17 16:05:29.722  4355  5052 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
02-17 16:05:29.724  4355  5052 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
02-17 16:05:29.777   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840352849000)
02-17 16:05:29.788   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840364166000)
02-17 16:05:30.143   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840719170000)
02-17 16:05:30.155   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840730272000)
02-17 16:05:30.166   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840741381000)
02-17 16:05:30.177   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840752486000)
02-17 16:05:30.188   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840763593000)
02-17 16:05:30.266   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840841444000)
02-17 16:05:30.277   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840852390000)
02-17 16:05:30.288   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840863487000)
02-17 16:05:30.299   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840874588000)
02-17 16:05:30.310   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840885689000)
02-17 16:05:30.321   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7840896971000)
02-17 16:05:31.345 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:31.345 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:31.345 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:31.345 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:31.346 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:31.346 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:31.346 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:31.346 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:31.346 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:31.346 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:31.346 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:31.346 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:31.352 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:31.352 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:31.352 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:31.352 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:31.352 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:31.352 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:31.352 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:31.352 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:31.352 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:31.352 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:31.353 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:31.353 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:31.353 27071 27233 W System.err: org.json.JSONException: End of input at character 0 of
02-17 16:05:31.353 27071 27233 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
02-17 16:05:31.353 27071 27233 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:101)
02-17 16:05:31.353 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:164)
02-17 16:05:31.354 27071 27233 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.vas.nicknamemessage.NickNameManager.a(P:37)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:156)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:131)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemPublicAccountChatMsgData.a(P:73)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.c(P:213)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.a(P:158)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.data.RecentItemChatMsgData.update(P:137)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.recent.ConversationDataFactory.a(P:130)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.c(P:6014)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.activity.home.Conversation.handleMessage(P:5729)
02-17 16:05:31.354 27071 27233 W System.err:    at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
02-17 16:05:31.354 27071 27233 W System.err:    at mqq.os.MqqHandler.dispatchMessage(P:99)
02-17 16:05:31.354 27071 27233 W System.err:    at mqq.os.MqqHandler$NativeHandler.dispatchMessage(P:326)
02-17 16:05:31.354 27071 27233 W System.err:    at android.os.Looper.loop(Looper.java:227)
02-17 16:05:31.354 27071 27233 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 16:05:31.354 27071 27233 E weishi855-WSRedDotPreloadManager: [preloadVideoCover] start
02-17 16:05:31.354 27071 27233 E weishi855-WSFeedsPreloadStrategy: [preloadRedDotData] mHadCleanPreCache:true
02-17 16:05:31.387   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7841962394000)
02-17 16:05:31.398   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7841973468000)
02-17 16:05:31.409   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7841984775000)
02-17 16:05:31.420   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7841995683000)
02-17 16:05:31.431   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842006793000)
02-17 16:05:31.520   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842095791000)
02-17 16:05:31.531   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842106898000)
02-17 16:05:31.542   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842117753000)
02-17 16:05:31.553   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842128862000)
02-17 16:05:31.564   943  1071 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 19260754811183489 (t=7842139977000)

（闪烁时一直循环类似的Error）
</code></pre></details>

**Comment by singleNeuron** [comment]
已重新测试并确认8.5.5无此问题，请尝试清除QQ缓存或全部数据
