### ISSUE TITLE
[功能需求] 简要概述需要的功能

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#602]
**QQ(TIM)版本/QQ(TIM) Version**

* 
![Screenshot_2021-02-17-23-12-08-765_com tencent mobileqq](https://user-images.githubusercontent.com/48674277/108224586-080bc200-7176-11eb-84b8-bbbdb02debec.jpg)

请问可以把资料页底下这个 送礼物 屏蔽掉吗？等了你好多个版本都没去掉这个😂

最近增加了好多屏蔽组件功能，好开心啊

**为什么你认为需要此功能**

* 碍眼，无意义功能

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by qwq233** [comment]
请正确使用模板
