### ISSUE TITLE
[功能需求] 屏蔽QQ浏览器相关内容

### ISSUE THREAD

**Issue by xushet** [ferredoxin/QNotified#604]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.2.7

**为什么你认为需要此功能**

* 在qq内点击网址链接默认用其内置浏览器打开，这个内置浏览器的体验非常差

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
在QQ聊天内点击链接会使用其内置浏览器， 希望能加个小选项，屏蔽内置浏览器打开或屏蔽用QQ浏览器打开按钮选项，因为有时误点就会二话不说开始下载QQ浏览器，非常恶心
![Screenshot_20210217-235720_QQ.png](https://user-images.githubusercontent.com/34502902/108230714-05ac6680-717c-11eb-8f98-b08c97fd2404.png)

**Comment by qwq233** [comment]
@xushet 请使用"去你大爷的内置浏览器"

**Comment by NextAlone** [comment]
@xushet 好需求。
