### ISSUE TITLE
[QQ8.5+，qn0.8.11.4dcb5cc(1613573454) ]在开启简洁模式后底部聊天大部分功能按钮消失

### ISSUE THREAD

**Issue by ZONGQUAN-HU** [ferredoxin/QNotified#608]
- [ ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
qq8.5+
* 

**模块版本/Module Version**
0.8.11.4dcb5cc(1613573454)
0.8.11.8ecb248(1613580388)
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 

**问题的具体描述/Detailed Description of the Bug**
2021年2月17-18日Cl自动构建版本中出现QQ底部聊天大部分按钮消失的问题，我之前安装过于2月15发布的0.8.11.462ba5e(1613367793)版本并没有发现按钮消失，然而与28日凌晨更新Cl版本后（先后安装过0.8.11.4dcb5cc(1613573454)和0.8.11.8ecb248(1613580388)），都发现了底部大部分菜单消失，在开启了QQ简洁模式时，底部按钮会再次简化，导致需要正常使用或者常用的按钮也被删除（如红包），如果新版本加入了有关底部按钮的删除代码，请考虑简洁模式下按钮问题重新修复，谢谢。
*  具体描述(如复现BUG所需要的前提和必要操作等)
![Screenshot_20210218-004956_QQ](https://user-images.githubusercontent.com/36360150/108242683-2aa6d680-7188-11eb-8805-6c95247951ad.png)
![Screenshot_20210218-010828_Telegraph](https://user-images.githubusercontent.com/36360150/108242716-32ff1180-7188-11eb-9dae-acf634a490fb.png)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
@ZONGQUAN-HU 请前往 精简加号菜单 勾选所需要功能

**Comment by qwq233** [comment]
不支持qq5+版本

**Comment by ZONGQUAN-HU** [comment]
> 不支持qq5.5+版本

在相同的QQ版本，使用更新过的qn，难道不是qn的问题吗？

**Comment by ZONGQUAN-HU** [comment]
一句不支持就完了？不支持我用这么多天？

**Comment by NextAlone** [comment]
@ZONGQUAN-HU 请确认版本号信息

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU 不支持，不支持，不支持
重要的问题说三遍。

**Comment by ZONGQUAN-HU** [comment]
不支持不是借口好吧，你们看看问题所在。。。不是跟你说版本问题，明明你们的qn有这样的改动

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU QQ5.5+是什么远古版本？

**Comment by ketal178** [comment]
> 一句不支持就完了？不支持我用这么多天？

你确定是5.5？？？？
这个版本有简洁模式？

**Comment by NextAlone** [comment]
> 不支持不是借口好吧，你们看看问题所在。。。不是跟你说版本问题，明明你们的qn有这样的改动

正在问您 QQ 5.5+ 是什么rz版本呢

**Comment by ZONGQUAN-HU** [comment]
妈的，打错了，是8.5+

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU 8.5.0还是8.5.5？

**Comment by ketal178** [comment]
> 妈的，打错了，是8.5+

8.5+没问题

**Comment by NextAlone** [comment]
> 妈的，打错了，是8.5+

使用支持不是借口好吧，你看看问题所在。。。不是跟你说qn问题，明明你qq有这样的改动

**Comment by singleNeuron** [comment]
@NextAlone 草我一口水喷了

**Comment by ketal178** [comment]
![> 妈的，打错了，是8.5+

![image](https://user-images.githubusercontent.com/41381927/108243944-99386400-7189-11eb-9c7b-f99c66ce3df6.png)

**Comment by ketal178** [comment]
> > 妈的，打错了，是8.5+
> 
> ![image](https://user-images.githubusercontent.com/41381927/108243944-99386400-7189-11eb-9c7b-f99c66ce3df6.png)

自己去设置

**Comment by ZONGQUAN-HU** [comment]
> @ZONGQUAN-HU 8.5.0还是8.5.5？

这两个版本我都试过，8.5.5和8.5.0都试过

**Comment by ketal178** [comment]
> > @ZONGQUAN-HU 8.5.0还是8.5.5？
> 
> 这两个版本我都试过，8.5.5和8.5.0都试过

![Uploading image.png…]()

**Comment by NextAlone** [comment]
@ZONGQUAN-HU 看下 精简加号菜单 里面勾选情况

**Comment by ZONGQUAN-HU** [comment]
> > > 妈的，打错了，是8.5+
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41381927/108243944-99386400-7189-11eb-9c7b-f99c66ce3df6.png)
> 
> 自己去设置

新功能？这默认设置有点邪门啊

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU 我也觉得他很邪门，所以我自己都没敢更新QN

**Comment by ZONGQUAN-HU** [comment]
> @ZONGQUAN-HU 我也觉得他很邪门，所以我自己都没敢更新QN

换回github版本了，不敢更电报里面的

**Comment by ZONGQUAN-HU** [comment]
好了，没事了

**Comment by qwq233** [comment]
@ZONGQUAN-HU 不喜欢ci版的过量bug就别更新ci版

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU 这就对了

**Comment by ZONGQUAN-HU** [comment]
> @ZONGQUAN-HU 不喜欢ci版的过量bug就别更新ci版

并不是不喜欢，这是不是bug也要到github问问大家才知道对吧

**Comment by singleNeuron** [comment]
@ZONGQUAN-HU 确实是我们开发组写的逻辑有问题

**Comment by ZONGQUAN-HU** [comment]
> @ZONGQUAN-HU 确实是我们开发组写的逻辑有问题

知道了
