### ISSUE TITLE
[Bug]QQ8.3.0 QN影响QQ规避系统长截图功能

### ISSUE THREAD

**Issue by ghost** [ferredoxin/QNotified#61]
我的QQ版本是8.3.0（这个其实不重要，因为我在使用8.2.x版本的时候也存在这个问题）
模块版本为0.7.1,beta
当系统截图完毕后,qq会弹出一个分享截图的悬浮窗,而当进入长截图模式的时候,该悬浮窗会消失,防止影响长截图效果
而当开启qn模块之后,QQ将不再规避系统长截图
经测试,当开启QN模块时,无论是否开启任何功能,QQ都将不再规避,而当QN模块被关闭的时候,长截图工作正常。
![Screenshot_2020-03-30-15-21-20-045_com tencent mobileqq](https://user-images.githubusercontent.com/60849359/77891706-f393b200-72a3-11ea-8aa0-fcd330a4d115.png)

**Comment by KarlcxChina** [comment]
系统版本为miui11最新开发版,安卓10

**Comment by qwq233** [comment]
现在还有没有该情况
