### ISSUE TITLE
[功能需求] 发送卡片支持发送红包消息

### ISSUE THREAD

**Issue by LeviMarvin** [ferredoxin/QNotified#619]
**TIM: 3.3.5**

* 

**禁止引流但应该不禁止逗朋友吧...一杆子打死一堆有点过有绝对了**

* 

**Omega功能**

* 

**发送卡片支持发送红包消息**

*  不管是不是引流的红包都显示"禁止引流"无法发送

**Comment by singleNeuron** [comment]
@LeviMarvin 我怎么知道你是引流还是逗朋友

**Comment by qwq233** [comment]
不考虑

**Comment by NextAlone** [comment]
@LeviMarvin 建议逗复读机呢
