### ISSUE TITLE
[功能需求] QQ相册扫码登录拒绝访问

### ISSUE THREAD

**Issue by BingxuanLu** [ferredoxin/QNotified#621]
**QQ(TIM)版本/QQ(TIM) Version**
QQ(8.5.5)
* 

**为什么你认为需要此功能**
由于只有一台手机所以只能用相册扫码登录
* 

**联系到哪些已经存在的bug或者功能**
无
* 

**具体功能需要/Specific features required**
解决QQ相册扫码登录后提示二维码失效（该登录被拒绝访问）的现象
*  具体描述(如使用的场景，面临的问题
一些网站要求QQ扫码登录，截图后调用QQ扫一扫相册选择图片后能够扫码并且登录成功

**Comment by xvhuan** [comment]
qq改机制了，只能摄像头扫码才能登录。跟模块有个卵关系。

**Comment by xvhuan** [comment]
只有一个手机那就用两块镜子，照样可以扫
