### ISSUE TITLE
[功能需求] 接龙红包搜索工具

### ISSUE THREAD

**Issue by XinYi-Media** [ferredoxin/QNotified#632]
**QQ(TIM)版本/QQ(TIM) Version**

* 855

**为什么你认为需要此功能**

* 譬如长按红包可以搜索相关成语诗句单词

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by cinit** [comment]
建议使用QQ复读机

**Comment by huajijam** [comment]
需要构建接龙api及词库，无算力实现，另外，请查看readme.md
