### ISSUE TITLE
[功能需求] 希望自动续火支持群聊

### ISSUE THREAD

**Issue by a6513375** [ferredoxin/QNotified#633]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5

**为什么你认为需要此功能**

* 方便群聊续火

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  像私聊一样 每天自动向群聊发送消息续火

**Comment by NextAlone** [comment]
@a6513375 好

**Comment by cinit** [comment]
@a6513375 感觉这个功能很容易被abuse，比如说定时群发广告消息，或者群发类似 老婆+ ,  扩列+ 之类无意义内容

**Comment by a6513375** [comment]
> @a6513375 感觉这个功能很容易被abuse，比如说定时群发广告消息，或者群发类似 老婆+ , 扩列+ 之类无意义内容

那可以设置成群聊续火不允许更改消息内容？

**Comment by huajijam** [comment]
@a6513375 有可能会被通过改字符串等形式更改

**Comment by a6513375** [comment]
> @a6513375 感觉这个功能很容易被abuse，比如说定时群发广告消息，或者群发类似 老婆+ , 扩列+ 之类无意义内容

那可以试试改成群聊续火不支持修改消息内容？

**Comment by a6513375** [comment]
> @a6513375 有可能会被通过改字符串等形式更改

okk

**Comment by china-mochen** [comment]
OK

**Comment by china-mochen** [comment]
建议:群聊续火和好友续火一样,不支持更改内容

**Comment by NextAlone** [comment]
> @a6513375 感觉这个功能很容易被abuse，比如说定时群发广告消息，或者群发类似 老婆+ , 扩列+ 之类无意义内容

所以这个功能要么

**Comment by huajijam** [comment]
我觉得都行

**Comment by cinit** [comment]
@huajijam 行，那就鸽了

**Comment by huajijam** [comment]
@cinit 好耶

**Comment by a6513375** [comment]
> @huajijam 行，那就鸽了

孬耶

**Comment by NextAlone** [comment]
@a6513375 要不打开挂着吧。等啥时候想到了好的措施再写

**Comment by Zhuoershang** [comment]
需求:在指定群进行每日签到！
为规避定时发送固定广告的情形！希望可以限制群续火的数量，或者续火内容字符数量！每个账号至多可以对5个群设置续火！

**Comment by Zhuoershang** [comment]
@a6513375

**Comment by a6513375** [comment]
> 需求:在指定群进行每日签到！
> 为规避定时发送固定广告的情形！希望可以限制群续火的数量，或者续火内容字符数量！每个账号至多可以对5个群设置续火！

感觉都可

**Comment by 835649333** [comment]
一样希望加入群续火
