### ISSUE TITLE
[功能需求] 查找聊天记录页面支持截图或者更多功能

### ISSUE THREAD

**Issue by xuanmi666** [ferredoxin/QNotified#635]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.55

**为什么你认为需要此功能**

* 使用QQ内置的聊天记录截图功能可以方便选择性的截取消息，当前该功能只有在聊天页面长按消息气泡才能使用，而如果在 查找聊天记录 页面寻找过往聊天记录中长按消息气泡则没有这个选项

* 同时在 查找聊天记录 页面长按消息气泡只有复制，转发，收藏，删除四项，除截图外，还能都够添加原有的回复，多选等选项（如果在聊天页面一直往上翻记录的话是可以的，但对于时间久远的就很麻烦，一直滑?）

**Comment by ketal178** [comment]
难度不是一般的大
