### ISSUE TITLE
QQ8.5.5简洁模式圆头像不生效

### ISSUE THREAD

**Issue by KongKongV** [ferredoxin/QNotified#637]
- [ 是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5.5105

**模块版本/Module Version**

* 0.8.12.9d8b8e8

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Lsposed V0.5.4.1

**问题的具体描述/Detailed Description of the Bug**

*  设备：Redmi 9
* 系统：PixelExperience11
* 安卓版本：Android 11
* 使用简洁模式圆头像后无论进行任何操作都不会生效，并且开启之后滑动聊天列表时头像会反复进行刷新（变灰色）

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by huajijam** [comment]
#600
