### ISSUE TITLE
加号简化问题

### ISSUE THREAD

**Issue by nightglow155** [ferredoxin/QNotified#650]
开启加号简化后，无论开了多少，点加号全为空，而且界面可以划出屏幕外同时返回键无效
![Screenshot_20210223-204828](https://user-images.githubusercontent.com/52414613/108845531-81912d80-7618-11eb-87c6-0605f84b1b5b.png)

**Comment by NextAlone** [comment]
@nightglow155 等下修复

**Comment by NextAlone** [comment]
@nightglow155 已修复。等ci
