### ISSUE TITLE
[QQ8.5.5.5105] 同时开启+1和显示消息时间功能后+1图标位置不对

### ISSUE THREAD

**Issue by zhanghua000** [ferredoxin/QNotified#664]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5.5105

**模块版本/Module Version**

* 0.8.12.34951ea

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 应用转生6.4.6

**问题的具体描述/Detailed Description of the Bug**
同时开启复“+1”和“消息显示发送者QQ号和时间”两个功能后+1图标位置偏下
*  具体描述(如复现BUG所需要的前提和必要操作等)  
1. 同时开启复“+1”和“消息显示发送者QQ号和时间”两个功能
2. 发送任何一个聊天信息（单行的文本信息最明显）
3. 截图如下：
![Screenshot_20210226_081051_com tencent mobileqq](https://user-images.githubusercontent.com/17194552/109245239-13688880-781b-11eb-8245-e0c0ee4abab5.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by ketal178** [comment]
这个位置就是消息高度的一半，符合预期

**Comment by NextAlone** [comment]
@zhanghua000 这个位置就是消息高度的一半，符合预期

**Comment by zhanghua000** [comment]
啊这。。。抱歉，我以为设计的目标位置是文本消息的后面来着
