### ISSUE TITLE
[功能需求]去除龙王提醒

### ISSUE THREAD

**Issue by akinonatsu** [ferredoxin/QNotified#67]
不知道是否考虑加入此功能
![Screenshot_20200412-151357_QQ](https://user-images.githubusercontent.com/57977138/79064688-8dfce800-7cdd-11ea-872f-d89f7f08a279.jpg)

**Comment by ketal178** [comment]
可在设置->隐私->群互动标识及幸运字符设置 
内关闭 
![J61 _BT@ST 8 BUR}7(9`3X](https://user-images.githubusercontent.com/41381927/106344995-ff973880-62e7-11eb-8ada-8fdcdb05ead5.jpg)
