### ISSUE TITLE
[功能需求] 自动续火增加可选消息

### ISSUE THREAD

**Issue by Liangyu-G** [ferredoxin/QNotified#672]
**QQ(TIM)版本/QQ(TIM) Version**

* ALL Version

**为什么你认为需要此功能**

* 每天因为忙碌的生活不得不让机器代替人工与好友联络感情。

**联系到哪些已经存在的bug或者功能**

* 自动续火

**具体功能需要/Specific features required**
自动续火功能建议增加早安、早、晚安、安之类的可选消息。
*  具体描述(如使用的场景，面临的问题)
由于目前的续火功能仅能发送“[续火]”这样的消息，如果只是为了续火还聊天做什么，好友见了这样的问候只会觉得尴尬，仿佛要决裂一般，大家都是有血有肉的人，应该发阳间的消息，不当毫无感情的续火机器，所以想要更改续火内容，增加可选项。

**Comment by qwq233** [comment]
@Liangyu-G 请修改标题

**Comment by taycke** [comment]
@Liangyu-G 为什么需要这理由秀啊

**Comment by taycke** [comment]
@Liangyu-G 一天就发一次是如何联络感情的

**Comment by Liangyu-G** [comment]
> @Liangyu-G 一天就发一次是如何联络感情的

就你屁事多，我又不是只和你续火👎🏻
