### ISSUE TITLE
[QQ8.5.5] 开启隐藏会员红名后左上角多出一个返回箭头

### ISSUE THREAD

**Issue by River2017CN** [ferredoxin/QNotified#683]
- [是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
QQ8.5.5(1630)
* 

**模块版本/Module Version**
0.8.13.3eccf51
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极 曳影·7.0.0.02111627-5592
* 

**问题的具体描述/Detailed Description of the Bug**
开启了“QQ净化[WIP]”中的“聊天-隐藏会员红名”之后私聊界面左上角会多出一个返回箭头
![IMG_20210228_111834.jpg](https://user-images.githubusercontent.com/78515395/109406774-c9b4a500-79b6-11eb-9a51-81a9f252cef2.jpg)
*  具体描述(如复现BUG所需要的前提和必要操作等)
开启QQ净化-聊天-隐藏会员红名后所有私聊左上角会多出一个返回箭头，群聊不受影响，关闭后消失。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
qq默认主题还是

**Comment by River2017CN** [comment]
> qq默认主题还是

默认模式下的默认主题

**Comment by NextAlone** [comment]
> > qq默认主题还是
> 
> 默认模式下的默认主题

最新版本是否还存在此问题

**Comment by River2017CN** [comment]
> > > qq默认主题还是
> > 
> > 默认模式下的默认主题
> 
> 最新版本是否还存在此问题

没了，感谢大佬🙏🏻
