### ISSUE TITLE
[QQ8.5.5] 更新最新版后点击检查更新检查到旧版

### ISSUE THREAD

**Issue by xiaodou233333** [ferredoxin/QNotified#684]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
8.5.5(1630)
* 

**模块版本/Module Version**
0.8.13.c1c8cba

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极 曳影·7.0.0.02111627-5592
* 

**问题的具体描述/Detailed Description of the Bug**
Qn版本更新至0.8.12.9d8b8e8之后，点击检查更新都会检查到0.8.12.9d8b8e8
![image](https://user-images.githubusercontent.com/61956441/109407851-316eee00-79bf-11eb-839b-e99e6f2ccfc9.png)
![QQ图片20210228122004](https://user-images.githubusercontent.com/61956441/109407862-51061680-79bf-11eb-89aa-15bdcae46abf.png)
![QQ图片20210228122326](https://user-images.githubusercontent.com/61956441/109407917-ce318b80-79bf-11eb-874c-a7e24b0e7221.png)

*  具体描述(如复现BUG所需要的前提和必要操作等)
更新到0.8.12.9d8b8e8之后版本就会了
**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by ketal178** [comment]
你好，软件内的检查更新渠道为稳定版，只会获取稳定版，你用的是ci版，

**Comment by xiaodou233333** [comment]
> 你好，软件内的检查更新渠道为稳定版，只会获取稳定版，你用的是ci版，

那如何让他获取最新版 因为之前都是获取最新版本的

**Comment by NextAlone** [comment]
@xiaodou233333 tg

**Comment by NextAlone** [comment]
@xiaodou233333 https://t.me/QNotified_CI
