### ISSUE TITLE
[Bug]QQ8.3.0 QQ启动黑屏，卡顿，偶尔闪退

### ISSUE THREAD

**Issue by Yodamt** [ferredoxin/QNotified#69]
miui11安卓9，8.3.0手机QQ，6.1.8Taichi环境，使用0.7.1beta。
开启的功能有
语音转发，+1，隐藏小程序，隐藏送礼，禁止自动@，禁止打开收礼界面，强制使用默认气泡，签到文本化，转发查看头像资料卡，防撤回，图片形式打开表情。
会出现启动QQ无反应卡顿，黑屏只能强制结束的情况，经常复现

**Comment by Yodamt** [comment]
还有一个问题是点击图片的时候偶尔会卡住弹出QQ无响应，但是确定后又可以流畅的用了

**Comment by lliioollcn** [comment]
请问现在还有这个问题吗
