### ISSUE TITLE
[功能需求] 请求完善自动勾选原图功能

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#690]
**QQ(TIM)版本/QQ(TIM) Version**

8.5.5(1630)

**为什么你认为需要此功能**

目前通过相册选择图片的时候，已经实现自动勾选原图，但是通过点击+号出现预览图的位置点击进入还是无法自动勾选原图
方便，一步到位

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

![IMG_20210301_042329](https://user-images.githubusercontent.com/48674277/109432480-5d818200-7a46-11eb-8e8e-bc95e7f57b2f.jpg)
![IMG_20210301_042404](https://user-images.githubusercontent.com/48674277/109432488-63776300-7a46-11eb-9dd3-32aad3dbc6d3.jpg)

如图所示位置入口选择图片仍然无法自动勾选原图，此处的使用率应该更高

**Comment by NextAlone** [comment]
了解

**Comment by NextAlone** [comment]
已更新
