### ISSUE TITLE
QQ版本8.5.5(1630)今天小程序广告失效，之前一直都可

### ISSUE THREAD

**Issue by a370263995** [ferredoxin/QNotified#694]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5(1630)

**模块版本/Module Version**

* 0.8.12.5d9bfd1

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

今天之前，小程序广告点击左上角即可跳过并成功领取奖励，今天操作的时候，点击关闭广告后，无法跳过，求作者看一哈

**Comment by a370263995** [comment]
有大佬看看不？

**Comment by ketal178** [comment]
@a370263995 都开学了，建议你pr

**Comment by a370263995** [comment]
> @a370263995 都开学了，建议你pr

啥是pr?

**Comment by ketal178** [comment]
@a370263995 adobe那个pr

**Comment by Thiasap** [comment]
8.5.5测试没问题，用的最新的0.8.13，你更新之后试一试，要手动关闭广告

**Comment by qwq233** [comment]
未改标题 模块版本过老
