### ISSUE TITLE
[QQ8.5.5] 修改@界面排序无效

### ISSUE THREAD

**Issue by 3190** [ferredoxin/QNotified#710]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5.5105

**模块版本/Module Version**

* 0.8.14.8d01b29

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Xposed 3.1.5

**问题的具体描述/Detailed Description of the Bug**

*  如题，开启"修改@界面排序"和没开一样

**Comment by ketal178** [comment]
这里测试OK![Screenshot_2021-03-06-18-51-51-684_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/110204273-24fe0000-7ead-11eb-8fd8-1a2454032b9f.jpg)![Screenshot_2021-03-06-18-52-00-753_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/110204274-27605a00-7ead-11eb-8692-41e475e205f9.jpg)
