### ISSUE TITLE
[功能需求] 默认模式隐藏群聊头衔

### ISSUE THREAD

**Issue by CirnoSalt** [ferredoxin/QNotified#713]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5

**为什么你认为需要此功能**

* 部分群的自定义头衔过长或过于花哨，影响美观。

**联系到哪些已经存在的bug或者功能**

* QQ净化>群聊页未开放功能。
* 虽然简洁模式可隐藏，但简洁模式+新版圆头像开启后不稳定，在进入群聊瞬间大概率发生fc。

**具体功能需要/Specific features required**

*  隐藏默认模式群聊中的群等级头衔/自定义头衔，同时保留群主与管理员的头衔显示。

**Comment by NextAlone** [comment]
区分管理太麻烦了，先一次性都干掉吧
