### ISSUE TITLE
[功能需求] 精简底栏看点

### ISSUE THREAD

**Issue by duzhaokun123** [ferredoxin/QNotified#715]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5

**为什么你认为需要此功能**

* 不看看点，占底栏位置

**联系到哪些已经存在的bug或者功能**

* 精简底栏动态

**具体功能需要/Specific features required**

*  提供一个开关以设置是否经精简底栏看点

**Comment by ketal178** [comment]
@duzhaokun123 QQ设置自己关

**Comment by NextAlone** [comment]
@duzhaokun123 设置里有。自己找。
