### ISSUE TITLE
[QQ8.5.5] 自动续火时间错误

### ISSUE THREAD

**Issue by Star-KWL** [ferredoxin/QNotified#716]
- [ 是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5

**模块版本/Module Version**

* 0.8.14.8d01b29

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed v1.1.0

**问题的具体描述/Detailed Description of the Bug**

自动续火QQ和QQ分身设同样的时间（00:00:01），QQ会在中午12.01分续火，QQ分身会在凌晨00.01分续火

*  具体描述(如复现BUG所需要的前提和必要操作等)
开启自动续火功能并设置时间后会产生12小时差，系统时间格式为24小时制
**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
更改一下别的时间再测试一下可以吗，这边没有分身

**Comment by Star-KWL** [comment]
> 更改一下别的时间再测试一下可以吗，这边没有分身

之前用的默认时间00:00:05也是这样，就是因为这样才改成01

**Comment by caoli5288** [comment]
自动续火的入口在哪我硬是没找到

**Comment by lightoo1122** [comment]
自动续火每天都跟设定的时间有误差，少则10分钟多则N个小时

**Comment by taycke** [comment]
@lightoo1122 几分钟是正常情况，这玩意之前是十分钟检测一次
