### ISSUE TITLE
希望可以屏蔽掉qq空间里背景图上的呼吸状推广图标

### ISSUE THREAD

**Issue by WD411** [ferredoxin/QNotified#738]
QQ空间手机版从很早就开始存在这种推广图标，它一般出现在自己头像的上方，并且呈呼吸状夸张的改变大小来吸引用户注意，点进去之后往往是一个折扣购买的页面，希望可以把这个小图标去掉。
还有部分情况下空间顶部也会出现动图横幅形式的广告（往往是自家的推广），动态详情、查看图片滑动到最后一张也会有其他厂商的广告，希望可以一并屏蔽掉
![IMG_20210313_143005](https://user-images.githubusercontent.com/79956396/111023896-980bf700-8416-11eb-8a38-5cf0a877c1f4.jpg)

**Comment by qwq233** [comment]
使用模板
