### ISSUE TITLE
8.5.5 文件重定向问题

### ISSUE THREAD

**Issue by Ynkcc** [ferredoxin/QNotified#745]
- [√ ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5

**模块版本/Module Version**

* 0.8.14.8d01b29

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsp 1.2.2

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
启用重定向接收文件的目录功能后，来自电脑发送的文件会下载失败。
**此处贴你获取到的日志信息/Log here**
未抓取日志(未找到简洁的入口)
<details><summary>展开查看</summary><pre><code>
如已修复请忽略

</code></pre></details>

**Comment by qwq233** [comment]
安卓11？
