### ISSUE TITLE
关于 +1 复读功能的建议

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#746]
开启+1功能后，聊天界面显得非常凌乱，而且容易误触
![Screenshot_2021-03-15-03-06-07-769_com tencent mobileqq](https://user-images.githubusercontent.com/48674277/111081405-2a5aea80-853e-11eb-9ed0-85d4615a6f62.jpg)

建议在 长按气泡菜单处，增加+1选项

![Screenshot_2021-03-15-03-06-12-030_com tencent mobileqq](https://user-images.githubusercontent.com/48674277/111081413-30e96200-853e-11eb-88aa-2595618b4c1b.jpg)

开启+1功能后，聊天界面显得非常凌乱，而且容易误触
建议在 长按气泡菜单处，增加+1选项

**Comment by qwq233** [comment]
建议不用
