### ISSUE TITLE
[QQ8.5.5] 消息显示@对象不完整

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#756]
- [ ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

*8.5.5

**模块版本/Module Version**

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

0.8.15.5c260b2

**问题的具体描述/Detailed Description of the Bug**
如图所示
*  具体描述(如复现BUG所需要的前提和必要操作等)
![IMG_20210317_215733](https://user-images.githubusercontent.com/48674277/111479290-ca498b80-876b-11eb-89d7-a2ee641194f1.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by lliioollcn** [comment]
请问是否还有此问题？
