### ISSUE TITLE
[QQ 8.5.5] QQ净化失效

### ISSUE THREAD

**Issue by River2017CN** [ferredoxin/QNotified#759]
- [是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
QQ 8.5.5(1630)

**模块版本/Module Version**
0.8.15.5b93400

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极阴 曳影·7.0.0.02111627-5762

**问题的具体描述/Detailed Description of the Bug**
大概在更新0.8.15.df9f24d版本后QQ净化的侧滑净化完全失效
*  具体描述(如复现BUG所需要的前提和必要操作等)
更新0.8.15.df9f24d版本后（大概，也有可能是早1-2个版本）QQ净化-侧滑完全失效
**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

无日志

</code></pre></details>
![Screenshot_20210319_222935.jpg](https://user-images.githubusercontent.com/78515395/111797027-b9cc1900-8903-11eb-872a-d2c2f5844423.jpg)![IMG_20210319_222949.jpg](https://user-images.githubusercontent.com/78515395/111797054-bf296380-8903-11eb-98bc-1283bd3fe510.jpg)![IMG_20210319_223006_Mosaic_22_30_16.jpg](https://user-images.githubusercontent.com/78515395/111797076-c5b7db00-8903-11eb-80ba-3cdf0ee04951.jpg)

**Comment by ketal178** [comment]
是不是QQ更新到了860

**Comment by River2017CN** [comment]
> 是不是QQ更新到了860

![IMG_20210319_224322.jpg](https://user-images.githubusercontent.com/78515395/111797945-8dfd6300-8904-11eb-8437-4c05b49503a8.jpg)
没有

**Comment by River2017CN** [comment]
在新版已经修复，感谢大佬们![IMG_20210327_002439.jpg](https://user-images.githubusercontent.com/78515395/112662598-d5e73180-8e92-11eb-9f07-b7589e995f62.jpg)
