### ISSUE TITLE
[功能需求] QQ厘米秀禁止自动弹出

### ISSUE THREAD

**Issue by 835649333** [ferredoxin/QNotified#762]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 

**联系到哪些已经存在的bug或者功能**

* 
**具体功能需要/Specific features required**
希望能加个设置禁止QQ厘米秀自动弹出动作或者聊天的时候弹出！双击关闭后也会弹出！
*  具体描述(如使用的场景，面临的问题)
* 聊天的时候发一些暧昧文字或者别的内容QQ厘米秀会自动弹出动作！
![IMG_20210320_073059](https://user-images.githubusercontent.com/61548712/111851537-9001fa80-88e1-11eb-8612-cd4e9a9171d7.jpg)

**Comment by NextAlone** [comment]
如无CMShow需求，可直接关闭CMShow
