### ISSUE TITLE
[功能需求] 复读功能优化

### ISSUE THREAD

**Issue by Liangyu-G** [ferredoxin/QNotified#770]
**QQ(TIM)版本/QQ(TIM) Version**

* ALL

**为什么你认为需要此功能**

* 方便，好看

**联系到哪些已经存在的bug或者功能**

* 复读功能

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
把复读按钮放进聊天界面长按消息所弹出的菜单里面（类似于微X的重复发送），使QQ界面变得与正常界面相同。

**Comment by NextAlone** [comment]
@Liangyu-G 好

**Comment by qwq233** [comment]
那不如直接复制粘贴

**Comment by ketal178** [comment]
污染 剪贴板 坏

**Comment by qwq233** [comment]
@ketal178 个人觉得麻烦了 长按菜单+1跟脱裤子放屁没啥区别

**Comment by ketal178** [comment]
> @ketal178 个人觉得麻烦了 长按菜单+1跟脱裤子放屁没啥区别

有的东西没法复制，只能转发

**Comment by ketal178** [comment]
不如长按转发代替复读

**Comment by soulpursuit** [comment]
> 不如长按转发代替复读

操作一步 和 操作很多步的区别！

**Comment by ketal178** [comment]
> > 不如长按转发代替复读
> 
> 操作一步 和 操作很多步的区别！

坏坏坏，这个复读按钮以后会干很多事，不太可能动 的
源码在这，你可以自己改，我不会改
