### ISSUE TITLE
[功能需求] 系统调起的分享页面加入”发送给我的iPad“

### ISSUE THREAD

**Issue by cyp0633** [ferredoxin/QNotified#771]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.6.0

**为什么你认为需要此功能**

* 系统分享页面中，选择QQ分享，只能分享给联系人和电脑，唯独没有iPad，很不方便。
* 尤其是对于上课时Android手机拍PPT传到iPad上的场景，打开QQ、选择iPad再发送，比从系统相机发送效率低很多。

**联系到哪些已经存在的bug或者功能**

* 系统调起QQ分享

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
* 场景请参照上方”为什么你认为需要此功能“
* 使用系统分享调起QQ时，可以选择发送给iPad。
* 比较需要图片类型的分享给iPad，如果能够顺手做其他文件类型的分享就更好了，十分感谢！

**Comment by ketal178** [comment]
大概无法实现？

**Comment by ketal178** [comment]
![image](https://user-images.githubusercontent.com/41381927/113653287-2008b800-96c8-11eb-9f83-2f6a9b20d78f.png)
图标用qn的?@cyp0633
