### ISSUE TITLE
[QQ8.6.0] 群聊+号有个红点

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#773]
- [ ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

*8.6.0

**模块版本/Module Version**
 
af9fb88
 
**使用的框架名称与框架版本/Xposed Framework and Framework Version**

lap 5501

**问题的具体描述/Detailed Description of the Bug**

群聊+号有个红点，估计是隐藏了的按钮有红点，所以+号上也有红点

*  具体描述(如复现BUG所需要的前提和必要操作等)
![Screenshot_2021-03-23-00-26-02-391_com tencent mobileqq](https://user-images.githubusercontent.com/48674277/112024446-2ac33900-8b6f-11eb-8888-0c40f07bf261.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
是否还有此问题

**Comment by soulpursuit** [comment]
> 是否还有此问题

没有了，但是现在不敢用了😂😂😂

请问最近有没有研究一下防封方面的工作

**Comment by ketal178** [comment]
> > 是否还有此问题
> 
> 没有了，但是现在不敢用了😂😂😂
> 
> 请问最近有没有研究一下防封方面的工作有研究
