### ISSUE TITLE
[QQ8.55] beta脚本功能没用

### ISSUE THREAD

**Issue by zhuixingzhe-baisheng** [ferredoxin/QNotified#774]
脚本功能没用

**Comment by ketal178** [comment]
@zhuixingzhe-baisheng 这个功能是装饰品，推荐用绿逗,复读机，你想用qn的，那要等很久很久

**Comment by zhuixingzhe-baisheng** [comment]
哦！谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月24日(周三) 晚上10:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ferredoxin/QNotified] [QQ8.55] beta脚本功能没用 (#774)




 
@zhuixingzhe-baisheng 这个功能是装饰品，推荐用绿逗,复读机，你想用qn的，那要等很久很久
