### ISSUE TITLE
[PlayQQ8_2_11]隐藏小程序入口

### ISSUE THREAD

**Issue by ketal178** [ferredoxin/QNotified#777]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* PlayQQ8_2_11，推测老版本QQ也会复现

**模块版本/Module Version**

* 0.8.15

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsp

**问题的具体描述/Detailed Description of the Bug**
开启隐藏小程序入口后，无法滑动打开qq侧滑菜单以及主页对话框菜单无法打开
*  具体描述(如复现BUG所需要的前提和必要操作等)
打开此功能
**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）
None
</code></pre></details>

**Comment by joyboy777** [comment]
play8211 勾选去除小程序会极大概率导致不能左滑到侧栏，下拉刷新消息无提示字
