### ISSUE TITLE
[QQ8.5.5] 自定义QQ等级关闭不能恢复正常显示

### ISSUE THREAD

**Issue by River2017CN** [ferredoxin/QNotified#780]
- [是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
8.5.5
* 

**模块版本/Module Version**
0.8.15.61f49de
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极 曳影·7.0.0.02111627-5816
* 

**问题的具体描述/Detailed Description of the Bug**
娱乐功能-自定义QQ等级即使关闭了仍不能恢复正常等级显示
![IMG_20210327_152241.jpg](https://user-images.githubusercontent.com/78515395/112713603-01106600-8f11-11eb-9d54-41acffd6d7ca.jpg)![IMG_20210327_152256.jpg](https://user-images.githubusercontent.com/78515395/112713607-05d51a00-8f11-11eb-8529-669bca4d4371.jpg)
*  具体描述(如复现BUG所需要的前提和必要操作等)
开启一次“娱乐功能-修改QQ等级”后即使关闭也不能恢复正常显示，禁用模块恢复

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）
（无日志）

</code></pre></details>

**Comment by ketal178** [comment]
重启qq

**Comment by River2017CN** [comment]
> 重启qq

重启十几遍没用，我等下更新860再试试吧

**Comment by ketal178** [comment]
@River2017CN 和QQ等级没关系，我这里也没有遇见

**Comment by ketal178** [comment]
@River2017CN 实际上这个也只有自己能看，以及自己名片等级不会改

**Comment by River2017CN** [comment]
> @River2017CN 实际上这个也只有自己能看，以及自己名片等级不会改

好的，谢谢大佬
