### ISSUE TITLE
[功能需求] 将相机替换为第三方相机

### ISSUE THREAD

**Issue by 1045925330** [ferredoxin/QNotified#786]
已经有一个 强制使用系统相机 的功能了，但是我的系统相机并不好用，所以希望能自己选择相机

**Comment by NextAlone** [comment]
@1045925330 建议更换系统默认相机。

**Comment by 1045925330** [comment]
> @1045925330 建议更换系统默认相机。

安卓11无法更换系统默认相机。

**Comment by singleNeuron** [comment]
> > @1045925330 建议更换系统默认相机。
> 
> 安卓11无法更换系统默认相机。

这是安卓11的问题，QN不予解决。

https://developer.android.com/about/versions/11/behavior-changes-11?hl=zh-cn#camera
