### ISSUE TITLE
[功能需求] 未读信息一键make all as read

### ISSUE THREAD

**Issue by qwq233** [ferredoxin/QNotified#792]
**QQ(TIM)版本/QQ(TIM) Version**

* all version

**为什么你认为需要此功能**

* 一个一个麻烦

**联系到哪些已经存在的bug或者功能**

**具体功能需要/Specific features required**

*  rt 类似tg的玩意 有人有空的话可以考虑做做 我捏其他玩意

**Comment by singleNeuron** [comment]
不是直接把在底栏的消息那里的气泡拖开就可以了吗？
