### ISSUE TITLE
QQ净化侧滑栏相关设置失效

### ISSUE THREAD

**Issue by AlexanderWolfZhang** [ferredoxin/QNotified#806]
QQ版本：8.6.5（同样问题在8.6.0也有）
QN版本：0.8.17.eb5678e
xposed版本：太极阴128（v7.0）
问题描述：之前反馈过开启复读消息折叠后侧滑净化失效，后续测试变成无论如何设置侧滑净化始终无法生效，干净重装QQ和插件（删除tencent文件夹）后重新设置仍无效（只设置QQ净化时可以生效但是一旦设置下方其他内容会导致侧滑净化再也无法生效），清除缓存可能有效，但是再次重启QQ后一定失效。尝试升级QQ到8.6.5也并未解决问题。
以下截图。
[https://img.vim-cn.com/f4/8c60bd175489de249137f6321a254574a044e8.jpg](url) 
[https://img.vim-cn.com/f9/c440c59a5921fc7ea9fbc466120a9cc94617fe.jpg](url) 
[https://img.vim-cn.com/48/59bbd667464a6b30af4a9b620799e78fa4e30a.jpg](url)

**Comment by ketal178** [comment]
已修复，等更新
