### ISSUE TITLE
[功能需求] 本模块本身能否增加新功能红点或其他提示？

### ISSUE THREAD

**Issue by soulpursuit** [ferredoxin/QNotified#816]
**QQ(TIM)版本/QQ(TIM) Version**

* 无

**为什么你认为需要此功能**

*  每次更新后都要每个菜单进去探寻新功能虽然这样挺刺激

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

希望本模块在更新后，在新功能项旁边能有红点提示或者new角标提示

*  具体描述(如使用的场景，面临的问题)

**Comment by ketal178** [comment]
@soulpursuit 更新日志干啥的？！

**Comment by Lagrio** [comment]
@soulpursuit 请至https://t.me/QNotified查看更新日志

**Comment by soulpursuit** [comment]
![Screenshot_2021-04-13-00-42-39-593_com tencent mobileqq](https://user-images.githubusercontent.com/48674277/114430657-40b59e00-9bf1-11eb-9a8f-936bb729481a.jpg)

不像之前那么方便，点这里就能看到了！！！

**Comment by soulpursuit** [comment]
![Screenshot_2021-04-13-00-42-54-592_org lsposed manager](https://user-images.githubusercontent.com/48674277/114430742-51feaa80-9bf1-11eb-9ddb-b0cabeddabe2.jpg)

还有这里，也是迷一样存在~是不是新版，全靠猜

**Comment by ketal178** [comment]
@soulpursuit ci版无日志日志很长，这个弹窗塞不下，

**Comment by ketal178** [comment]
@soulpursuit 这里没日志正常，
