### ISSUE TITLE
[功能需求] 续火改为收到你与xxx的xxx即将消失，今天记得打卡噢后自动回复

### ISSUE THREAD

**Issue by caoli5288** [ferredoxin/QNotified#821]
**QQ(TIM)版本/QQ(TIM) Version**

* all

**为什么你认为需要此功能**

* 比定时消息更为flexible

**联系到哪些已经存在的bug或者功能**

* none

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by NextAlone** [comment]
@caoli5288 这种提示大部分时间不会出现

**Comment by ketal178** [comment]
@caoli5288 一般来说无法实现，，

**Comment by caoli5288** [comment]
那可以获取到火花闪烁状态吗

**Comment by ketal178** [comment]
> 那可以获取到火花闪烁状态吗

不是很懂你想法
