### ISSUE TITLE
[8.6.5] QQ账号被异常封号（疑似大面积封号）

### ISSUE THREAD

**Issue by Nigel-NI** [ferredoxin/QNotified#830]
- [是 ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

QQ 8.6.5

**模块版本/Module Version**

版本0.8.18.c768cb7

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

应用转生6.4.9

**问题的具体描述/Detailed Description of the Bug**

QQ账号被冻结，提示“该账号涉嫌进行业务违规操作”。但是插件设置里没有开启与抢红包有关的设置。

**此处贴你获取到的日志信息/Log here**

腾讯官方行为，暂无日志

**Comment by dzshzx** [comment]
QQ(TIM)版本/QQ(TIM) Version

QQ 8.6.5

模块版本/Module Version

版本0.8.18.c768cb7

使用的框架名称与框架版本/Xposed Framework and Framework Version

LSPOSED 1.3.5

问题的具体描述/Detailed Description of the Bug

QQ账号被冻结，提示“该账号涉嫌进行业务违规操作”。但是插件设置里没有开启与抢红包有关的设置。

此处贴你获取到的日志信息/Log here

腾讯官方行为，暂无日志

**Comment by DearJia1** [comment]
暂避风头

**Comment by Steve-cn** [comment]
同样，已经关了所有模块，卸载重新安装QQ并拒绝QQ获取应用程序列表了

**Comment by EvilOctopusFu** [comment]
+1,也是遇到了同样的情况。

**Comment by ketal178** [comment]
无计划开发防检测，也无法帮用户解封，怕就别用
每次大规模封号都是很久才有一次

**Comment by singleNeuron** [comment]
> * [是 ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
> 
> **QQ(TIM)版本/QQ(TIM) Version**
> 
> QQ 8.6.5
> 
> **模块版本/Module Version**
> 
> 版本0.8.18.c768cb7
> 
> **使用的框架名称与框架版本/Xposed Framework and Framework Version**
> 
> 应用转生6.4.9
> 
> **问题的具体描述/Detailed Description of the Bug**
> 
> QQ账号被冻结，提示“该账号涉嫌进行业务违规操作”。但是插件设置里没有开启与抢红包有关的设置。
> 
> **此处贴你获取到的日志信息/Log here**
> 
> 腾讯官方行为，暂无日志

应用转生这种免root框架太容易被检测了，连包都给改了
