### ISSUE TITLE
[功能需求] 使用SharedPreferences接口封装的配置存储方案

### ISSUE THREAD

**Issue by singleNeuron** [ferredoxin/QNotified#831]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* EdfriendManager已被废弃而无任何代替方案，现有配置存储方案难用至极。

**联系到哪些已经存在的bug或者功能**

* https://github.com/ferredoxin/QNotified/pull/824

**具体功能需要/Specific features required**

*  替代被废弃的ExfriendManager等现有的屎山存储，在所有非工厂类代码中类型均需为SharedPrefereces以便于未来迁移。

**Comment by ketal178** [comment]
现有的问题是进程隔离
在安卓7.0-，QQ865，使用mmkv会炸掉

**Comment by FROZENJJ** [comment]
这两天qn大面积封号诶QAQ

**Comment by NextAlone** [comment]
@FROZENJJ 见频道公告，请勿继续反馈此类信息。

**Comment by singleNeuron** [comment]
> 现有的问题是进程隔离
> 在安卓7.0-，QQ865+，使用mmkv会炸掉

把minSdkVersion调到O不就行了

**Comment by singleNeuron** [comment]
> @FROZENJJ 见频道公告，请勿继续反馈此类信息。

麻烦帮我复制一下文本到这里，学校里不能魔法上网

**Comment by NextAlone** [comment]
@singleNeuron 公告

截止目前，我们已收到多名用户反馈，内容均为其 QQ 帐号被暂时冻结，且被冻结的帐号需要通过人脸验证或其他验证方式才能恢复使用，腾讯官方给出的冻结理由多为「该帐号因涉嫌业务违规操作被暂时冻结」。

经多方渠道了解，我们发现此次 QQ 帐号被冻结现象范围较广，时间点较为集中，且被封用户无明显特征。无论用户是否使用了 Xposed 类模块、是否安装了 Magisk 等应用、是否使用的是 QQ v8.6.5(1696) ，我们均发现存在 QQ 帐号被冻结现象。

我们初步判断此次冻结现象可能为腾讯官方的净网行动，与 QNotified 无关，但不排除有其他可能的因素影响。

*提示：使用 Xposed 类模块具有一定风险，请您在自行评估风险后选择是否使用 QNotified 或其他 Xposed 类模块。

如您选择使用 QNotified ，您需要自担风险，我们不为任何使用 QNotified 产生的后果承担任何责任。

QNotified 社区频道
2021.04.22

**Comment by ketal178** [comment]
@singleNeuron ？咕咕华会反对的

**Comment by singleNeuron** [comment]
> @singleNeuron ？咕咕华会反对的

？他自己都不用7.0了好吗，要不然就先把7.0以上的迁移过去，7.0以下的走IPC向主进程CURD。

**Comment by ketal178** [comment]
@singleNeuron 你没QQ吗，github不费劲吗

**Comment by singleNeuron** [comment]
> @singleNeuron 你没QQ吗，github不费劲吗

班里大屏幕啊，也就GitHub即登即用不留痕迹了。

**Comment by singleNeuron** [comment]
要不然还是用Android Room吧，SQL多进程不同时写是没问题的。目前只在主进程有写入需求，其他进程只有读需求，这样的话不用管Android Room的那一套同步机制，我们自己用IPC写一套失效的“广播”就可以了。

或者尽快找一个安全高性能的多进程读单进程写的配置持久化方案出来，建议五一之前完成。
