### ISSUE TITLE
[功能需求] 获取qq空间被挡访客

### ISSUE THREAD

**Issue by AkariPOI** [ferredoxin/QNotified#833]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 因为不想开黄钻

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**
在列表中显示被挡访客的头像昵称等信息
*  具体描述(如使用的场景，面临的问题)
* 首次进入空间后这个图标下会显示被挡访客的头像，非黄钻用户只能看到这个头像而无法进一步查看
![qq_pic_merged_1619084766967](https://user-images.githubusercontent.com/69719282/115694004-0ab3af00-a393-11eb-87ef-8668191dab32.jpg)

**Comment by NextAlone** [comment]
@AkariPOI 凡是需要request的东西。一概做不了。

**Comment by singleNeuron** [comment]
请自行充黄钻会员，此限制在腾讯服务器端而不是QQ客户端，不在QNotified能力范围内。
