### ISSUE TITLE
[QQ8.5.5] 在“太极·阳”环境下出现因为“使用不是官方版本”问题而被冻结

### ISSUE THREAD

**Issue by Grand-cocoa** [ferredoxin/QNotified#835]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 手机QQ 8.5.5

**模块版本/Module Version**

* 0.8.18.c768cb7

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极 曳影·7.0.0.02111627

**问题的具体描述/Detailed Description of the Bug**

* 不需要任何操作
* 在“太极·阳”环境下出现因为“使用不是官方版本”问题而被冻结

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

非软件BUG

</code></pre></details>

**Comment by NextAlone** [comment]
@Grand-cocoa 855也出现了？

**Comment by Grand-cocoa** [comment]
目前已更新为865使用，还不知道是否有问题

**Comment by NextAlone** [comment]
@Grand-cocoa 目前发现的封号多为865

**Comment by Grand-cocoa** [comment]
@NextAlone 懂了，这就换老版本💊

**Comment by ACodingJie** [comment]
@Grand-cocoa 换哪个版本比较保险？ 之前使用7开头的好像一直没有遇到问题😂

**Comment by NextAlone** [comment]
@ACodingJie 暂时卸载比较安全。

**Comment by NextAlone** [comment]
@ACodingJie 说真的

**Comment by Grand-cocoa** [comment]
现已换成8.4.5测试（Doge）
