### ISSUE TITLE
[PlayQQ 8.2.11.4530] 无法启动QNotified 

### ISSUE THREAD

**Issue by player0898** [ferredoxin/QNotified#836]
**QQ(TIM)版本/QQ(TIM) Version**

PlayQQ 8.2.11.4530

**模块版本/Module Version**

QNotified v0.8.16 从Telegram频道下载
QNotified v0.8.17 从Edxposed商城下载
QNotified v0.8.11.265.d3ba0e0 从GooglePlay下载

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

Edxposed 0.5.2.1 

**问题的具体描述/Detailed Description of the Bug**

三个版本安装完成重启后点开都提示绿色的已激活，点击模块设置中的QQ，拉起QQ然后瞬间闪退，设置中看不到QNotified 设置选项。QQ安装的是GooglePlay商城的8.2.11.4630版，似乎与更新说明中的8.2.11.1380版本号不一致

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
@player0898 是否屏蔽应用列表

**Comment by ketal178** [comment]
试试点击故障排除

**Comment by lliioollcn** [comment]
请问现在还有无此问题？

**Comment by Panadolysc** [comment]
我也遇到这个问题了

**Comment by ketal178** [comment]
> 我也遇到这个问题了

试试能不能进故障排查

**Comment by Panadolysc** [comment]
> > 我也遇到这个问题了
> 
> 试试能不能进故障排查

不行，，，设置里的QNotified都进不去

**Comment by ketal178** [comment]
> > > 我也遇到这个问题了
> > 
> > 
> > 试试能不能进故障排查
> 
> 不行，，，设置里的QNotified都进不去

![image](https://user-images.githubusercontent.com/41381927/117145325-9ee73280-ade5-11eb-8d5f-f9c9069074d6.png)

**Comment by Panadolysc** [comment]
> > > > 我也遇到这个问题了
> > > 
> > > 
> > > 试试能不能进故障排查
> > 
> > 
> > 不行，，，设置里的QNotified都进不去
> 
> ![image](https://user-images.githubusercontent.com/41381927/117145325-9ee73280-ade5-11eb-8d5f-f9c9069074d6.png)

哦QAQ可以进

**Comment by ketal178** [comment]
> > > > > 我也遇到这个问题了
> > > > 
> > > > 
> > > > 试试能不能进故障排查
> > > 
> > > 
> > > 不行，，，设置里的QNotified都进不去
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/41381927/117145325-9ee73280-ade5-11eb-8d5f-f9c9069074d6.png)
> 
> 哦QAQ可以进

清除缓存
清除所有的历史记录
重置模块设置
一次删一个
删完看看能不能进，不能就删下一个

**Comment by Panadolysc** [comment]
> > > > > > 我也遇到这个问题了
> > > > > 
> > > > > 
> > > > > 试试能不能进故障排查
> > > > 
> > > > 
> > > > 不行，，，设置里的QNotified都进不去
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/41381927/117145325-9ee73280-ade5-11eb-8d5f-f9c9069074d6.png)
> > 
> > 
> > 哦QAQ可以进
> 
> 清除缓存
> 清除所有的历史记录
> 重置模块设置
> 一次删一个
> 删完看看能不能进，不能就删下一个

呜呜我这里可以了，谢谢~

**Comment by player0898** [comment]
> 请问现在还有无此问题？

我后来把edp换成LSP就解决了
