### ISSUE TITLE
[QQ8.6.0] 太极不认QNotified

### ISSUE THREAD

**Issue by xiaodou233333** [ferredoxin/QNotified#838]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
8.6.0.5210
* 

**模块版本/Module Version**
0.8.18.0f65d7a
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极 曳影·7.0.0.02111627-5999
* 

**问题的具体描述/Detailed Description of the Bug**
太极不认QNotified 都写暂不支持
![QQ图片20210424000142](https://user-images.githubusercontent.com/61956441/115899329-3321d300-a491-11eb-93d6-f77675db4fde.jpg)

*  具体描述(如复现BUG所需要的前提和必要操作等)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
自己找weishu去

**Comment by singleNeuron** [comment]
太极软件仓库炸了，已经通知到weishu，需等候他亲自解决
