### ISSUE TITLE
[QQ8.4.10] 模块更新后太极阴显示暂不支持

### ISSUE THREAD

**Issue by Poiniconi** [ferredoxin/QNotified#839]
- [ ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
是
**QQ(TIM)版本/QQ(TIM) Version**

* qq8.4.10

**模块版本/Module Version**

* 0.8.18.c768cb7

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极阴 曳影7.0。0.02111627-5999

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

手机系统OriginOS1.0，之前用的是0.8.15.x的模块，晚上更新到 0.8.18.c768cb7模块并重启手机后，太极阴显示暂不支持，无法勾选模块，更新引擎、回退旧版本模块、更换其他版本QQ、取消优化也均显示不支持。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
找weishu
