### ISSUE TITLE
强制下线问题反馈

### ISSUE THREAD

**Issue by imstan** [ferredoxin/QNotified#840]
今早收到腾讯下线提醒
![Screenshot_2021-04-24-06-37-23-900_com tencent mobileqq](https://user-images.githubusercontent.com/83098656/115937329-4d2bd780-a4ca-11eb-8c24-e7c2431b979b.jpg)
进入客服中心后提醒由于使用修改版QQ软件被冻结登录。
由于开启的功能较多，无法确定是哪一项或者哪些项导致的此问题。
不知各位有无建议，哪些功能可能会导致被检测到，可以尝试性关闭

**Comment by Kegekkk** [comment]
我也遇到了，这两天才开始的，每天早上必给我冻结

**Comment by qwq233** [comment]
频道公告
