### ISSUE TITLE
[8.6.5] 会被检测，次日提示冻结

### ISSUE THREAD

**Issue by WenKin0106** [ferredoxin/QNotified#851]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.6.5

**模块版本/Module Version**

* 0.8.18

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* v93

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

次日登录QQ会被冻结，提示使用篡改的客户端登录

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>
无

**Comment by WenKin0106** [comment]
![Uploading IMG_20210502_071839.jpg…]()

**Comment by NextAlone** [comment]
请见电报频道公告。本问题不受理。
