### ISSUE TITLE
[QQ870] 夜间模式下字数统计不可见

### ISSUE THREAD

**Issue by XinYi-Media** [ferredoxin/QNotified#860]
- [是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 870

**模块版本/Module Version**

* 0.8.19.2c41172

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

如图
![Screenshot_20210503_144235_com tencent mobileqq](https://user-images.githubusercontent.com/72146600/116847959-313cda00-ac1e-11eb-9d6f-5be8a5ca1d3b.jpg)
![Screenshot_20210503_144230_com tencent mobileqq](https://user-images.githubusercontent.com/72146600/116847963-33069d80-ac1e-11eb-8960-9979274f5861.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

没有日志

</code></pre></details>

**Comment by cinit** [comment]
长按看不见的字可以修改颜色
