### ISSUE TITLE
[QQ8.5.5 TIM3.5.5] 小程序转链接分享（接收）的设置无法保存

### ISSUE THREAD

**Issue by Hoshikawakaguya** [ferredoxin/QNotified#866]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.5.5 TIM3.5.5均有发生

**模块版本/Module Version**

*0.8.19.2c41172

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* QQ（太极阴） Tim（edxposed）

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

某版本升级后 原本小程序转链接接收为开启状态设置为关闭，亦或原本为关闭状态开启后，重启qq或tim程序，设置重新变回开启或是关闭

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
新版UI重构中，部分功能可能不稳定。这是开发组已知问题，将会尽快解决。

退回到 https://github.com/ferredoxin/QNotified/commit/bc0f4be2fe8d80324f6e8f49a65f213c7d4f463a 之前（不包括）可能可以改善此问题。

**Comment by ketal178** [comment]
@singleNeuron 元元想你了

**Comment by singleNeuron** [comment]
> @singleNeuron 元元想你了

我这周试着请假回去qwq

**Comment by cinit** [comment]
@singleNeuron 别吧，就剩一个月了

**Comment by NextAlone** [comment]
@cinit 别吧，就剩一个月了

**Comment by ketal178** [comment]
@singleNeuron 别吧，就剩一个月了
