### ISSUE TITLE
[QQ 8.7.0]屏蔽DIY名片无效

### ISSUE THREAD

**Issue by mother-hunter-father-killer** [ferredoxin/QNotified#868]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.7.0

**模块版本/Module Version**

* 0.8.19.2c41172

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

屏蔽DIY名片无效 如图

![-63f774606743f9ba](https://user-images.githubusercontent.com/83447071/117144685-d3bca080-ad77-11eb-879f-69f8d55b0898.jpg)

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by ketal178** [comment]
这，，，，是腾讯的自带样式，不是那堆破diy名片

**Comment by mother-hunter-father-killer** [comment]
> 这，，，，是腾讯的自带样式，不是那堆破DIY名片

之前开屏蔽DIY的这玩意就不显示....

**Comment by ketal178** [comment]
@mother-hunter-father-killer qq860开始坏了，勉强修好能用就不错了

**Comment by mother-hunter-father-killer** [comment]
> @母亲-猎人-父亲杀手Qq 860开始坏了，勉强修好能用就不错了

好吧 感谢 我哈批了

**Comment by ketal178** [comment]
> > @母亲-猎人-父亲杀手Qq 860开始坏了，勉强修好能用就不错了
> 
> 好吧 感谢 我哈批了

草你这个翻译
