### ISSUE TITLE
[QQ8.3.0(1362)] 防撤回功能没有效果

### ISSUE THREAD

**Issue by Ajing4152** [ferredoxin/QNotified#870]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
QQ8.3.0(1362)
* 

**模块版本/Module Version**
0.8.19.2c41172
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
使用的是太极阴，版本湛泸·6.4.0.09021214-6105
* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
在查看别人发的图片时，别人撤回，然后提示消息已被撤回，之后用电脑登陆小号测试，发送文字然后撤回，防撤回没有效果

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
qq版本过老暂不考虑功能维护
