### ISSUE TITLE
开源许可证冲突

### ISSUE THREAD

**Issue by singleNeuron** [ferredoxin/QNotified#875]
https://github.com/ferredoxin/QNotified/pull/869/files#diff-c9cee5809a45bce39e6470edd1efe099c3da0ce3563879597aa1a02fb9d33b8cR1
中引入了LSPosed的文件，而此文件是GPL许可证，与本项目的AGPL许可证严重冲突。

**Comment by qwq233** [comment]
？agpl兼容gpl啊

**Comment by qwq233** [comment]
https://zh.m.wikipedia.org/wiki/%E8%87%AA%E7%94%B1%E5%8F%8A%E9%96%8B%E6%94%BE%E5%8E%9F%E5%A7%8B%E7%A2%BC%E8%BB%9F%E9%AB%94%E8%A8%B1%E5%8F%AF%E8%AD%89%E6%AF%94%E8%BC%83
