### ISSUE TITLE
[QQ 8.7.8] Bug 收集

### ISSUE THREAD

**Issue by keta1** [ferredoxin/QNotified#899]
## 请简述无法使用的功能

**修复进度**

**Comment by Neturalized** [comment]
QQ净化→侧滑→隐藏侧滑栏列表失效

**Comment by Samuel-meteor** [comment]
手机机型荣耀v20
qq qn版本均为最新
在“花Q”分选项中的 自定义启动图 的图片路径中多次尝试输入一张存在相册中的图片的路径，但一直都提示路径不存在或者有误，请问标准路径格式应该是怎么样的？文件路径的开头名词不知道该是啥，包括但不限于 手机存储内部存储存储等名词以及它们的英文大小写都试了过去但是都不行

**Comment by mis1042** [comment]
#910

**Comment by Zeraphyms** [comment]
免广告送群礼物又双叒叕失效了，视频类广告失效了，又出现倒计时了

**Comment by ketal178** [comment]
@Zeraphyms 你去pr就有了

**Comment by Zeraphyms** [comment]
@ketal178 阿巴阿巴，我还是去睡大觉吧乌乌

**Comment by Zeraphyms** [comment]
@ketal178 话说pr你你会动身去写吗🌝

**Comment by ketal178** [comment]
> @ketal178 话说pr你你会动身去写吗🌝

我是菜鸡，写不来

**Comment by 3033418609** [comment]
QQ是8.8.0   最新的那个f8版本的QN不知道为什么显示不了，QQ里面没有，防撤回那些东西直接失效，用的太极，有没有大佬教教啊，真没搞懂

**Comment by mis1042** [comment]
不好意思麻烦了,#912

**Comment by aisibia** [comment]
8.7.0以上的qq用这个模块会冻结，用以下的版本能解决问题吗？

**Comment by NextAlone** [comment]
@aisibia 旧版本封号冻结几率显著降低，具体可以自测
