### ISSUE TITLE
[QQ8.7.0] qzone启动失败

### ISSUE THREAD

**Issue by XinYi-Media** [ferredoxin/QNotified#900]
- [] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.7.0

**模块版本/Module Version**

* 0.8.19.2c41172

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
qzone启动失败

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

没有日志诶

</code></pre></details>

**Comment by XinYi-Media** [comment]
等一下，图片上传不了

**Comment by XinYi-Media** [comment]
https://img03.sogoucdn.com/app/a/100520146/7a156f02b5230d3d41f5479effcd8adc

**Comment by ketal178** [comment]
1尝试关闭qn，查看能否打开
2不能打开尝试清楚QQ数据查看能否打开
3清楚数据后能打开，尝试开启qn，查看能否打开

**Comment by XinYi-Media** [comment]
太极中关闭qn仍无法打开，理论为框架问题
