### ISSUE TITLE
寻求QQ集成版本

### ISSUE THREAD

**Issue by wangdi376** [ferredoxin/QNotified#901]
由于手机无法正常使用xposed激活QNotified，寻求一个手机QQ安装包内置新版本的QN模块,谢谢啦

**Comment by singleNeuron** [comment]
抱歉，我们不提供此类服务

**Comment by wangdi376** [comment]
(╯︵╰)

**Comment by cinit** [comment]
@wangdi376 为何无法激活?

**Comment by wangdi376** [comment]
因为手机没有root自己某些原因激活后有问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月23日(星期天) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ferredoxin/QNotified] 寻求QQ集成版本 (#901)
