### ISSUE TITLE
[QQ8.7.8] 在Android6 MIUI10上出现问题

### ISSUE THREAD

**Issue by mis1042** [ferredoxin/QNotified#910]
- [* ] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**
8.7.8
* 

**模块版本/Module Version**
0.8.19 b63cec6
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极阳，128 60
* 

**问题的具体描述/Detailed Description of the Bug**
经常会弹出QQ已停止运行，但是并没有停止，第二天会被腾讯冻结
*  具体描述(如复现BUG所需要的前提和必要操作等)
在Android6和MIUI10使用本模块

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）
无日志，我点击查看日志没有内容

</code></pre></details>

**Comment by ketal178** [comment]
复现不了，没log
我这就去学魔法

**Comment by mis1042** [comment]
我点击了查看日志，但是没有任何东西出现，我再试试

**Comment by mis1042** [comment]
它看起来像这样
![Screenshot_2021-06-02-22-43-15-090_com tencent mobileqq](https://user-images.githubusercontent.com/53249654/120501250-0cda4600-c3f4-11eb-8b4b-db8b9b35f15d.png)
然后这个弹出频率很高

**Comment by ketal178** [comment]
> 它看起来像这样
> ![Screenshot_2021-06-02-22-43-15-090_com tencent mobileqq](https://user-images.githubusercontent.com/53249654/120501250-0cda4600-c3f4-11eb-8b4b-db8b9b35f15d.png)
> 然后这个弹出频率很高

有电脑吗

**Comment by mis1042** [comment]
有的，您需要我怎么做

**Comment by ketal178** [comment]
> 有的，您需要我怎么做

联系方式，我远程来看看

**Comment by mis1042** [comment]
我电脑是macOS的
QQ:3526436393
email:mailto:misaka@mis1042.top

**Comment by mis1042** [comment]
感谢大佬~
