### ISSUE TITLE
[QQ8.7.8] 问题依旧,在android6上仍然弹出QQ已停止运行

### ISSUE THREAD

**Issue by mis1042** [ferredoxin/QNotified#913]
- [x] #972

**QQ(TIM)版本/QQ(TIM) Version**

QQ8.7.6

**模块版本/Module Version**

Qnotified 0.8.19 0676e72

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

太极阳

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

无

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

注:我已经反馈过,有大佬改了代码并且合并,我已经下载安装并重启以使用更新版本(刚修改后的那个),但是错误依旧
上一个issues:#910
PR:#912

**Comment by IJustWantANamePlease** [comment]
确定不是手机带不动qq了吗（bushi）

**Comment by cinit** [comment]
@IJustWantANamePlease 请抓取QQ闪退log然后附上

**Comment by 205556501** [comment]
And6版本也太低了吧

**Comment by lightoo1122** [comment]
红米note 10 Android11也经常这样，荣耀20 Android10正常

**Comment by singleNeuron** [comment]
@lightoo1122 这个应该是因为mmkv吧

**Comment by 20000121qq** [comment]
也存在问题，MIUI10.9开发版
