### ISSUE TITLE
[QQ8.4.18]QQ被杀后台后QN模块失效

### ISSUE THREAD

**Issue by Luo-Xiao-Mi** [ferredoxin/QNotified#915]
**QQ(TIM)版本/QQ(TIM) Version**

*QQ8.4.18

**模块版本/Module Version**

* 0.8.19

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极6.3.0

**问题的具体描述/Detailed Description of the Bug**
QN模块失效，在QQ里没有显示，重装和更新模块都没有解决
*  具体描述(如复现BUG所需要的前提和必要操作等)
荣耀20手机，今天使用省电模式打开QQ之后用了一段时间，再回来之后发现QN失效了，但QX还在

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）不知道在哪里(不好意思)

</code></pre></details>

**Comment by ketal178** [comment]
@Luo-Xiao-Mi /data/user/0/com.tencent.mobileqq/files/qnotified_config.dat
删了他

**Comment by Luo-Xiao-Mi** [comment]
> @Luo-Xiao-Mi /data/user/0/com.tencent.mobileqq/files/qnotified_config.dat
> 删了他

可是荣耀手机无法进入根目录怎么破(

**Comment by ketal178** [comment]
@Luo-Xiao-Mi 清除所有QQ数据

**Comment by ketal178** [comment]
@Luo-Xiao-Mi 进故障排查

**Comment by ketal178** [comment]
@Luo-Xiao-Mi 里面能清楚模块设置

**Comment by Luo-Xiao-Mi** [comment]
> @Luo-Xiao-Mi 里面能清楚模块设置

好的  我试试

**Comment by Luo-Xiao-Mi** [comment]
点击故障排查之后出现一个提示  几秒后切入qq变成黑屏   之后就QQ未响应了
![Uploading Screenshot_20210608_115731_com.tencent.mobileqq.jpg…]()

**Comment by ketal178** [comment]
> 点击故障排查之后出现一个提示  几秒后切入qq变成黑屏   之后就QQ未响应了
> ![Uploading Screenshot_20210608_115731_com.tencent.mobileqq.jpg…]()
> 

你这图还没上传完，就....

**Comment by Luo-Xiao-Mi** [comment]
> 点击故障排查之后出现一个提示 几秒后切入qq变成黑屏 之后就QQ未响应了
> 
> 
> 你这图还没上传完，就....

啊。。对不起  我在上传一次
![Screenshot_20210608_115731_com tencent mobileqq](https://user-images.githubusercontent.com/43297943/121120921-2bf03200-c851-11eb-82b6-8cacb49ef68b.jpg)

**Comment by ketal178** [comment]
> > 点击故障排查之后出现一个提示 几秒后切入qq变成黑屏 之后就QQ未响应了
> > 
> > 
> > 你这图还没上传完，就....
> 
> 啊。。对不起  我在上传一次
> ![Screenshot_20210608_115731_com tencent mobileqq](https://user-images.githubusercontent.com/43297943/121120921-2bf03200-c851-11eb-82b6-8cacb49ef68b.jpg)
> 

点下面的故障排查进不去的话，没救了，清数据或者不用qn，自己选吧

**Comment by Luo-Xiao-Mi** [comment]
> > > 点击故障排查之后出现一个提示 几秒后切入qq变成黑屏 之后就QQ未响应了
> > > 你这图还没上传完，就....
> > 
> > 
> > 啊。。对不起  我在上传一次
> > ![Screenshot_20210608_115731_com tencent mobileqq](https://user-images.githubusercontent.com/43297943/121120921-2bf03200-c851-11eb-82b6-8cacb49ef68b.jpg)
> 
> 点下面的故障排查进不去的话，没救了，清数据或者不用qn，自己选吧

好吧  谢谢了。。。
