### ISSUE TITLE
tim2.3.1.1834闪退

### ISSUE THREAD

**Issue by youlan2333** [ferredoxin/QNotified#920]
tim2.3.1.1834
模块版本0.8.19.f89607d（最新）
框架：太极阳128（60）曳影-7.0.3.05282148-6273（最新）
---------------------------------------------------------------------
问题：在激活时自动重启tim后闪退
用太极优化tim后显示版本号但点击设置中qn依旧闪退
---------------------------------------------------------------------
![QQ截图20210612083148](https://user-images.githubusercontent.com/64688148/121759523-a7efc000-cb58-11eb-8716-00918f6c319f.png)

**Comment by Ferryseven** [comment]
可以试试最新版的含光8.0.0.06092326
