### ISSUE TITLE
【QQ8.8.0】聊天界面“发送”按钮显示不正常

### ISSUE THREAD

**Issue by DypeStone** [ferredoxin/QNotified#921]
**QQ(TIM)版本/QQ(TIM) Version**
  QQ8.8.0
* 

**模块版本/Module Version**
  Qn0.8.20
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
  太极
* 

**问题的具体描述/Detailed Description of the Bug**
  当启用Qnotified并打开简洁模式时，聊天界面“发送”按钮显示不正常
*  具体描述(如复现BUG所需要的前提和必要操作等)
* [图片](https://i.ibb.co/DVjw74R/pop.jpg)

**Comment by keta1** [comment]
@DypeStone 0.8.19有吗

**Comment by DypeStone** [comment]
> @DypeStone 0.8.19有这个bug吗

有

**Comment by DypeStone** [comment]
新发现：被收在群助手里的群，「发送」按钮正常
