### ISSUE TITLE
[功能需求] 阻止QQ拦截非安全网址

### ISSUE THREAD

**Issue by 0XPYEX0** [ferredoxin/QNotified#930]
**QQ(TIM)版本/QQ(TIM) Version**
QQ 8.8.0 (5420)
* 

**为什么你认为需要此功能**
去除反人类功能
* 

**联系到哪些已经存在的bug或者功能**
无
* 

**具体功能需要/Specific features required**
阻止QQ跳转至拦截界面，直接打开对应网址

*  具体描述(如使用的场景，面临的问题)
在QQ中打开不在腾讯白名单的网站会被拦截，要求在浏览器打开(如果要在浏览器开，我在你QQ开干什么)

**Comment by singleNeuron** [comment]
@0XPYEX0 这玩意是x5的feature吧，禁用x5试试？

**Comment by 0XPYEX0** [comment]
...？抱歉我理解不能，可否详讲

**Comment by singleNeuron** [comment]
@0XPYEX0 在QQ中打开http://debugx5.qq.com/即可进入x5内核调试页面，在该页面中可以卸载并禁用x5内核，强制QQ使用Android webview

**Comment by xushet** [comment]
应该跟x5没有关系的

**Comment by 0XPYEX0** [comment]
事实上我自己晚上找了十来分钟还是没找到哪里能关H5，，可能是我太菜了⑧，，
我也感觉不是那个的问题

**Comment by singleNeuron** [comment]
麻烦给个被拦截的网址的样本，我去测试

**Comment by keta1** [comment]
@singleNeuron 996.icu

**Comment by 0XPYEX0** [comment]
https://jd.bukkit.org

**Comment by qwq233** [comment]
什么网站一定要在qq开 理解不能(

**Comment by 0XPYEX0** [comment]
> 什么网站一定要在qq开 理解不能(

发给我的链接我不能看🐴？QQ这么搞，我就得复制出去开，还不能直接选浏览器打开，纯属反人类操作

**Comment by qwq233** [comment]
> > 什么网站一定要在qq开 理解不能(
> 
> 发给我的链接我不能看？QQ这么搞，我就得复制出去开，还不能直接选浏览器打开，纯属反人类操作

有个模块叫“去您大爷的内置浏览器”

**Comment by 0XPYEX0** [comment]
我觉得QN能做也挺好的
不乐意写我也不能怎么样 毕竟咱比较菜
那就close吧
