### ISSUE TITLE
[功能需求] 希望添加打开转发多条记录内详细资料的功能

### ISSUE THREAD

**Issue by hayabusa169** [ferredoxin/QNotified#936]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ V8.4.8.4810

**为什么你认为需要此功能**

* 方便查看多条转发记录内账号的详细资料，方便直接添加好友，查看账号信息

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
以前Qnotified0.8.10版本的时候有的功能，非常实用，不知道为什么后来更新取消掉了，希望添加回来

**Comment by singleNeuron** [comment]
@hayabusa169 我这边现在一直有这个功能啊
