### ISSUE TITLE
[8.5.5] 群聊中经常出现疑似厘米秀动画

### ISSUE THREAD

**Issue by djj200504001** [ferredoxin/QNotified#939]
- [ 是] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5（1630）

**模块版本/Module Version**

* 0.8.20.1b90a17

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极阴，曳影7.0.3.05282148-6376

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

在群聊中出现大段文字/特定排序的数字时，会触发520动画，一个跳动的心形，具体效果如下：
![S10627-14085850](https://user-images.githubusercontent.com/3965694/124362664-f4ff1780-dc68-11eb-8f99-2423ef9dd773.png)
![S10627-14090048](https://user-images.githubusercontent.com/3965694/124362669-fcbebc00-dc68-11eb-90a2-14b0c86b5e9b.png)
出现此动画时群聊消息滚动会变得卡顿
检查过厘米秀，在主界面右划菜单右下角未发现厘米秀，应该已经关闭
![S10704-01425618](https://user-images.githubusercontent.com/3965694/124362709-427b8480-dc69-11eb-873a-36fbb31a4975.png)
查看过issued，尝试使用“静默指定类型通知消息”功能，但是未找到CMshow字眼。

如需了解更多细节可联系：
QQ：514065186
邮箱：514065186@qq.com

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

未找到导出日志功能

</code></pre></details>

**Comment by djj200504001** [comment]
补充说明：虽然截图头像不一样，但是两个QQ均会触发此动画，均未在右划菜单右下角看见厘米秀。

**Comment by keta1** [comment]
你把qn关了，再试试会不会触发
还会触发就不是qn的问题

**Comment by djj200504001** [comment]
经测试应该不是qn的问题，我把bug反馈换成功能需求再提一次。
