### ISSUE TITLE
[功能需求] 屏蔽QQ群聊天时弹出的疑似厘米秀动画

### ISSUE THREAD

**Issue by djj200504001** [ferredoxin/QNotified#940]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.5.5

**为什么你认为需要此功能**

* 弹出此动画的时候滚动和输入会变得非常卡顿

**联系到哪些已经存在的bug或者功能**

* 暂无

**具体功能需要/Specific features required**

*  https://github.com/ferredoxin/QNotified/issues/939

**Comment by bigfoxtail** [comment]
大胸弟你把厘米秀关了不好么？

**Comment by djj200504001** [comment]
我这边看是关了的，但是还是会弹出来

**Comment by bigfoxtail** [comment]
23333   你清空下数据重新试试吧
