### ISSUE TITLE
[功能需求] Tim深色模式

### ISSUE THREAD

**Issue by SukiEva** [ferredoxin/QNotified#943]
**QQ(TIM)版本/QQ(TIM) Version**

* 最新版本

**为什么你认为需要此功能**

* 完全看不到官方增加深色模式的可能性

**联系到哪些已经存在的bug或者功能**

* 无

**具体功能需要/Specific features required**

*  夜间能跟随系统深色，或者手动开启，在一些强制深色功能不完善（比如一加）的手机上，防止夜间亮瞎眼

**Comment by tvcbuv** [comment]
同样有此需求，并且qn在Tim上很多功能无效，比如回复禁用@，消息复读+1会出现串行问题

**Comment by singleNeuron** [comment]
@tvcbuv 因为没几个开发者用Tim

**Comment by tvcbuv** [comment]
> @tvcbuv 因为没几个开发者用Tim

哈哈，tg那边的bot我也有反馈过，也是说开发者们不使用Tim😂
