### ISSUE TITLE
[TIM] 软件屡次停止被提醒

### ISSUE THREAD

**Issue by pdnfm** [ferredoxin/QNotified#944]
**QQ(TIM)版本/QQ(TIM) Version**

* tim 3.3.8

**模块版本/Module Version**

* 0.8.20.1b90a17

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* magisk 22.1 太极 7.0.0

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
在安装模块前，tim正常；安装后，功能正常，消息刷新不及时，手机频繁报出停止运行需要上传报告

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/sagit/sagit:9/PKQ1.190118.001/20.6.18:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 21508, tid: 21508, name: ncent.tim:qzone  >>> com.tencent.tim:qzone <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x12efebb8
    r0  12efeb78  r1  00000010  r2  afaad000  r3  00000018
    r4  00000000  r5  e94969f1  r6  ffe094d0  r7  00000000
    r8  e9dd7000  r9  ffe093ac  r10 ffe094a0  r11 00000003
    ip  00000001  sp  ffe09340  lr  e93ff893  pc  e93ffa7c

backtrace:
    #00 pc 00380a7c  /system/lib/libart.so (offset 0x2b0000) (art::FetchStackTraceVisitor::VisitFrame()+500)
    #01 pc 00365f0b  /system/lib/libart.so (offset 0x2b0000) (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+1334)
    #02 pc 0036d04b  /system/lib/libart.so (offset 0x2b0000) (_jobject* art::Thread::CreateInternalStackTrace<false>(art::ScopedObjectAccessAlreadyRunnable const&) const+106)
    #03 pc 002f29d5  /system/lib/libart.so (offset 0x2b0000) (art::Throwable_nativeFillInStackTrace(_JNIEnv*, _jclass*)+28)
    #04 pc 004d7f07  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.Throwable.nativeFillInStackTrace+94)
    #05 pc 004d94ff  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.Throwable.fillInStackTrace+94)
    #06 pc 00994427  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.ClassNotFoundException.<init>+142)
    #07 pc 00413375  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_stub_internal+68)
    #08 pc 003ecca1  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_stub+224)
    #09 pc 000a1c8d  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
    #10 pc 00349d4d  /system/lib/libart.so (offset 0x2b0000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
    #11 pc 00349b77  /system/lib/libart.so (offset 0x2b0000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+310)
    #12 pc 0027f84f  /system/lib/libart.so (art::JNI::CallNonvirtualVoidMethodV(_JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list)+454)
    #13 pc 002693e5  /system/lib/libart.so (art::JNI::NewObjectV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+624)
    #14 pc 002acd63  /system/lib/libart.so (_JNIEnv::NewObject(_jclass*, _jmethodID*, ...)+30)
    #15 pc 002ea38f  /system/lib/libart.so (offset 0x2b0000) (art::Class_classForName(_JNIEnv*, _jclass*, _jstring*, unsigned char, _jobject*)+350)
    #16 pc 004e3313  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.reflect.Parameter.getAnnotationNative [DEDUPED]+146)
    #17 pc 004c18f9  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.BootClassLoader.findClass+48)
    #18 pc 004c1c39  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.BootClassLoader.loadClass+104)
    #19 pc 002d72e1  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.ClassLoader.loadClass+136)
    #20 pc 0038e19b  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (me.app.loadClass+578)
    #21 pc 002d72e1  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.ClassLoader.loadClass+136)
    #22 pc 002d7231  /system/framework/arm/boot-core-oj.oat (offset 0x2ca000) (java.lang.ClassLoader.loadClass+40)
    #23 pc 00413375  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_stub_internal+68)
    #24 pc 003ecca1  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_stub+224)
    #25 pc 000a1c8d  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
    #26 pc 00349d4d  /system/lib/libart.so (offset 0x2b0000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
    #27 pc 0034acc1  /system/lib/libart.so (offset 0x2b0000) (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+320)
    #28 pc 0026b2c3  /system/lib/libart.so (art::JNI::CallObjectMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+450)
    #29 pc 000ded8f  /system/lib/libart.so (_JNIEnv::CallObjectMethod(_jobject*, _jmethodID*, ...)+30)
    #30 pc 000ddb2b  /system/lib/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+2594)
    #31 pc 000f1467  /system/lib/libart.so (art::ClassLinker::DoResolveType(art::dex::TypeIndex, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>)+118)
    #32 pc 003955d1  /system/lib/libart.so (offset 0x2b0000) (_ZN3art8verifier14MethodVerifier12ResolveClassILNS1_11CheckAccessE0EEERKNS0_7RegTypeENS_3dex9TypeIndexE+112)
    #33 pc 0039d981  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::CodeFlowVerifyInstruction(unsigned int*)+6472)
    #34 pc 0039bda7  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::CodeFlowVerifyMethod()+214)
    #35 pc 0039a7c1  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::VerifyCodeFlow()+576)
    #36 pc 00398c4f  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::Verify()+5762)
    #37 pc 00396c9d  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::VerifyMethod(art::Thread*, unsigned int, art::DexFile const*, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>, art::DexFile::ClassDef const&, art::DexFile::CodeItem const*, art::ArtMethod*, unsigned int, art::CompilerCallbacks*, bool, art::verifier::HardFailLogMode, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+96)
    #38 pc 003965a5  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::VerifyClass(art::Thread*, art::DexFile const*, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>, art::DexFile::ClassDef const&, art::CompilerCallbacks*, bool, art::verifier::HardFailLogMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+1140)
    #39 pc 00395f5d  /system/lib/libart.so (offset 0x2b0000) (art::verifier::MethodVerifier::VerifyClass(art::Thread*, art::mirror::Class*, art::CompilerCallbacks*, bool, art::verifier::HardFailLogMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+352)
    #40 pc 000e3f8d  /system/lib/libart.so (art::ClassLinker::PerformClassVerification(art::Thread*, art::Handle<art::mirror::Class>, art::verifier::HardFailLogMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+60)
    #41 pc 000e321f  /system/lib/libart.so (art::ClassLinker::VerifyClass(art::Thread*, art::Handle<art::mirror::Class>, art::verifier::HardFailLogMode)+1110)
    #42 pc 000e5ba3  /system/lib/libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+238)
    #43 pc 000d6097  /system/lib/libart.so (art::ClassLinker::EnsureInitialized(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+130)
    #44 pc 001e6ef5  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+332)
    #45 pc 001e198f  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+814)
    #46 pc 003e88db  /system/lib/libart.so (offset 0x2b0000) (MterpInvokeStatic+130)
    #47 pc 00406214  /system/lib/libart.so (offset 0x2b0000) (ExecuteMterpImpl+14612)
    #48 pc 002967e8  <anonymous:ae75e000> (com.dahuo.sunflower.xp.ʻ$1.afterHookedMethod+144)
    #49 pc 001c610b  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1192137911+378)
    #50 pc 001ca737  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
    #51 pc 003db401  /system/lib/libart.so (offset 0x2b0000) (artQuickToInterpreterBridge+880)
    #52 pc 004178ff  /system/lib/libart.so (offset 0x2b0000) (art_quick_to_interpreter_bridge+30)
    #53 pc 0030b90f  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (de.robv.android.xposed.ExposedHelper.afterHookedMethod+38)
    #54 pc 008456f3  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (me.apl$ᐝ.afterHookedMethod+282)
    #55 pc 0030b90f  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (de.robv.android.xposed.ExposedHelper.afterHookedMethod+38)
    #56 pc 00645e9d  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (me.apo$ʻ.ᐝ+292)
    #57 pc 00365915  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (me.anc.a+1164)
    #58 pc 0036545f  /data/app/me.weishu.exp-qRvlRL0pP7fQ2a2KWRXt5A==/oat/arm/base.odex (offset 0x267000) (me.anc.a+78)
    #59 pc 00413375  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_stub_internal+68)
    #60 pc 003ecda3  /system/lib/libart.so (offset 0x2b0000) (art_quick_invoke_static_stub+222)
    #61 pc 000a1c9f  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
    #62 pc 001e6e95  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
    #63 pc 001e198f  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+814)
    #64 pc 003e88db  /system/lib/libart.so (offset 0x2b0000) (MterpInvokeStatic+130)
    #65 pc 00406214  /system/lib/libart.so (offset 0x2b0000) (ExecuteMterpImpl+14612)
    #66 pc 0000022c  <anonymous:e9ddf000> (android.content.ContextWrapper_1886535560.attachBaseContext+36)
    #67 pc 001c610b  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1192137911+378)
    #68 pc 001ca737  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
    #69 pc 003db401  /system/lib/libart.so (offset 0x2b0000) (artQuickToInterpreterBridge+880)
    #70 pc 004178ff  /system/lib/libart.so (offset 0x2b0000) (art_quick_to_interpreter_bridge+30)
    #71 pc 00000d37  <anonymous:bc8fe000>

</code></pre></details>

**Comment by keta1** [comment]
更新太极到7.0.3以上版本
