### ISSUE TITLE
QQ8.8.5 桌面图标消息个数错误

### ISSUE THREAD

**Issue by 3272780473** [ferredoxin/QNotified#946]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.5

**模块版本/Module Version**

* 0.8.20.1a2d6c5

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极 曳影7.0.3.05282148

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
不知道什么时候就会出现消息显示个数错误，数字随机，QQ里面没有提醒的消息但是桌面就是显示有未读消息

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by cinit** [comment]
@3272780473 请问是否开启了自定义机型？

**Comment by ufvi** [comment]
好像是自定义机型的问题
