### ISSUE TITLE
[QQ8.8.5] QQ净化-聊天-隐藏互动标识功能失效

### ISSUE THREAD

**Issue by Narase-Edge** [ferredoxin/QNotified#949]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.5

**模块版本/Module Version**

* 0.8.20.1b90a17

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSP v1.4.7(5803)

**问题的具体描述/Detailed Description of the Bug**

*  开启如标题所诉功能后群聊界面并未成功隐藏互动标识。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by Padcr** [comment]
能不能别发了，好烦啊...


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月13日(周二) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ferredoxin/QNotified] [QQ8.8.5] QQ净化-聊天-隐藏互动标识功能失效 (#949)




 
Closed #949.
 
&mdash;

**Comment by qwq233** [comment]
@Padcr 你自己watch还怪别人？
