### ISSUE TITLE
[Bug]QQ8.3.3 图片消息处理结果错误

### ISSUE THREAD

**Issue by zkvvabcd** [ferredoxin/QNotified#95]
![Screenshot_20200708-122042](https://user-images.githubusercontent.com/52879734/86875760-d75ea700-c115-11ea-9051-7948f75c2e89.jpg)
手机端收到的
![mmexport1594182264753](https://user-images.githubusercontent.com/52879734/86875828-fa895680-c115-11ea-8ae1-1e381c794536.png)
电脑端收到的
版本是太极6.3.0，QN是0.8.0 QQ版本是8.3.3
QN功能只开了隐藏小程序，闪照，防撤回，收藏更多表情，被删好友通知

**Comment by cinit** [comment]
确定签到文本化没开?

**Comment by zkvvabcd** [comment]
> 确定签到文本化没开？

这个没有开 是机器人发的消息 就很迷惑 几率不高

**Comment by qwq233** [comment]
请问仍有这个问题吗
