### ISSUE TITLE
[QQ880] 新设置UI的几个bug

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#953]
**QQ(TIM)版本/QQ(TIM) Version**

* 880

**模块版本/Module Version**

* 0.8.20.f0a2e80 (1626337910)

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

1. 历史设置丢失
2. 部分功能开关开启后仍无效且无法保存
3. Omega测试性功能15秒阅读锁丢失

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

木得

</code></pre></details>

**Comment by singleNeuron** [comment]
@lightoo1122 1.历史设置丢失是正常现象，回退到旧版能恢复
2.请具体举例
4.Omega测试与新UI无任何关系，只是入口变了

**Comment by tianqiqaq** [comment]
@singleNeuron 2.举例如“+1”功能失效，更换“+1”图标按钮点不开
4.旧版界面部分按钮缺失，与旧版模块的旧版界面不一致，新版界面无检查更新按钮
