### ISSUE TITLE
[功能需求] 隐藏群聊群成员头衔

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#959]
**QQ(TIM)版本/QQ(TIM) Version**

* 880

**为什么你认为需要此功能**

* 以前有的，最新版本的按钮变灰了点不了？

**联系到哪些已经存在的bug或者功能**

* 新UI设置界面此项开关为灰色

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by singleNeuron** [comment]
@lightoo1122 灰色说明不支持880

**Comment by lightoo1122** [comment]
> @lightoo1122 灰色说明不支持880

换新UI之前功能在这个版本的QQ上可用

**Comment by singleNeuron** [comment]
@lightoo1122 联系具体负责此功能的开发者解决

**Comment by keta1** [comment]
@singleNeuron 我觉得是你搞出来的

**Comment by singleNeuron** [comment]
@keta1 显然不是我
