### ISSUE TITLE
[QQ 8.8.12.5675（7月21日凌晨热补丁更新）] 对方撤回消息后的提示显示未收到

### ISSUE THREAD

**Issue by rinscr3003** [ferredoxin/QNotified#963]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.12.5675（7月21日凌晨热补丁更新）

**模块版本/Module Version**

* 0.8.20.1b90a17

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* EdXposed 4.6.2

**问题的具体描述/Detailed Description of the Bug**
对方撤回消息后的提示显示未收到
*  具体描述(如复现BUG所需要的前提和必要操作等)
用另一个账号发消息并撤回。

无法找到生成的日志文件

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by lightoo1122** [comment]
是部分消息提示未收到嘛（那是正常的），如果是所有可能是QQ和谐了
不过防撤回的原理是记录收到的消息撤回的时候再把它输出，可能是你QQ没在后台运行导致的？

**Comment by rinscr3003** [comment]
> 是部分消息提示未收到嘛（那是正常的），如果是所有可能是QQ和谐了
> 不过防撤回的原理是记录收到的消息撤回的时候再把它输出，可能是你QQ没在后台运行导致的？

所有消息都是这样，而且测试时保持在前台运行（就盯着那个群）。  
消息不会消失，但是冒出来那一条不能显示撤回了哪一条而是提示未收到。
