### ISSUE TITLE
[版本 8.2.11] 设置里面的二级界面无法打开

### ISSUE THREAD

**Issue by wangzhenxing4** [ferredoxin/QNotified#967]
**QQ(TIM)版本/QQ(TIM) Version**
版本 8.2.11
* 

**模块版本/Module Version**
包括0.8.20.f0a2e80(1626337910)之后
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
lsposed5824
* 

**问题的具体描述/Detailed Description of the Bug**
点击设置-qn-可以进入，但是在qn界面里面再点击无法使用打开
*  具体描述(如复现BUG所需要的前提和必要操作等)
点击设置-qn-可以进入，但是在qn界面里面再点击无法使用

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
qq升级到855试试

**Comment by wangzhenxing4** [comment]
> qq升级到855精灵

不想使用国内版本，在肿瘤了，我已经暂停更新了，0.8.2.0e9f23e1（1627018579）依然无法使用

**Comment by qwq233** [comment]
> > qq升级到855精灵
> 
> 不想使用国内版本，在肿瘤了，我已经暂停更新了，0.8.2.0e9f23e1（1627018579）依然无法使用

建议别用play版
