### ISSUE TITLE
[功能需求] 联系人重排序

### ISSUE THREAD

**Issue by lightoo1122** [ferredoxin/QNotified#970]
**QQ(TIM)版本/QQ(TIM) Version**

* 883

**为什么你认为需要此功能**

* 联系人svip前排显示

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

忽略联系人SVIP前排显示，按照音序排列

**Comment by cinit** [comment]
https://github.com/cinit/QAuxiliary/commit/f16fcf342e4e193eeb2482eda7aad83857c02343 做了分组列表重排，但排序是根据 strcmp 做的，如果要支持拼音感觉好麻烦
