### ISSUE TITLE
[8.8.12] 无法隐藏侧滑栏图标

### ISSUE THREAD

**Issue by Swag-Bull** [ferredoxin/QNotified#973]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.12
* 

**模块版本/Module Version**
0.8.20.5a17f16
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极：曳影·7.0.3.05282148
* 

**问题的具体描述/Detailed Description of the Bug**
无法隐藏侧滑栏图标
*  具体描述(如复现BUG所需要的前提和必要操作等)
每次设置后重启qq都不生效

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by singleNeuron** [comment]
@Swag-Bull 没适配新版QQ
