### ISSUE TITLE
[QQ8.8.12]语音转发功能失效

### ISSUE THREAD

**Issue by zhuixingzhe-baisheng** [ferredoxin/QNotified#975]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**模块版本/Module Version**

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)更新QQ后发现一部分功能失效，希望尽早适配，谢谢！

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by y2199972285** [comment]
语音转发失效了。。

**Comment by singleNeuron** [comment]
@github-actions[bot] keep open
