### ISSUE TITLE
最新版本

### ISSUE THREAD

**Issue by hhk2303** [ferredoxin/QNotified#981]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**模块版本/Module Version**

* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

能适配一下安卓12吗

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by qwq233** [comment]
不可以

**Comment by singleNeuron** [comment]
@hhk2303 ？安卓12怎么了，我用着好好的啊
