### ISSUE TITLE
[qq8.2.8] 无法切换简洁模式

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [ferredoxin/QNotified#982]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.2.8

**模块版本/Module Version**

* Version 0.8.20.2eb5b4a

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* xposed 89 x86_64

**问题的具体描述/Detailed Description of the Bug**
qq无法开启简洁模式（无法切换主题）
*  具体描述(如复现BUG所需要的前提和必要操作等)
切换夜间模式提示“主题文件切换失败”，切换简介模式提示“简洁模式启用超时 请稍后重试”再次点击提示“正在切换中请稍后重试”
尝试过的方法1.等2.清缓存3.重装qq4.某度娘
（不希望把qq换为高版本 因为之前用的play版......嗯...；希望作者大大可以解决这个问题或在模块中添加一个强制设置qq为简洁模式的功能）

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）（抱歉大佬我不知道日志在哪里 找不到 希望下次把入口放在明显的地方或者在github说明一下吧）

</code></pre></details>

**Comment by singleNeuron** [comment]
@YaeSakuraQvQ 你用没用sub主题

**Comment by YaeSakuraQvQ** [comment]
> @YaeSakuraQvQ你用没用sub主题

什么意思...麻烦大佬可以再说的细一点嘛（如 解决方法之类的）谢谢~

**Comment by singleNeuron** [comment]
@YaeSakuraQvQ 解决办法啊，一般这种情况清除QQ缓存试试，清除缓存没用就清除数据，不需要升级。

**Comment by YaeSakuraQvQ** [comment]
> @YaeSakuraQvQ 解决办法啊，一般这种情况清除QQ缓存试试，清除缓存没用就清除数据，不需要升级。

已经试过了啊 我上面有写 “2.清缓存3.重装qq” 就是这方法我已经试完了 没有用  麻烦大佬给个我没用过的可行方法吧，谢谢~

**Comment by singleNeuron** [comment]
@YaeSakuraQvQ 不开qn能切换吗

**Comment by YaeSakuraQvQ** [comment]
> @YaeSakuraQvQ 不开qn能切换吗

可以...但是开了qn之后又变成了上蓝下白的默认主题（而且这时候进去设置里简洁模式的开关处于“开“的状态 但简介模式并没有生效）

**Comment by singleNeuron** [comment]
@YaeSakuraQvQ qn都开了哪些功能

**Comment by YaeSakuraQvQ** [comment]
> @YaeSakuraQvQ qn都开了哪些功能

都是一些净化向的 例如去除...屏蔽...等 还有防闪照和防撤回

**Comment by lightoo1122** [comment]
你是不是用了QQcolor啊，用了这个切换主题就会有提示

**Comment by YaeSakuraQvQ** [comment]
> 你是不是用了QQcolor啊，用了这个切换主题就会有提示

我应该没用过...最近我用一个特殊的方法解决了 就是先关掉qn 开夜间模式 然后用备份软件(我用的钛备份)备份qq的数据 然后打开qn并还原数据 然后就阔以在qn下正常夜间模式了 还是谢谢啦~
