### ISSUE TITLE
[功能需求] 空间自动点赞

### ISSUE THREAD

**Issue by dfmjndm** [ferredoxin/QNotified#991]
**QQ(TIM)版本/QQ(TIM) Version**

* 

**为什么你认为需要此功能**

* 增加和好友间的互动

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)

**Comment by singleNeuron** [comment]
@dfmjndm 做梦呢，不可能支持的
