### ISSUE TITLE
[功能需求] 开屏的log信息的保存

### ISSUE THREAD

**Issue by 0x00Finch** [ferredoxin/QNotified#993]
**QQ(TIM)版本/QQ(TIM) Version**
极速版4.0.1
* 

**为什么你认为需要此功能**
把这些扫描的东西存在一个地方，下一次打开的时候是否能快许多呢？
* 

**联系到哪些已经存在的bug或者功能**

* 

**具体功能需要/Specific features required**

*  具体描述(如使用的场景，面临的问题)
每次开应用，都会加载一遍，导致每次打开都非常慢
![Screenshot_20210802-111218~2.jpg](https://user-images.githubusercontent.com/26269474/127905863-8f7ddf58-ec3b-4cb1-8735-8b9c6915f910.jpg)

**Comment by singleNeuron** [comment]
@0x00Finch 正常情况下是有缓存的，每次启动都重新查找只能说明是出问题了

**Comment by 0x00Finch** [comment]
> @0x00Finch 正常情况下是有缓存的，每次启动都重新查找只能说明是出问题了

那你要不要log文件啥的？
