### ISSUE TITLE
[QQ 8.8.12] 防撤回功能问题

### ISSUE THREAD

**Issue by msoushi** [ferredoxin/QNotified#995]
**QQ(TIM)版本/QQ(TIM) Version**

QQ 8.8.12.5675

**模块版本/Module Version**

0.8.20.701e851

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

LSPosed 1.4.7(5803)

**问题的具体描述/Detailed Description of the Bug**

将QQ更新后，虽然防撤回功能可以正常工作，但一直显示“xxx撤回了一条消息(没收到)”

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

不太清楚在哪里获取日志诶……抱歉……

</code></pre></details>

**Comment by singleNeuron** [comment]
@msoushi 开着聊天界面对方撤回的情况下有效吗

**Comment by qwq233** [comment]
后台被杀 检查下电源相关是不是无限制

**Comment by msoushi** [comment]
刚才试了下，开着聊天界面时撤回一条消息，可以防住撤回，但还是显示“xxx撤回了一条消息（没收到）”
后台被杀的话，就和没开启防撤回一样了

**Comment by singleNeuron** [comment]
@msoushi 后台被杀了收不到是因为，腾讯服务器不会给设备推送撤回的消息，用什么方法也没用。我们只能让本地客户端不删除已经收到的又被撤回的消息。

**Comment by msoushi** [comment]
抱歉，刚才没表述清楚。
和后台没关系的，后台被杀了的话直接就看不到被撤回消息了……
测试图片已经附上
![Screenshot_20210805-140254__01.jpg](https://user-images.githubusercontent.com/67544659/128301611-e33d0ddc-01d6-45f4-8f7b-e56300433dee.jpg)

**Comment by keta1** [comment]
更新qn
